"""Narrow adapter for histogram rendering through hexafe-plotstats."""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass, replace
from io import BytesIO
from typing import Any, Iterable

import numpy as np
import pandas as pd

from modules.env_utils import FALSE_VALUES, TRUE_VALUES, env_bool
from modules.export_chart_payload_helpers import build_histogram_table_data
from modules.export_summary_utils import resolve_histogram_bin_count
from modules.matplotlib_runtime import configure_headless_matplotlib
from modules.summary_plot_palette import SUMMARY_PLOT_PALETTE

configure_headless_matplotlib()

PLOTSTATS_EXPORT_CHARTS_ENV_VAR = "METROLIZA_PLOTSTATS_EXPORT_CHARTS"
_PLOTSTATS_DISABLED_VALUES = {"0", "false", "no", "off", "disabled", "metroliza", "legacy"}
_PLOTSTATS_ENABLED_VALUES = TRUE_VALUES | frozenset({"all", "*"})


@dataclass(frozen=True)
class HistogramStatsTable:
    """Display-ready histogram statistics rows."""

    title: str
    rows: tuple[tuple[str, str], ...]
    backend: str = "metroliza"

    def as_dict(self) -> dict[str, Any]:
        return {
            "title": self.title,
            "backend": self.backend,
            "rows": [{"label": label, "value": value} for label, value in self.rows],
        }


@dataclass(frozen=True)
class HistogramRenderResult:
    """Rendered histogram image and the stats table embedded in it."""

    png_bytes: bytes
    backend: str
    stats_table: HistogramStatsTable


@dataclass(frozen=True)
class ChartArtifactPngResult:
    """Rendered chart image generated by the plotstats artifact adapter."""

    png_bytes: bytes
    backend: str
    artifact: Mapping[str, Any]


def plotstats_export_charts_enabled() -> bool:
    """Return whether Metroliza should route export chart artifacts through plotstats.

    Plotstats is the default export/dashboard chart path. Operators can set
    ``METROLIZA_PLOTSTATS_EXPORT_CHARTS=0`` or another disabled value to force
    the legacy Metroliza/native renderer path for diagnostics or rollback.
    """

    return env_bool(
        PLOTSTATS_EXPORT_CHARTS_ENV_VAR,
        default=True,
        true_values=_PLOTSTATS_ENABLED_VALUES,
        false_values=FALSE_VALUES | frozenset(_PLOTSTATS_DISABLED_VALUES),
    )


def metroliza_dashboard_plotstats_theme() -> dict[str, Any]:
    """Return serializable plotstats theme tokens aligned to Metroliza dashboards."""

    return {
        "name": "metroliza_dashboard",
        "font_family": 'Aptos, "Segoe UI", "Helvetica Neue", sans-serif',
        "font_size": 12,
        "colors": {
            "background": "#ffffff",
            "plot_background": "#ffffff",
            "text": "#1f2933",
            "muted_text": "#687385",
            "grid": SUMMARY_PLOT_PALETTE["grid"],
            "axis": SUMMARY_PLOT_PALETTE["axis_spine"],
            "bar": SUMMARY_PLOT_PALETTE["distribution_base"],
            "bar_outline": SUMMARY_PLOT_PALETTE["distribution_foreground"],
            "fit": SUMMARY_PLOT_PALETTE["central_tendency"],
            "spec_limit": SUMMARY_PLOT_PALETTE["spec_limit"],
            "nominal": SUMMARY_PLOT_PALETTE["central_tendency"],
        },
    }


def build_dashboard_plotly_spec(
    payload: Mapping[str, Any],
    *,
    title: str,
    theme: str | Mapping[str, Any] | None = None,
    static: bool = True,
) -> dict[str, Any] | None:
    """Build a bounded Plotly spec through hexafe-plotstats dashboard adapters.

    The package dependency is optional at import time for development and tests.
    Callers keep their existing static-image fallback when this returns ``None``.
    """

    if plotstats_export_charts_enabled():
        spec = build_plotstats_dashboard_spec(
            payload,
            title=title,
            theme="light" if isinstance(theme, Mapping) else str(theme or "light"),
            static=static,
        )
        if spec:
            return spec

    try:
        from hexafe_plotstats.adapters import plotly_spec_from_metroliza_dashboard_payload
    except Exception:
        return None

    try:
        spec = plotly_spec_from_metroliza_dashboard_payload(
            payload,
            title=title,
            theme=theme or metroliza_dashboard_plotstats_theme(),
            static=static,
        )
    except Exception:
        return None
    if not isinstance(spec, dict):
        return None
    data = spec.get("data")
    if not isinstance(data, list) or not data:
        return None
    layout = spec.get("layout") if isinstance(spec.get("layout"), dict) else {}
    config = spec.get("config") if isinstance(spec.get("config"), dict) else {}
    return {
        "data": data,
        "layout": layout,
        "config": config,
        "metadata": spec.get("metadata") if isinstance(spec.get("metadata"), dict) else {},
    }


def build_chart_artifact(
    payload: Mapping[str, Any],
    *,
    target: str,
    title: str | None = None,
    theme: str | Mapping[str, Any] | None = None,
    backend: str = "auto",
    include_plotly: bool = True,
    include_png: bool = False,
    static: bool | None = None,
) -> dict[str, Any] | None:
    """Build a plotstats chart artifact when the installed package supports it."""

    try:
        from hexafe_plotstats.adapters import chart_artifact_from_metroliza_payload
    except Exception:
        return None

    payload_mapping = dict(payload)
    if title is not None and not payload_mapping.get("title"):
        payload_mapping["title"] = title
    try:
        artifact = chart_artifact_from_metroliza_payload(
            payload_mapping,
            target=target,
            theme=theme or metroliza_dashboard_plotstats_theme(),
            backend=backend,
            include_plotly=include_plotly,
            include_png=include_png,
            static=static,
        )
    except Exception:
        return None
    return artifact if isinstance(artifact, dict) else None


def build_plotstats_dashboard_spec(
    payload: Mapping[str, Any],
    *,
    title: str,
    theme: str = "light",
    static: bool = True,
) -> dict[str, Any] | None:
    """Build an HTML-dashboard Plotly spec through the new artifact contract."""

    dashboard_theme = metroliza_dashboard_plotstats_theme()
    dashboard_theme["dashboard_theme"] = str(theme or "light")
    artifact = build_chart_artifact(
        payload,
        target="html_dashboard",
        title=title,
        theme=dashboard_theme,
        include_plotly=True,
        include_png=False,
        static=static,
    )
    if not artifact:
        return None
    spec = artifact.get("plotly_spec")
    if not _valid_plotly_spec(spec):
        return None
    return _trim_plotly_spec(spec)


def render_chart_artifact_png(
    payload: Mapping[str, Any],
    *,
    target: str = "workbook_image",
    backend: str = "auto",
) -> ChartArtifactPngResult | None:
    """Render a chart PNG through plotstats artifact API when available."""

    artifact = build_chart_artifact(
        payload,
        target=target,
        backend=backend,
        include_plotly=False,
        include_png=True,
        static=True,
    )
    if not artifact:
        return None
    png_bytes = artifact.get("png_bytes")
    if not isinstance(png_bytes, (bytes, bytearray)) or not png_bytes:
        return None
    backend_name = str(artifact.get("backend") or "hexafe-plotstats")
    return ChartArtifactPngResult(
        png_bytes=bytes(png_bytes),
        backend=backend_name,
        artifact=artifact,
    )


def build_histogram_stats_table(
    values: Iterable[Any],
    *,
    title: str = "Parameter",
    backend: str = "metroliza",
    lsl: float | None = None,
    usl: float | None = None,
) -> HistogramStatsTable | None:
    array = _finite_values(values)
    if array.size == 0:
        return None
    package_rows = _histogram_table_rows_from_plotstats(array, lsl=lsl, usl=usl)
    if package_rows:
        rows = _normalize_histogram_capability_rows(package_rows, lsl=lsl, usl=usl)
        resolved_backend = "hexafe-plotstats"
    else:
        table_payload = build_histogram_table_data(_summary_stats(array, lsl=lsl, usl=usl))
        rows = _normalize_histogram_capability_rows(
            tuple((str(label), str(value)) for label, value in table_payload.get("rows", ())),
            lsl=lsl,
            usl=usl,
        )
        resolved_backend = backend
    return HistogramStatsTable(title=str(title or "Parameter"), rows=rows, backend=resolved_backend)


def render_histogram_png(
    values: Iterable[Any],
    *,
    title: str,
    metric_label: str,
    bin_count: int | None = None,
    lsl: float | None = None,
    usl: float | None = None,
) -> HistogramRenderResult | None:
    """Render a histogram PNG through hexafe-plotstats, falling back to local Matplotlib."""

    array = _finite_values(values)
    if array.size == 0:
        return None
    resolved_bin_count = _resolved_bin_count(array, bin_count=bin_count)
    stats_table = build_histogram_stats_table(
        array,
        title="Parameter",
        backend="hexafe-plotstats",
        lsl=lsl,
        usl=usl,
    )
    if stats_table is None:
        return None

    result = _render_with_hexafe_plotstats(
        array,
        title=title,
        metric_label=metric_label,
        bin_count=resolved_bin_count,
        stats_table=stats_table,
        lsl=lsl,
        usl=usl,
    )
    if result is not None:
        return result
    return _render_with_metroliza_fallback(
        array,
        title=title,
        metric_label=metric_label,
        bin_count=resolved_bin_count,
        stats_table=replace(stats_table, backend="metroliza-fallback"),
    )


def _render_with_hexafe_plotstats(
    values: np.ndarray,
    *,
    title: str,
    metric_label: str,
    bin_count: int,
    stats_table: HistogramStatsTable,
    lsl: float | None = None,
    usl: float | None = None,
) -> HistogramRenderResult | None:
    try:
        from hexafe_plotstats import HistogramConfig, build_histogram_payload, render_histogram
        from hexafe_plotstats.models.common import SpecLimits
        from hexafe_plotstats.models.payloads import TableRow
    except Exception:
        return None

    try:
        spec_limits = SpecLimits(lsl=lsl, nominal=_nominal_from_limits(lsl, usl), usl=usl)
        payload = build_histogram_payload(
            values,
            spec_limits=spec_limits,
            config=HistogramConfig(bins=bin_count, density=False, include_fit=True),
            metadata={
                "title": title,
                "axis_labels": {"x": metric_label, "y": "Count"},
            },
        )
        payload = replace(
            payload,
            table_rows=tuple(
                TableRow(label=label, value=value, kind="summary_metric")
                for label, value in stats_table.rows
            ),
        )
        render_result = render_histogram(payload, backend="matplotlib")
        png_bytes = _figure_png_bytes(render_result.fig)
        return HistogramRenderResult(
            png_bytes=png_bytes,
            backend="hexafe-plotstats",
            stats_table=stats_table,
        )
    except Exception:
        return None
    finally:
        _close_plotstats_figure(locals().get("render_result"))


def _render_with_metroliza_fallback(
    values: np.ndarray,
    *,
    title: str,
    metric_label: str,
    bin_count: int,
    stats_table: HistogramStatsTable,
) -> HistogramRenderResult:
    import matplotlib.pyplot as plt

    fig = plt.figure(figsize=(7.4, 3.7))
    try:
        grid = fig.add_gridspec(1, 2, width_ratios=(3.0, 1.35), wspace=0.25)
        ax = fig.add_subplot(grid[0, 0])
        table_ax = fig.add_subplot(grid[0, 1])
        ax.hist(
            values,
            bins=bin_count,
            color=SUMMARY_PLOT_PALETTE["distribution_base"],
            edgecolor=SUMMARY_PLOT_PALETTE["distribution_foreground"],
            alpha=0.82,
        )
        ax.set_title(title, color=SUMMARY_PLOT_PALETTE["annotation_text"])
        ax.set_xlabel(metric_label, color=SUMMARY_PLOT_PALETTE["axis_text"])
        ax.set_ylabel("Count", color=SUMMARY_PLOT_PALETTE["axis_text"])
        ax.grid(
            True,
            axis="y",
            color=SUMMARY_PLOT_PALETTE["grid"],
            linewidth=0.5,
            alpha=0.45,
        )
        for spine in ax.spines.values():
            spine.set_color(SUMMARY_PLOT_PALETTE["axis_spine"])
        ax.tick_params(axis="both", colors=SUMMARY_PLOT_PALETTE["axis_text"])
        _draw_stats_table(table_ax, stats_table)
        fig.subplots_adjust(left=0.08, right=0.98, bottom=0.16, top=0.88, wspace=0.28)
        png_bytes = _figure_png_bytes(fig)
    finally:
        plt.close(fig)
    return HistogramRenderResult(
        png_bytes=png_bytes,
        backend=stats_table.backend,
        stats_table=stats_table,
    )


def _histogram_table_rows_from_plotstats(
    values: np.ndarray,
    *,
    lsl: float | None = None,
    usl: float | None = None,
) -> tuple[tuple[str, str], ...]:
    try:
        from hexafe_plotstats import HistogramConfig, build_histogram_payload
        from hexafe_plotstats.models.common import SpecLimits
    except Exception:
        return ()
    try:
        payload = build_histogram_payload(
            values,
            spec_limits=SpecLimits(lsl=lsl, nominal=_nominal_from_limits(lsl, usl), usl=usl),
            config=HistogramConfig(density=False, include_fit=True),
        )
    except Exception:
        return ()
    rows = []
    for row in getattr(payload, "table_rows", ()) or ():
        label = str(getattr(row, "label", "") or "").strip()
        value = str(getattr(row, "value", "") or "").strip()
        if label:
            rows.append((label, value))
    return tuple(rows)


def _nominal_from_limits(lsl: float | None, usl: float | None) -> float | None:
    if lsl is not None and usl is not None and lsl <= usl:
        return (float(lsl) + float(usl)) / 2.0
    return None


def _normalize_histogram_capability_rows(
    rows: tuple[tuple[str, str], ...],
    *,
    lsl: float | None,
    usl: float | None,
) -> tuple[tuple[str, str], ...]:
    has_lsl = lsl is not None
    has_usl = usl is not None
    has_any_limit = has_lsl or has_usl
    has_two_sided_limits = has_lsl and has_usl
    normalized: list[tuple[str, str]] = []
    seen_labels: set[str] = set()

    for raw_label, raw_value in rows:
        label = str(raw_label or "").strip()
        value = str(raw_value or "").strip()
        label_key = label.casefold().replace(" ", "")
        if label_key == "cp":
            label = "Cp"
            if not has_two_sided_limits:
                value = "N/A"
        elif label_key in {"cpk", "cpu", "cpl"}:
            label = "Cpk"
            if not has_any_limit:
                value = "N/A"
        elif label_key == "nok":
            label = "NOK"
            if not has_any_limit:
                value = "N/A"
        elif label_key in {"nok%", "nokpct"}:
            label = "NOK %"
            if not has_any_limit:
                value = "N/A"
        if label:
            seen_labels.add(label.casefold())
        normalized.append((label, value))

    required_rows: list[tuple[str, str]] = []
    if "cp" not in seen_labels:
        required_rows.append(("Cp", "N/A" if not has_two_sided_limits else ""))
    if "cpk" not in seen_labels:
        required_rows.append(("Cpk", "N/A" if not has_any_limit else ""))
    if not has_any_limit:
        if "nok" not in seen_labels:
            required_rows.append(("NOK", "N/A"))
        if "nok %" not in seen_labels:
            required_rows.append(("NOK %", "N/A"))

    for label, value in required_rows:
        normalized = _insert_histogram_row_before_samples(normalized, (label, value))
    return tuple(normalized)


def _insert_histogram_row_before_samples(
    rows: list[tuple[str, str]],
    row: tuple[str, str],
) -> list[tuple[str, str]]:
    for index, (label, _value) in enumerate(rows):
        if str(label).strip().casefold() == "samples":
            return rows[:index] + [row] + rows[index:]
    return [*rows, row]


def _draw_stats_table(table_ax, stats_table: HistogramStatsTable) -> None:
    table_ax.axis("off")
    cell_text = [[label, value] for label, value in stats_table.rows]
    table = table_ax.table(
        cellText=cell_text,
        colLabels=["Parameter", "Value"],
        cellLoc="left",
        colLoc="left",
        loc="center",
    )
    table.auto_set_font_size(False)
    table.set_fontsize(8.4)
    table.scale(1.0, 1.12)
    for (row, _col), cell in table.get_celld().items():
        cell.set_edgecolor("#d1d5db")
        cell.set_linewidth(0.55)
        if row == 0:
            cell.set_facecolor("#eef2f7")
            cell.set_text_props(weight="bold", color="#111827")
        else:
            cell.set_facecolor("#ffffff")
            cell.set_text_props(color="#1f2933")
    table_ax.set_title(stats_table.title, fontsize=10, fontweight="bold", color="#111827")


def _figure_png_bytes(fig) -> bytes:
    image = BytesIO()
    fig.savefig(image, format="png", dpi=150, bbox_inches="tight")
    image.seek(0)
    return image.getvalue()


def _close_plotstats_figure(render_result) -> None:
    if render_result is None or not hasattr(render_result, "fig"):
        return
    try:
        import matplotlib.pyplot as plt

        plt.close(render_result.fig)
    except Exception:
        return


def _finite_values(values: Iterable[Any]) -> np.ndarray:
    series = pd.to_numeric(pd.Series(list(values)), errors="coerce").dropna()
    if series.empty:
        return np.asarray([], dtype=float)
    array = series.to_numpy(dtype=float)
    return array[np.isfinite(array)]


def _summary_stats(
    values: np.ndarray,
    *,
    lsl: float | None = None,
    usl: float | None = None,
) -> dict[str, Any]:
    sample_size = int(values.size)
    sigma = float(np.std(values, ddof=1)) if sample_size > 1 else None
    average = float(np.mean(values))
    below_lsl = int(np.sum(values < lsl)) if lsl is not None else 0
    above_usl = int(np.sum(values > usl)) if usl is not None else 0
    nok_count = below_lsl + above_usl
    cp: float | str = "N/A"
    cpk: float | str = "N/A"
    if sigma is not None and sigma > 0:
        if lsl is not None and usl is not None and lsl < usl:
            cp = (usl - lsl) / (6 * sigma)
            cpk = min((usl - average) / (3 * sigma), (average - lsl) / (3 * sigma))
        elif usl is not None:
            cpk = (usl - average) / (3 * sigma)
        elif lsl is not None:
            cpk = (average - lsl) / (3 * sigma)
    return {
        "minimum": float(np.min(values)),
        "maximum": float(np.max(values)),
        "average": average,
        "median": float(np.median(values)),
        "sigma": sigma,
        "cp": cp,
        "cpk": cpk,
        "lsl": lsl,
        "usl": usl,
        "capability_ci": {},
        "sample_size": sample_size,
        "nok_count": nok_count,
        "nok_pct": (nok_count / sample_size) if sample_size else 0.0,
        "observed_nok_count": nok_count,
        "observed_nok_below_lsl_count": below_lsl,
        "observed_nok_above_usl_count": above_usl,
        "observed_nok_pct": (nok_count / sample_size) if sample_size else 0.0,
        "estimated_nok_pct": None,
        "estimated_nok_ppm": None,
        "estimated_yield_pct": None,
    }


def _resolved_bin_count(values: np.ndarray, *, bin_count: int | None = None) -> int:
    if bin_count is not None and int(bin_count) > 0:
        return int(bin_count)
    return max(1, int(resolve_histogram_bin_count(values).get("bin_count") or 1))


def _valid_plotly_spec(spec: Any) -> bool:
    if not isinstance(spec, dict):
        return False
    data = spec.get("data")
    return isinstance(data, list) and bool(data)


def _trim_plotly_spec(spec: Mapping[str, Any]) -> dict[str, Any]:
    return {
        "data": spec.get("data") if isinstance(spec.get("data"), list) else [],
        "layout": spec.get("layout") if isinstance(spec.get("layout"), dict) else {},
        "config": spec.get("config") if isinstance(spec.get("config"), dict) else {},
        "metadata": spec.get("metadata") if isinstance(spec.get("metadata"), dict) else {},
    }


__all__ = [
    "ChartArtifactPngResult",
    "HistogramRenderResult",
    "HistogramStatsTable",
    "PLOTSTATS_EXPORT_CHARTS_ENV_VAR",
    "build_chart_artifact",
    "build_dashboard_plotly_spec",
    "build_histogram_stats_table",
    "build_plotstats_dashboard_spec",
    "metroliza_dashboard_plotstats_theme",
    "plotstats_export_charts_enabled",
    "render_chart_artifact_png",
    "render_histogram_png",
]
