"""Narrow adapter for histogram rendering through hexafe-plotstats."""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass, replace
from decimal import Decimal, ROUND_HALF_UP
from io import BytesIO
import math
import re
from typing import Any, Iterable

import numpy as np
import pandas as pd

from modules.env_utils import FALSE_VALUES, TRUE_VALUES, env_bool
from modules.export_chart_payload_helpers import build_histogram_table_data
from modules.export_summary_utils import resolve_histogram_bin_count
from modules.matplotlib_runtime import configure_headless_matplotlib
from modules.summary_plot_palette import SUMMARY_PLOT_PALETTE

configure_headless_matplotlib()

PLOTSTATS_EXPORT_CHARTS_ENV_VAR = "METROLIZA_PLOTSTATS_EXPORT_CHARTS"
_PLOTSTATS_DISABLED_VALUES = {"0", "false", "no", "off", "disabled", "metroliza", "legacy"}
_PLOTSTATS_ENABLED_VALUES = TRUE_VALUES | frozenset({"all", "*"})
_PLOTLY_GROUP_COLORWAY = (
    SUMMARY_PLOT_PALETTE["distribution_foreground"],
    "#D55E00",
    "#009E73",
    SUMMARY_PLOT_PALETTE["outlier"],
    SUMMARY_PLOT_PALETTE["central_tendency"],
    SUMMARY_PLOT_PALETTE["distribution_base"],
)


@dataclass(frozen=True)
class HistogramStatsTable:
    """Display-ready histogram statistics rows."""

    title: str
    rows: tuple[tuple[str, str], ...]
    backend: str = "metroliza"

    def as_dict(self) -> dict[str, Any]:
        return {
            "title": self.title,
            "backend": self.backend,
            "rows": [{"label": label, "value": value} for label, value in self.rows],
        }


@dataclass(frozen=True)
class HistogramRenderResult:
    """Rendered histogram image and the stats table embedded in it."""

    png_bytes: bytes
    backend: str
    stats_table: HistogramStatsTable


@dataclass(frozen=True)
class ChartArtifactPngResult:
    """Rendered chart image generated by the plotstats artifact adapter."""

    png_bytes: bytes
    backend: str
    artifact: Mapping[str, Any]


def plotstats_export_charts_enabled() -> bool:
    """Return whether Metroliza should route export chart artifacts through plotstats.

    Plotstats is the default export/dashboard chart path. Operators can set
    ``METROLIZA_PLOTSTATS_EXPORT_CHARTS=0`` or another disabled value to force
    the legacy Metroliza/native renderer path for diagnostics or rollback.
    """

    return env_bool(
        PLOTSTATS_EXPORT_CHARTS_ENV_VAR,
        default=True,
        true_values=_PLOTSTATS_ENABLED_VALUES,
        false_values=FALSE_VALUES | frozenset(_PLOTSTATS_DISABLED_VALUES),
    )


def metroliza_dashboard_plotstats_theme() -> dict[str, Any]:
    """Return serializable plotstats theme tokens aligned to Metroliza dashboards."""

    return {
        "name": "metroliza_dashboard",
        "font_family": 'Aptos, "Segoe UI", "Helvetica Neue", sans-serif',
        "font_size": 12,
        "colors": {
            "background": "#ffffff",
            "plot_background": "#ffffff",
            "text": "#1f2933",
            "muted_text": "#687385",
            "grid": SUMMARY_PLOT_PALETTE["grid"],
            "axis": SUMMARY_PLOT_PALETTE["axis_spine"],
            "bar": SUMMARY_PLOT_PALETTE["distribution_base"],
            "bar_outline": SUMMARY_PLOT_PALETTE["distribution_foreground"],
            "fit": SUMMARY_PLOT_PALETTE["central_tendency"],
            "spec_limit": SUMMARY_PLOT_PALETTE["spec_limit"],
            "nominal": SUMMARY_PLOT_PALETTE["central_tendency"],
        },
    }


def build_dashboard_plotly_spec(
    payload: Mapping[str, Any],
    *,
    title: str,
    theme: str | Mapping[str, Any] | None = None,
    static: bool = True,
) -> dict[str, Any] | None:
    """Build a bounded Plotly spec through hexafe-plotstats dashboard adapters.

    The package dependency is optional at import time for development and tests.
    Callers keep their existing static-image fallback when this returns ``None``.
    """

    payload = _payload_with_resolved_histogram_bin_count(payload)

    if plotstats_export_charts_enabled():
        spec = build_plotstats_dashboard_spec(
            payload,
            title=title,
            theme="light" if isinstance(theme, Mapping) else str(theme or "light"),
            static=static,
        )
        if spec:
            return spec

    try:
        from hexafe_plotstats.adapters import plotly_spec_from_metroliza_dashboard_payload
    except Exception:
        return _fallback_dashboard_plotly_spec(payload, title=title, static=static)

    try:
        spec = plotly_spec_from_metroliza_dashboard_payload(
            payload,
            title=title,
            theme=theme or metroliza_dashboard_plotstats_theme(),
            static=static,
        )
    except Exception:
        return _fallback_dashboard_plotly_spec(payload, title=title, static=static)
    if not isinstance(spec, dict):
        return _fallback_dashboard_plotly_spec(payload, title=title, static=static)
    data = spec.get("data")
    if not isinstance(data, list) or not data:
        return _fallback_dashboard_plotly_spec(payload, title=title, static=static)
    layout = spec.get("layout") if isinstance(spec.get("layout"), dict) else {}
    config = spec.get("config") if isinstance(spec.get("config"), dict) else {}
    raw_spec = {
        "data": data,
        "layout": layout,
        "config": config,
        "metadata": spec.get("metadata") if isinstance(spec.get("metadata"), dict) else {},
    }
    _normalize_payload_limit_trace_labels(raw_spec, payload)
    _apply_payload_histogram_bins_to_spec(raw_spec, payload)
    _normalize_payload_group_stat_trace_names(raw_spec, payload)
    _ensure_group_histogram_mean_annotations(raw_spec, payload)
    return _normalize_dashboard_plotly_spec(raw_spec)


def _fallback_dashboard_plotly_spec(
    payload: Mapping[str, Any],
    *,
    title: str,
    static: bool,
) -> dict[str, Any] | None:
    payload_type = str(payload.get("type") or "").strip().casefold()
    if payload_type == "histogram":
        return _fallback_histogram_plotly_spec(payload, title=title, static=static)
    return None


def _fallback_histogram_plotly_spec(
    payload: Mapping[str, Any],
    *,
    title: str,
    static: bool,
) -> dict[str, Any] | None:
    groups = _histogram_payload_groups(payload)
    all_values = np.concatenate([values for _label, values in groups]) if groups else np.asarray([])
    all_values = all_values[np.isfinite(all_values)]
    if not groups or all_values.size == 0:
        return None

    bin_count = _resolved_bin_count(all_values, bin_count=_payload_int(payload.get("bin_count")))
    _counts, bin_edges = np.histogram(all_values, bins=max(1, bin_count))
    centers = ((bin_edges[:-1] + bin_edges[1:]) / 2.0).tolist()
    widths = np.diff(bin_edges).tolist()
    traces: list[dict[str, Any]] = []
    for index, (label, values) in enumerate(groups):
        counts, _edges = np.histogram(values, bins=bin_edges)
        denominator = max(int(values.size), 1)
        y_values = (counts / denominator).astype(float).tolist()
        customdata = [
            [float(start), float(end), int(count), f"{start:.4g}..{end:.4g}"]
            for start, end, count in zip(bin_edges[:-1], bin_edges[1:], counts, strict=False)
        ]
        traces.append(
            {
                "type": "bar",
                "name": str(label),
                "x": centers,
                "y": y_values,
                "width": widths,
                "opacity": 0.72 if len(groups) > 1 else 0.9,
                "marker": {"color": _PLOTLY_GROUP_COLORWAY[index % len(_PLOTLY_GROUP_COLORWAY)]},
                "customdata": customdata,
                "hovertemplate": (
                    "bin=%{customdata[0]:.4g}..%{customdata[1]:.4g}<br>"
                    "frequency=%{y:.2%}<br>"
                    "count=%{customdata[2]}<extra></extra>"
                ),
            }
        )
    traces.extend(_histogram_reference_traces(all_values, limits=payload.get("limits")))

    style = payload.get("style") if isinstance(payload.get("style"), Mapping) else {}
    x_label = str(style.get("axis_label_x") or payload.get("x_label") or "Value")
    spec = {
        "data": traces,
        "layout": {
            "title": {"text": title},
            "barmode": "overlay" if len(groups) > 1 else "relative",
            "xaxis": {"title": {"text": x_label}},
            "yaxis": {"title": {"text": "Frequency (%)"}},
            "legend": {"orientation": "h"},
        },
        "config": {"responsive": True, "displaylogo": False, "staticPlot": bool(static)},
        "metadata": {"kind": "histogram", "histogram_y_mode": "percent"},
    }
    _ensure_group_histogram_mean_annotations(spec, payload)
    return _normalize_dashboard_plotly_spec(spec)


def _histogram_payload_groups(payload: Mapping[str, Any]) -> list[tuple[str, np.ndarray]]:
    raw_groups = payload.get("groups")
    groups: list[tuple[str, np.ndarray]] = []
    if isinstance(raw_groups, list):
        for index, item in enumerate(raw_groups, start=1):
            if not isinstance(item, Mapping):
                continue
            values = _finite_values(item.get("values") or ())
            if values.size:
                groups.append((str(item.get("group") or f"Group {index}"), values))
        return groups
    values = _finite_values(payload.get("values") or ())
    return [("Frequency", values)] if values.size else []


def _histogram_reference_traces(
    values: np.ndarray,
    *,
    limits: Any,
) -> list[dict[str, Any]]:
    traces: list[dict[str, Any]] = []
    limits_mapping = limits if isinstance(limits, Mapping) else {}
    reference_values: list[tuple[str, float | None, str]] = [
        ("Min", float(np.min(values)), "#7c3aed"),
        ("Q1", float(np.quantile(values, 0.25)), "#7c3aed"),
        ("Median", float(np.median(values)), "#0f766e"),
        ("Mean", float(np.mean(values)), "#2563eb"),
        ("Q3", float(np.quantile(values, 0.75)), "#7c3aed"),
        ("Max", float(np.max(values)), "#7c3aed"),
        ("LSL", _optional_float(limits_mapping.get("lsl")), "#b91c1c"),
        ("Nominal", _optional_float(limits_mapping.get("nominal")), "#0f766e"),
        ("USL", _optional_float(limits_mapping.get("usl")), "#b91c1c"),
    ]
    for label, value, color in reference_values:
        if value is None or not math.isfinite(value):
            continue
        formatted = _format_metrology_legend_value(label, value)
        traces.append(
            {
                "type": "scatter",
                "mode": "lines",
                "name": label,
                "x": [value, value],
                "y": [0.0, 1.0],
                "line": {"color": color, "width": 1.5, "dash": "dash"},
                "hovertemplate": f"{label}={formatted}<extra></extra>",
            }
        )
    return traces


def _payload_int(value: Any) -> int | None:
    try:
        parsed = int(value)
    except (TypeError, ValueError):
        return None
    return parsed if parsed > 0 else None


def _optional_float(value: Any) -> float | None:
    try:
        parsed = float(value)
    except (TypeError, ValueError):
        return None
    return parsed if math.isfinite(parsed) else None


def _normalize_payload_limit_trace_labels(spec: Mapping[str, Any], payload: Mapping[str, Any]) -> None:
    limits = payload.get("limits") if isinstance(payload.get("limits"), Mapping) else {}
    if not limits:
        return
    limit_values = {
        "LSL": _optional_float(limits.get("lsl")),
        "USL": _optional_float(limits.get("usl")),
    }
    data = spec.get("data")
    if not isinstance(data, list):
        return
    for trace in data:
        if not isinstance(trace, dict):
            continue
        label = str(trace.get("name") or "").strip()
        label_key = label.casefold().replace("_", " ")
        if not label_key.startswith("limit"):
            continue
        _axis, value = _constant_line_axis_and_value(trace)
        matched_label = _matching_limit_label(value, limit_values)
        if matched_label is None:
            if "1" in label_key and limit_values.get("LSL") is not None:
                matched_label = "LSL"
            elif "2" in label_key and limit_values.get("USL") is not None:
                matched_label = "USL"
        if matched_label is not None:
            trace["name"] = matched_label


def _matching_limit_label(
    value: float | None,
    limit_values: Mapping[str, float | None],
) -> str | None:
    if value is None:
        return None
    for label, limit_value in limit_values.items():
        if limit_value is not None and math.isclose(value, limit_value, rel_tol=1e-9, abs_tol=1e-9):
            return label
    return None


def build_chart_artifact(
    payload: Mapping[str, Any],
    *,
    target: str,
    title: str | None = None,
    theme: str | Mapping[str, Any] | None = None,
    backend: str = "auto",
    include_plotly: bool = True,
    include_png: bool = False,
    static: bool | None = None,
) -> dict[str, Any] | None:
    """Build a plotstats chart artifact when the installed package supports it."""

    try:
        from hexafe_plotstats.adapters import chart_artifact_from_metroliza_payload
    except Exception:
        return None

    payload_mapping = dict(payload)
    if title is not None and not payload_mapping.get("title"):
        payload_mapping["title"] = title
    try:
        artifact = chart_artifact_from_metroliza_payload(
            payload_mapping,
            target=target,
            theme=theme or metroliza_dashboard_plotstats_theme(),
            backend=backend,
            include_plotly=include_plotly,
            include_png=include_png,
            static=static,
        )
    except Exception:
        return None
    return artifact if isinstance(artifact, dict) else None


def build_plotstats_dashboard_spec(
    payload: Mapping[str, Any],
    *,
    title: str,
    theme: str = "light",
    static: bool = True,
) -> dict[str, Any] | None:
    """Build an HTML-dashboard Plotly spec through the new artifact contract."""

    payload = _payload_with_resolved_histogram_bin_count(payload)
    dashboard_theme = metroliza_dashboard_plotstats_theme()
    dashboard_theme["dashboard_theme"] = str(theme or "light")
    artifact = build_chart_artifact(
        payload,
        target="html_dashboard",
        title=title,
        theme=dashboard_theme,
        include_plotly=True,
        include_png=False,
        static=static,
    )
    if not artifact:
        return None
    spec = artifact.get("plotly_spec")
    if not _valid_plotly_spec(spec):
        return None
    _normalize_payload_limit_trace_labels(spec, payload)
    _apply_payload_histogram_bins_to_spec(spec, payload)
    _normalize_payload_group_stat_trace_names(spec, payload)
    _ensure_group_histogram_mean_annotations(spec, payload)
    return _trim_plotly_spec(spec)


def normalize_distribution_stat_legend(
    spec: Mapping[str, Any],
    payload: Mapping[str, Any],
) -> dict[str, Any]:
    """Ensure distribution/IQR Plotly legends expose values for semantic stat items."""

    normalized = dict(spec)
    _normalize_payload_group_stat_trace_names(normalized, payload)
    _dedupe_visible_stat_legend_items(normalized)
    return normalized


def render_chart_artifact_png(
    payload: Mapping[str, Any],
    *,
    target: str = "workbook_image",
    backend: str = "auto",
) -> ChartArtifactPngResult | None:
    """Render a chart PNG through plotstats artifact API when available."""

    artifact = build_chart_artifact(
        payload,
        target=target,
        backend=backend,
        include_plotly=False,
        include_png=True,
        static=True,
    )
    if not artifact:
        return None
    png_bytes = artifact.get("png_bytes")
    if not isinstance(png_bytes, (bytes, bytearray)) or not png_bytes:
        return None
    backend_name = str(artifact.get("backend") or "hexafe-plotstats")
    return ChartArtifactPngResult(
        png_bytes=bytes(png_bytes),
        backend=backend_name,
        artifact=artifact,
    )


def build_histogram_stats_table(
    values: Iterable[Any],
    *,
    title: str = "Parameter",
    backend: str = "metroliza",
    lsl: float | None = None,
    usl: float | None = None,
) -> HistogramStatsTable | None:
    array = _finite_values(values)
    if array.size == 0:
        return None
    package_rows = _histogram_table_rows_from_plotstats(array, lsl=lsl, usl=usl)
    if package_rows:
        rows = _normalize_histogram_capability_rows(package_rows, lsl=lsl, usl=usl)
        resolved_backend = "hexafe-plotstats"
    else:
        table_payload = build_histogram_table_data(_summary_stats(array, lsl=lsl, usl=usl))
        rows = _normalize_histogram_capability_rows(
            tuple((str(label), str(value)) for label, value in table_payload.get("rows", ())),
            lsl=lsl,
            usl=usl,
        )
        resolved_backend = backend
    return HistogramStatsTable(title=str(title or "Parameter"), rows=rows, backend=resolved_backend)


def render_histogram_png(
    values: Iterable[Any],
    *,
    title: str,
    metric_label: str,
    bin_count: int | None = None,
    lsl: float | None = None,
    usl: float | None = None,
) -> HistogramRenderResult | None:
    """Render a histogram PNG through hexafe-plotstats, falling back to local Matplotlib."""

    array = _finite_values(values)
    if array.size == 0:
        return None
    resolved_bin_count = _resolved_bin_count(array, bin_count=bin_count)
    stats_table = build_histogram_stats_table(
        array,
        title="Parameter",
        backend="hexafe-plotstats",
        lsl=lsl,
        usl=usl,
    )
    if stats_table is None:
        return None

    result = _render_with_hexafe_plotstats(
        array,
        title=title,
        metric_label=metric_label,
        bin_count=resolved_bin_count,
        stats_table=stats_table,
        lsl=lsl,
        usl=usl,
    )
    if result is not None:
        return result
    return _render_with_metroliza_fallback(
        array,
        title=title,
        metric_label=metric_label,
        bin_count=resolved_bin_count,
        stats_table=replace(stats_table, backend="metroliza-fallback"),
    )


def _render_with_hexafe_plotstats(
    values: np.ndarray,
    *,
    title: str,
    metric_label: str,
    bin_count: int,
    stats_table: HistogramStatsTable,
    lsl: float | None = None,
    usl: float | None = None,
) -> HistogramRenderResult | None:
    try:
        from hexafe_plotstats import HistogramConfig, build_histogram_payload, render_histogram
        from hexafe_plotstats.models.common import SpecLimits
        from hexafe_plotstats.models.payloads import TableRow
    except Exception:
        return None

    try:
        spec_limits = SpecLimits(lsl=lsl, nominal=_nominal_from_limits(lsl, usl), usl=usl)
        payload = build_histogram_payload(
            values,
            spec_limits=spec_limits,
            config=HistogramConfig(bins=bin_count, density=False, include_fit=True),
            metadata={
                "title": title,
                "axis_labels": {"x": metric_label, "y": "Count"},
            },
        )
        payload = replace(
            payload,
            table_rows=tuple(
                TableRow(label=label, value=value, kind="summary_metric")
                for label, value in stats_table.rows
            ),
        )
        render_result = render_histogram(payload, backend="matplotlib")
        png_bytes = _figure_png_bytes(render_result.fig)
        return HistogramRenderResult(
            png_bytes=png_bytes,
            backend="hexafe-plotstats",
            stats_table=stats_table,
        )
    except Exception:
        return None
    finally:
        _close_plotstats_figure(locals().get("render_result"))


def _render_with_metroliza_fallback(
    values: np.ndarray,
    *,
    title: str,
    metric_label: str,
    bin_count: int,
    stats_table: HistogramStatsTable,
) -> HistogramRenderResult:
    import matplotlib.pyplot as plt

    fig = plt.figure(figsize=(7.4, 3.7))
    try:
        grid = fig.add_gridspec(1, 2, width_ratios=(3.0, 1.35), wspace=0.25)
        ax = fig.add_subplot(grid[0, 0])
        table_ax = fig.add_subplot(grid[0, 1])
        ax.hist(
            values,
            bins=bin_count,
            color=SUMMARY_PLOT_PALETTE["distribution_base"],
            edgecolor=SUMMARY_PLOT_PALETTE["distribution_foreground"],
            alpha=0.82,
        )
        ax.set_title(title, color=SUMMARY_PLOT_PALETTE["annotation_text"])
        ax.set_xlabel(metric_label, color=SUMMARY_PLOT_PALETTE["axis_text"])
        ax.set_ylabel("Count", color=SUMMARY_PLOT_PALETTE["axis_text"])
        ax.grid(
            True,
            axis="y",
            color=SUMMARY_PLOT_PALETTE["grid"],
            linewidth=0.5,
            alpha=0.45,
        )
        for spine in ax.spines.values():
            spine.set_color(SUMMARY_PLOT_PALETTE["axis_spine"])
        ax.tick_params(axis="both", colors=SUMMARY_PLOT_PALETTE["axis_text"])
        _draw_stats_table(table_ax, stats_table)
        fig.subplots_adjust(left=0.08, right=0.98, bottom=0.16, top=0.88, wspace=0.28)
        png_bytes = _figure_png_bytes(fig)
    finally:
        plt.close(fig)
    return HistogramRenderResult(
        png_bytes=png_bytes,
        backend=stats_table.backend,
        stats_table=stats_table,
    )


def _histogram_table_rows_from_plotstats(
    values: np.ndarray,
    *,
    lsl: float | None = None,
    usl: float | None = None,
) -> tuple[tuple[str, str], ...]:
    try:
        from hexafe_plotstats import HistogramConfig, build_histogram_payload
        from hexafe_plotstats.models.common import SpecLimits
    except Exception:
        return ()
    try:
        payload = build_histogram_payload(
            values,
            spec_limits=SpecLimits(lsl=lsl, nominal=_nominal_from_limits(lsl, usl), usl=usl),
            config=HistogramConfig(density=False, include_fit=True),
        )
    except Exception:
        return ()
    rows = []
    for row in getattr(payload, "table_rows", ()) or ():
        label = str(getattr(row, "label", "") or "").strip()
        value = str(getattr(row, "value", "") or "").strip()
        if label:
            rows.append((label, value))
    return tuple(rows)


def _nominal_from_limits(lsl: float | None, usl: float | None) -> float | None:
    if lsl is not None and usl is not None and lsl <= usl:
        return (float(lsl) + float(usl)) / 2.0
    return None


def _normalize_histogram_capability_rows(
    rows: tuple[tuple[str, str], ...],
    *,
    lsl: float | None,
    usl: float | None,
) -> tuple[tuple[str, str], ...]:
    has_lsl = lsl is not None
    has_usl = usl is not None
    has_any_limit = has_lsl or has_usl
    has_two_sided_limits = has_lsl and has_usl
    normalized: list[tuple[str, str]] = []
    seen_labels: set[str] = set()

    for raw_label, raw_value in rows:
        label = str(raw_label or "").strip()
        value = str(raw_value or "").strip()
        label_key = label.casefold().replace(" ", "")
        if label_key == "cp":
            label = "Cp"
            if not has_two_sided_limits:
                value = "N/A"
        elif label_key in {"cpk", "cpu", "cpl"}:
            label = "Cpk"
            if not has_any_limit:
                value = "N/A"
        elif label_key == "nok":
            label = "NOK"
            if not has_any_limit:
                value = "N/A"
        elif label_key in {"nok%", "nokpct"}:
            label = "NOK %"
            if not has_any_limit:
                value = "N/A"
        if label:
            seen_labels.add(label.casefold())
        normalized.append((label, value))

    required_rows: list[tuple[str, str]] = []
    if "cp" not in seen_labels:
        required_rows.append(("Cp", "N/A" if not has_two_sided_limits else ""))
    if "cpk" not in seen_labels:
        required_rows.append(("Cpk", "N/A" if not has_any_limit else ""))
    if not has_any_limit:
        if "nok" not in seen_labels:
            required_rows.append(("NOK", "N/A"))
        if "nok %" not in seen_labels:
            required_rows.append(("NOK %", "N/A"))

    for label, value in required_rows:
        normalized = _insert_histogram_row_before_samples(normalized, (label, value))
    return tuple(normalized)


def _insert_histogram_row_before_samples(
    rows: list[tuple[str, str]],
    row: tuple[str, str],
) -> list[tuple[str, str]]:
    for index, (label, _value) in enumerate(rows):
        if str(label).strip().casefold() == "samples":
            return rows[:index] + [row] + rows[index:]
    return [*rows, row]


def _draw_stats_table(table_ax, stats_table: HistogramStatsTable) -> None:
    table_ax.axis("off")
    cell_text = [[label, value] for label, value in stats_table.rows]
    table = table_ax.table(
        cellText=cell_text,
        colLabels=["Parameter", "Value"],
        cellLoc="left",
        colLoc="left",
        loc="center",
    )
    table.auto_set_font_size(False)
    table.set_fontsize(8.4)
    table.scale(1.0, 1.12)
    for (row, _col), cell in table.get_celld().items():
        cell.set_edgecolor("#d1d5db")
        cell.set_linewidth(0.55)
        if row == 0:
            cell.set_facecolor("#eef2f7")
            cell.set_text_props(weight="bold", color="#111827")
        else:
            cell.set_facecolor("#ffffff")
            cell.set_text_props(color="#1f2933")
    table_ax.set_title(stats_table.title, fontsize=10, fontweight="bold", color="#111827")


def _figure_png_bytes(fig) -> bytes:
    image = BytesIO()
    fig.savefig(image, format="png", dpi=150, bbox_inches="tight")
    image.seek(0)
    return image.getvalue()


def _close_plotstats_figure(render_result) -> None:
    if render_result is None or not hasattr(render_result, "fig"):
        return
    try:
        import matplotlib.pyplot as plt

        plt.close(render_result.fig)
    except Exception:
        return


def _finite_values(values: Iterable[Any]) -> np.ndarray:
    series = pd.to_numeric(pd.Series(list(values)), errors="coerce").dropna()
    if series.empty:
        return np.asarray([], dtype=float)
    array = series.to_numpy(dtype=float)
    return array[np.isfinite(array)]


def _summary_stats(
    values: np.ndarray,
    *,
    lsl: float | None = None,
    usl: float | None = None,
) -> dict[str, Any]:
    sample_size = int(values.size)
    sigma = float(np.std(values, ddof=1)) if sample_size > 1 else None
    average = float(np.mean(values))
    below_lsl = int(np.sum(values < lsl)) if lsl is not None else 0
    above_usl = int(np.sum(values > usl)) if usl is not None else 0
    nok_count = below_lsl + above_usl
    cp: float | str = "N/A"
    cpk: float | str = "N/A"
    if sigma is not None and sigma > 0:
        if lsl is not None and usl is not None and lsl < usl:
            cp = (usl - lsl) / (6 * sigma)
            cpk = min((usl - average) / (3 * sigma), (average - lsl) / (3 * sigma))
        elif usl is not None:
            cpk = (usl - average) / (3 * sigma)
        elif lsl is not None:
            cpk = (average - lsl) / (3 * sigma)
    return {
        "minimum": float(np.min(values)),
        "maximum": float(np.max(values)),
        "average": average,
        "median": float(np.median(values)),
        "sigma": sigma,
        "cp": cp,
        "cpk": cpk,
        "lsl": lsl,
        "usl": usl,
        "capability_ci": {},
        "sample_size": sample_size,
        "nok_count": nok_count,
        "nok_pct": (nok_count / sample_size) if sample_size else 0.0,
        "observed_nok_count": nok_count,
        "observed_nok_below_lsl_count": below_lsl,
        "observed_nok_above_usl_count": above_usl,
        "observed_nok_pct": (nok_count / sample_size) if sample_size else 0.0,
        "estimated_nok_pct": None,
        "estimated_nok_ppm": None,
        "estimated_yield_pct": None,
    }


def _resolved_bin_count(values: np.ndarray, *, bin_count: int | None = None) -> int:
    if bin_count is not None and int(bin_count) > 0:
        return int(bin_count)
    return max(1, int(resolve_histogram_bin_count(values).get("bin_count") or 1))


def _valid_plotly_spec(spec: Any) -> bool:
    if not isinstance(spec, dict):
        return False
    data = spec.get("data")
    return isinstance(data, list) and bool(data)


def _trim_plotly_spec(spec: Mapping[str, Any]) -> dict[str, Any]:
    trimmed = {
        "data": spec.get("data") if isinstance(spec.get("data"), list) else [],
        "layout": spec.get("layout") if isinstance(spec.get("layout"), dict) else {},
        "config": spec.get("config") if isinstance(spec.get("config"), dict) else {},
        "metadata": spec.get("metadata") if isinstance(spec.get("metadata"), dict) else {},
    }
    return _normalize_dashboard_plotly_spec(trimmed)


_REFERENCE_LEGEND_LABELS = {
    "lsl",
    "nom",
    "nominal",
    "usl",
    "mean",
    "median",
    "q1",
    "q3",
    "min",
    "minimum",
    "max",
    "maximum",
}
_REFERENCE_LEGEND_DISPLAY_LABELS = {
    "lsl": "LSL",
    "nom": "Nominal",
    "nominal": "Nominal",
    "usl": "USL",
    "mean": "Mean",
    "median": "Median",
    "q1": "Q1",
    "q3": "Q3",
    "min": "Min",
    "minimum": "Min",
    "max": "Max",
    "maximum": "Max",
}
_BIN_RANGE_PATTERN = re.compile(
    r"^\s*([+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:e[+-]?\d+)?)\s+-\s+"
    r"([+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:e[+-]?\d+)?)\s*$",
    re.IGNORECASE,
)


def _normalize_dashboard_plotly_spec(spec: dict[str, Any]) -> dict[str, Any]:
    data = [dict(trace) if isinstance(trace, Mapping) else trace for trace in spec.get("data", [])]
    layout = dict(spec.get("layout") or {})
    config = dict(spec.get("config") or {})
    metadata = dict(spec.get("metadata") or {})
    spec = {"data": data, "layout": layout, "config": config, "metadata": metadata}

    if _is_histogram_plotly_spec(spec):
        _normalize_histogram_plotly_axes(spec)
        _normalize_histogram_bar_trace_y_values(spec)
        _normalize_grouped_histogram_bins(spec)
        _normalize_histogram_overlay_traces(spec)
    _normalize_reference_trace_names_and_annotations(spec)
    _dedupe_visible_stat_legend_items(spec)
    _normalize_plotly_annotation_boxes(spec)
    if _is_histogram_plotly_spec(spec):
        _stagger_histogram_x_annotations(spec)
    return spec


def _payload_with_resolved_histogram_bin_count(payload: Mapping[str, Any]) -> Mapping[str, Any]:
    if str(payload.get("type") or "").strip().casefold() != "histogram":
        return payload
    groups = _histogram_payload_groups(payload)
    all_values = np.concatenate([values for _label, values in groups]) if groups else np.asarray([])
    all_values = all_values[np.isfinite(all_values)]
    if all_values.size == 0:
        return payload
    resolved = max(1, int(resolve_histogram_bin_count(all_values).get("bin_count") or 1))
    next_payload = dict(payload)
    next_payload["bin_count"] = resolved
    return next_payload


def _apply_payload_histogram_bins_to_spec(spec: Mapping[str, Any], payload: Mapping[str, Any]) -> None:
    if str(payload.get("type") or "").strip().casefold() != "histogram":
        return
    if isinstance(spec, dict):
        metadata = spec.setdefault("metadata", {})
        if isinstance(metadata, dict):
            metadata["kind"] = "histogram"
            metadata["histogram_y_mode"] = "percent"
    groups = _histogram_payload_groups(payload)
    all_values = np.concatenate([values for _label, values in groups]) if groups else np.asarray([])
    all_values = all_values[np.isfinite(all_values)]
    if all_values.size == 0:
        return
    data_min = float(np.min(all_values))
    data_max = float(np.max(all_values))
    if math.isclose(data_min, data_max, rel_tol=1e-9, abs_tol=1e-9):
        padding = max(abs(data_min) * 0.01, 0.5)
        data_min -= padding
        data_max += padding
    bin_count = _resolved_bin_count(all_values, bin_count=_payload_int(payload.get("bin_count")))
    bin_size = (data_max - data_min) / max(bin_count, 1)
    if not math.isfinite(bin_size) or bin_size <= 0:
        return
    for trace in spec.get("data") or []:
        if not isinstance(trace, dict) or str(trace.get("type") or "").strip().casefold() != "histogram":
            continue
        trace["histnorm"] = "probability"
        trace["xbins"] = {"start": data_min, "end": data_max, "size": bin_size}


def _normalize_payload_group_stat_trace_names(spec: Mapping[str, Any], payload: Mapping[str, Any]) -> None:
    payload_type = str(payload.get("type") or "").strip().casefold()
    if payload_type not in {"distribution", "iqr"}:
        return
    labels = [str(item) for item in (payload.get("labels") or [])]
    series_list = _payload_distribution_series(payload)
    stat_names: list[str] = []
    for index, (label, series) in enumerate(zip(labels, series_list), start=1):
        values = _finite_trace_values(series)
        if not values:
            stat_names.append(label or f"Group {index}")
            continue
        stat_names.append(_format_group_statistics_trace_name(label or f"Group {index}", values))
    for trace, stat_name in zip(spec.get("data") or [], stat_names, strict=False):
        if isinstance(trace, dict) and str(trace.get("type") or "").strip().casefold() in {"violin", "box"}:
            trace["name"] = stat_name
    _ensure_payload_distribution_stat_legend_traces(spec, payload)


def _ensure_payload_distribution_stat_legend_traces(
    spec: Mapping[str, Any],
    payload: Mapping[str, Any],
) -> None:
    data = spec.get("data")
    if not isinstance(data, list):
        return
    labels = [str(item) for item in (payload.get("labels") or [])]
    series_list = _payload_distribution_series(payload)
    existing_names = {
        str(trace.get("name") or "")
        for trace in data
        if isinstance(trace, Mapping)
    }
    populated_count = sum(1 for series in series_list if _finite_trace_values(series))
    traces: list[dict[str, Any]] = []
    single_group_stats: dict[str, float] = {}
    group_stats: dict[str, dict[str, float]] = {}
    for label, series in zip(labels, series_list, strict=False):
        values = sorted(_finite_trace_values(series))
        if not values:
            continue
        group_label = label or f"Group {len(traces) + 1}"
        prefix = "" if populated_count == 1 else f"{group_label} "
        stats = {
            "Min": min(values),
            "Q1": _percentile_sorted(values, 0.25),
            "Median": _percentile_sorted(values, 0.5),
            "Mean": sum(values) / len(values),
            "Q3": _percentile_sorted(values, 0.75),
            "Max": max(values),
        }
        group_stats[group_label] = dict(stats)
        if populated_count == 1:
            single_group_stats = dict(stats)
        for stat_label, value in stats.items():
            name = f"{prefix}{stat_label}={_format_metrology_legend_value(stat_label, value)}"
            if name in existing_names:
                continue
            traces.append(
                _legend_only_reference_trace(
                    name=name,
                    value=value,
                    color="#2563eb" if stat_label == "Mean" else "#7c3aed",
                    dash="dashdot" if stat_label == "Mean" else "dot",
                )
            )
            existing_names.add(name)
    limits = payload.get("limits") if isinstance(payload.get("limits"), Mapping) else payload
    for label, key, color, dash in (
        ("LSL", "lsl", "#b91c1c", "dash"),
        ("Nominal", "nominal", "#0f766e", "solid"),
        ("USL", "usl", "#b91c1c", "dash"),
    ):
        value = _optional_float(limits.get(key)) if isinstance(limits, Mapping) else None
        if value is None:
            continue
        name = f"{label}={_format_metrology_legend_value(label, value)}"
        if name in existing_names:
            continue
        traces.append(_legend_only_reference_trace(name=name, value=value, color=color, dash=dash))
        existing_names.add(name)
    _normalize_existing_semantic_stat_traces(
        data,
        stats=single_group_stats,
        group_stats=group_stats,
        existing_names=existing_names,
    )
    data.extend(traces)


def _payload_distribution_series(payload: Mapping[str, Any]) -> list[Any]:
    series = payload.get("series")
    if isinstance(series, list):
        return series
    values = payload.get("values")
    if isinstance(values, list):
        return values
    return []


def _normalize_existing_semantic_stat_traces(
    data: list[Any],
    *,
    stats: Mapping[str, float],
    group_stats: Mapping[str, Mapping[str, float]] | None = None,
    existing_names: set[str],
) -> None:
    group_stats = group_stats or {}
    if not stats and not group_stats:
        return
    label_to_stat = {
        "min": "Min",
        "minimum": "Min",
        "min marker": "Min",
        "max": "Max",
        "maximum": "Max",
        "max marker": "Max",
        "mean": "Mean",
        "mean marker": "Mean",
        "median": "Median",
        "q1": "Q1",
        "q3": "Q3",
    }
    visible_names: set[str] = set()
    for trace in data:
        if not isinstance(trace, dict):
            continue
        label = str(trace.get("name") or "").strip()
        stat_label, value, prefix = _semantic_stat_trace_value(
            label,
            stats=stats,
            group_stats=group_stats,
            label_to_stat=label_to_stat,
        )
        if stat_label is None:
            if _is_semantic_stat_trace_label(label, label_to_stat):
                trace["showlegend"] = False
            continue
        if value is None:
            if _is_semantic_stat_trace_label(label, label_to_stat):
                trace["showlegend"] = False
            continue
        name = f"{prefix}{stat_label}={_format_metrology_legend_value(stat_label, value)}"
        if name in visible_names:
            trace["name"] = name
            trace["showlegend"] = False
            continue
        if name in existing_names and name != label:
            trace["name"] = name
            trace["showlegend"] = False
            continue
        trace["name"] = name
        existing_names.add(name)
        if trace.get("showlegend", True) is not False:
            visible_names.add(name)


def _semantic_stat_trace_value(
    label: str,
    *,
    stats: Mapping[str, float],
    group_stats: Mapping[str, Mapping[str, float]],
    label_to_stat: Mapping[str, str],
) -> tuple[str | None, float | None, str]:
    label_base = _semantic_trace_label_base(label)
    label_key = label_base.casefold()
    stat_label = label_to_stat.get(label_key)
    if stat_label is not None:
        return stat_label, stats.get(stat_label), ""

    for group_label, values in group_stats.items():
        group_prefix = f"{group_label} "
        group_key = str(group_label).strip().casefold()
        for raw_label, canonical_label in label_to_stat.items():
            candidate_keys = {
                f"{group_key} {raw_label}",
                f"{group_key} {raw_label} marker",
            }
            if label_key in candidate_keys:
                return canonical_label, values.get(canonical_label), group_prefix
    return None, None, ""


def _is_semantic_stat_trace_label(label: str, label_to_stat: Mapping[str, str]) -> bool:
    label_key = _semantic_trace_label_base(label).casefold()
    if label_key in label_to_stat:
        return True
    return any(
        label_key.endswith(f" {raw_label}") or label_key.endswith(f" {raw_label} marker")
        for raw_label in label_to_stat
    )


def _semantic_trace_label_base(label: str) -> str:
    return str(label or "").split("=", 1)[0].strip()


def _legend_only_reference_trace(*, name: str, value: float | None, color: str, dash: str) -> dict[str, Any]:
    numeric = 0.0 if value is None else float(value)
    return {
        "type": "scatter",
        "mode": "lines",
        "name": name,
        "x": [0, 1],
        "y": [numeric, numeric],
        "line": {"color": color, "width": 2, "dash": dash},
        "hoverinfo": "skip",
        "visible": "legendonly",
        "showlegend": True,
    }


def _ensure_group_histogram_mean_annotations(spec: Mapping[str, Any], payload: Mapping[str, Any]) -> None:
    if str(payload.get("type") or "").strip().casefold() != "histogram":
        return
    groups = _histogram_payload_groups(payload)
    if len(groups) <= 1:
        return
    layout = spec.get("layout")
    if not isinstance(layout, dict):
        return
    annotations = layout.setdefault("annotations", [])
    if not isinstance(annotations, list):
        annotations = []
        layout["annotations"] = annotations
    shapes = layout.setdefault("shapes", [])
    if not isinstance(shapes, list):
        shapes = []
        layout["shapes"] = shapes
    existing_by_text = {
        str(annotation.get("text") or ""): annotation
        for annotation in annotations
        if isinstance(annotation, dict)
    }
    mean_annotations: list[tuple[dict[str, Any], float]] = []
    for index, (label, values) in enumerate(groups):
        finite_values = values[np.isfinite(values)]
        if finite_values.size == 0:
            continue
        mean_value = float(np.mean(finite_values))
        color = _ensure_histogram_group_trace_color(spec, str(label), index)
        text = f"{label} mean={_format_metrology_legend_value('Mean', mean_value)}"
        shapes.append(
            {
                "type": "line",
                "xref": "x",
                "yref": "paper",
                "x0": mean_value,
                "x1": mean_value,
                "y0": 0,
                "y1": 1,
                "line": {"color": color, "width": 2, "dash": "dashdot"},
            }
        )
        annotation = existing_by_text.get(text)
        if annotation is None:
            annotation = {
                "xref": "x",
                "yref": "paper",
                "x": mean_value,
                "y": 1.08,
                "text": text,
                "showarrow": False,
                "font": {"size": 11, "color": color},
                "bgcolor": "#ffffff",
                "bordercolor": "#cbd5e1",
                "borderwidth": 1,
                "borderpad": 3,
                "opacity": 1.0,
            }
            annotations.append(annotation)
            existing_by_text[text] = annotation
        else:
            annotation.update(
                {
                    "xref": "x",
                    "yref": "paper",
                    "x": mean_value,
                    "text": text,
                    "showarrow": False,
                    "font": {"size": 11, "color": color},
                    "bgcolor": "#ffffff",
                    "bordercolor": "#cbd5e1",
                    "borderwidth": max(int(annotation.get("borderwidth") or 0), 1),
                    "borderpad": max(int(annotation.get("borderpad") or 0), 3),
                    "opacity": 1.0,
                }
            )
        mean_annotations.append((annotation, mean_value))
    all_values = np.concatenate([values for _label, values in groups]) if groups else np.asarray([])
    all_values = all_values[np.isfinite(all_values)]
    bin_width = None
    if all_values.size:
        bin_count = _resolved_bin_count(all_values, bin_count=_payload_int(payload.get("bin_count")))
        data_min = float(np.min(all_values))
        data_max = float(np.max(all_values))
        if math.isclose(data_min, data_max, rel_tol=1e-9, abs_tol=1e-9):
            padding = max(abs(data_min) * 0.01, 0.5)
            data_min -= padding
            data_max += padding
        bin_width = (data_max - data_min) / max(bin_count, 1)
    _stagger_histogram_mean_annotations(layout, mean_annotations, bin_width=bin_width)


def _ensure_histogram_group_trace_color(spec: Mapping[str, Any], label: str, index: int) -> str:
    fallback_color = _PLOTLY_GROUP_COLORWAY[index % len(_PLOTLY_GROUP_COLORWAY)]
    for trace in spec.get("data") or []:
        if not isinstance(trace, dict):
            continue
        if str(trace.get("type") or "").strip().casefold() not in {"bar", "histogram"}:
            continue
        if str(trace.get("name") or "").strip() != label:
            continue
        marker = trace.get("marker") if isinstance(trace.get("marker"), dict) else {}
        color = marker.get("color")
        if isinstance(color, list):
            color = color[0] if color else None
        if color:
            return str(color)
        line = trace.get("line") if isinstance(trace.get("line"), Mapping) else {}
        line_color = line.get("color")
        if line_color:
            return str(line_color)
        marker = trace.setdefault("marker", {})
        if isinstance(marker, dict):
            marker["color"] = fallback_color
        return fallback_color
    trace_colors = _histogram_trace_colors(spec)
    return trace_colors[index] if index < len(trace_colors) else fallback_color


def _histogram_trace_colors_by_name(spec: Mapping[str, Any]) -> dict[str, str]:
    colors: dict[str, str] = {}
    for trace in spec.get("data") or []:
        if not isinstance(trace, Mapping):
            continue
        marker = trace.get("marker") if isinstance(trace.get("marker"), Mapping) else {}
        color = marker.get("color")
        if isinstance(color, list):
            color = color[0] if color else None
        if color is None:
            line = trace.get("line") if isinstance(trace.get("line"), Mapping) else {}
            color = line.get("color")
        name = str(trace.get("name") or "").strip()
        if name and color:
            colors[name] = str(color)
    return colors


def _histogram_trace_colors(spec: Mapping[str, Any]) -> list[str]:
    colors: list[str] = []
    for trace in spec.get("data") or []:
        if not isinstance(trace, Mapping):
            continue
        if str(trace.get("type") or "").strip().casefold() not in {"bar", "histogram"}:
            continue
        marker = trace.get("marker") if isinstance(trace.get("marker"), Mapping) else {}
        color = marker.get("color")
        if isinstance(color, list):
            color = color[0] if color else None
        if color is None:
            line = trace.get("line") if isinstance(trace.get("line"), Mapping) else {}
            color = line.get("color")
        if color:
            colors.append(str(color))
    return colors


def _stagger_histogram_mean_annotations(
    layout: dict[str, Any],
    mean_annotations: list[tuple[dict[str, Any], float]],
    *,
    bin_width: float | None = None,
) -> None:
    if len(mean_annotations) <= 1:
        return
    sorted_annotations = sorted(
        mean_annotations,
        key=lambda item: (item[1], str(item[0].get("text") or "")),
    )
    x_values = [x_value for _annotation, x_value in sorted_annotations]
    span = max(x_values) - min(x_values)
    threshold = 0.0
    if bin_width is not None and math.isfinite(bin_width) and bin_width > 0:
        threshold = max(threshold, bin_width * 0.75)
    if span > 0:
        threshold = max(threshold, span * 0.03)
    threshold = max(threshold, 1e-9)

    clusters: list[list[tuple[dict[str, Any], float]]] = []
    for item in sorted_annotations:
        if not clusters or abs(item[1] - clusters[-1][-1][1]) > threshold:
            clusters.append([item])
        else:
            clusters[-1].append(item)

    max_y = 1.08
    for cluster in clusters:
        if len(cluster) <= 1:
            cluster[0][0]["y"] = 1.08
            continue
        for offset, (annotation, _x_value) in enumerate(cluster):
            y_value = 1.08 + (offset * 0.08)
            annotation["y"] = y_value
            max_y = max(max_y, y_value)

    if max_y > 1.08:
        margin = layout.setdefault("margin", {})
        if isinstance(margin, dict):
            extra_steps = int(round((max_y - 1.08) / 0.08))
            margin["t"] = max(int(margin.get("t") or 0), 78 + extra_steps * 22)


def _stagger_histogram_x_annotations(spec: Mapping[str, Any]) -> None:
    layout = spec.get("layout")
    if not isinstance(layout, dict):
        return
    raw_annotations = layout.get("annotations")
    if not isinstance(raw_annotations, list):
        return
    annotations: list[tuple[dict[str, Any], float]] = []
    for annotation in raw_annotations:
        if not isinstance(annotation, dict):
            continue
        if str(annotation.get("xref") or "").strip().casefold() != "x":
            continue
        if str(annotation.get("yref") or "").strip().casefold() != "paper":
            continue
        x_value = _optional_float(annotation.get("x"))
        if x_value is None:
            continue
        annotations.append((annotation, x_value))
    if not annotations:
        return
    data = spec.get("data")
    bin_width = _representative_histogram_bin_width(data) if isinstance(data, list) else None
    _stagger_histogram_mean_annotations(layout, annotations, bin_width=bin_width)


def _is_histogram_plotly_spec(spec: Mapping[str, Any]) -> bool:
    metadata = spec.get("metadata") if isinstance(spec.get("metadata"), Mapping) else {}
    if str(metadata.get("kind") or "").strip().casefold() == "histogram":
        return True
    if str(metadata.get("histogram_y_mode") or "").strip():
        return True
    for trace in spec.get("data") or []:
        if isinstance(trace, Mapping) and str(trace.get("type") or "").strip().casefold() == "histogram":
            return True
    return False


def _normalize_histogram_plotly_axes(spec: Mapping[str, Any]) -> None:
    layout = spec.get("layout")
    if not isinstance(layout, dict):
        return
    yaxis = layout.setdefault("yaxis", {})
    if isinstance(yaxis, dict):
        yaxis["title"] = {"text": "Frequency (%)"}
        yaxis["tickformat"] = ".0%"
        for key in ("range", "tickmode", "tickvals", "ticktext", "nticks"):
            yaxis.pop(key, None)
    xaxis = layout.setdefault("xaxis", {})
    if isinstance(xaxis, dict):
        xaxis["tickformat"] = ".4~g"
        xaxis["automargin"] = True
        title = xaxis.get("title")
        if isinstance(title, dict):
            title["standoff"] = max(int(title.get("standoff") or 0), 20)
        elif title:
            xaxis["title"] = {"text": str(title), "standoff": 20}
    margin = layout.setdefault("margin", {})
    if isinstance(margin, dict):
        margin["b"] = max(int(margin.get("b") or 0), 92)


def _normalize_grouped_histogram_bins(spec: Mapping[str, Any]) -> None:
    for trace in spec.get("data") or []:
        if not isinstance(trace, dict) or str(trace.get("type") or "").casefold() != "bar":
            continue
        x_values = trace.get("x")
        if not isinstance(x_values, list) or not x_values:
            continue
        parsed = [_parse_bin_range_label(value) for value in x_values]
        if not all(item is not None for item in parsed):
            continue
        ranges = [(float(start), float(end), str(label)) for start, end, label in parsed if start is not None and end is not None]
        trace["x"] = [(start + end) / 2.0 for start, end, _label in ranges]
        trace["width"] = [max(end - start, 0.0) for start, end, _label in ranges]
        old_customdata = trace.get("customdata") if isinstance(trace.get("customdata"), list) else []
        customdata = []
        for index, (start, end, label) in enumerate(ranges):
            count = None
            if index < len(old_customdata) and isinstance(old_customdata[index], list) and old_customdata[index]:
                count = old_customdata[index][0]
            customdata.append([start, end, count, label])
        trace["customdata"] = customdata
        trace["hovertemplate"] = (
            "bin=%{customdata[0]:.4g}..%{customdata[1]:.4g}<br>"
            "frequency=%{y:.2%}<br>"
            "count=%{customdata[2]}<extra></extra>"
        )


def _normalize_histogram_bar_trace_y_values(spec: Mapping[str, Any]) -> None:
    for trace in spec.get("data") or []:
        if not isinstance(trace, dict):
            continue
        trace_type = str(trace.get("type") or "").strip().casefold()
        if trace_type == "histogram":
            trace["histnorm"] = "probability"
        if trace_type not in {"bar", "histogram"}:
            continue
        y_values = _finite_trace_values(trace.get("y"))
        if not y_values:
            continue
        total = float(sum(value for value in y_values if value > 0.0))
        max_value = float(max(y_values))
        if total > 1.0 + 1e-9 or max_value > 1.0 + 1e-9:
            denominator = total if total > 0.0 else max_value
            normalized = [float(max(value, 0.0) / denominator) for value in y_values]
        else:
            normalized = [float(max(value, 0.0)) for value in y_values]
        trace["y"] = [float(min(value, 1.0)) for value in normalized]
        trace["hovertemplate"] = str(
            trace.get("hovertemplate")
            or "bin=%{x}<br>frequency=%{y:.2%}<extra></extra>"
        )


_GENERIC_OVERLAY_NAME_PATTERN = re.compile(r"^(?:curve\s+)?overlay\s*\d*$", re.IGNORECASE)


def _normalize_histogram_overlay_traces(spec: Mapping[str, Any]) -> None:
    data = spec.get("data")
    if not isinstance(data, list):
        return
    bin_width = _representative_histogram_bin_width(data)
    overlay_index = 0
    for trace in data:
        if not isinstance(trace, dict) or not _is_histogram_overlay_trace(trace):
            continue
        overlay_index += 1
        trace["name"] = _histogram_overlay_trace_name(trace, overlay_index)
        if bin_width is not None:
            _scale_overlay_trace_to_probability(trace, bin_width)


def _representative_histogram_bin_width(data: list[Any]) -> float | None:
    widths: list[float] = []
    for trace in data:
        if not isinstance(trace, Mapping):
            continue
        trace_type = str(trace.get("type") or "").strip().casefold()
        if trace_type == "bar":
            raw_width = trace.get("width")
            if isinstance(raw_width, list):
                widths.extend(_finite_positive_values(raw_width))
            else:
                width = _optional_float(raw_width)
                if width is not None and width > 0:
                    widths.append(width)
        elif trace_type == "histogram":
            xbins = trace.get("xbins") if isinstance(trace.get("xbins"), Mapping) else {}
            width = _optional_float(xbins.get("size"))
            if width is not None and width > 0:
                widths.append(width)
    if not widths:
        return None
    return float(np.median(np.asarray(widths, dtype=float)))


def _finite_positive_values(values: Any) -> list[float]:
    output: list[float] = []
    if not isinstance(values, list):
        return output
    for value in values:
        numeric = _optional_float(value)
        if numeric is not None and numeric > 0:
            output.append(numeric)
    return output


def _is_histogram_overlay_trace(trace: Mapping[str, Any]) -> bool:
    if str(trace.get("type") or "").strip().casefold() != "scatter":
        return False
    axis, value = _constant_line_axis_and_value(trace)
    if axis and value is not None:
        return False
    name = str(trace.get("name") or "").strip()
    return bool(_GENERIC_OVERLAY_NAME_PATTERN.match(name))


def _histogram_overlay_trace_name(trace: Mapping[str, Any], overlay_index: int) -> str:
    line = trace.get("line") if isinstance(trace.get("line"), Mapping) else {}
    dash = str(line.get("dash") or trace.get("dash") or "").strip().casefold()
    fill = str(trace.get("fill") or "").strip().casefold()
    if fill and fill != "none":
        return "Tail shading"
    if dash and dash not in {"solid", "none"}:
        return "KDE reference"
    return "Selected model curve" if overlay_index == 1 else f"Model curve {overlay_index}"


def _scale_overlay_trace_to_probability(trace: dict[str, Any], bin_width: float) -> None:
    y_values = _finite_trace_values(trace.get("y"))
    if not y_values:
        return
    y_array = np.asarray(y_values, dtype=float)
    if y_array.size == 0:
        return
    scaled = y_array * float(bin_width)
    max_scaled = float(np.nanmax(scaled)) if scaled.size else 0.0
    if max_scaled > 1.0:
        scaled = scaled / max_scaled
    trace["y"] = [float(min(max(value, 0.0), 1.0)) for value in scaled.tolist()]
    trace["hovertemplate"] = str(trace.get("hovertemplate") or "%{x}<br>%{y:.2%}<extra></extra>")


def _format_group_statistics_trace_name(label: str, values: list[float]) -> str:
    if not values:
        return str(label)
    return f"{label} (n={len(values)})"


def _format_plotly_stat_value(value: float | None) -> str:
    if value is None or not math.isfinite(float(value)):
        return ""
    number = float(value)
    magnitude = abs(number)
    if magnitude >= 10_000 or (0.0 < magnitude < 0.001):
        return f"{number:.4g}"
    rounded = Decimal(str(round(number, 12))).quantize(Decimal("0.001"), rounding=ROUND_HALF_UP)
    text = f"{rounded:f}".rstrip("0").rstrip(".")
    return "0" if text in {"", "-0"} else text


def _format_metrology_legend_value(label: str, value: float | None) -> str:
    if value is None or not math.isfinite(float(value)):
        return ""
    precision = 4 if label.strip().casefold() == "mean" else 3
    quantizer = Decimal("1").scaleb(-precision)
    rounded = Decimal(str(round(float(value), 12))).quantize(quantizer, rounding=ROUND_HALF_UP)
    return f"{rounded:.{precision}f}"


def _dedupe_visible_stat_legend_items(spec: Mapping[str, Any]) -> None:
    data = spec.get("data")
    if not isinstance(data, list):
        return
    seen: set[str] = set()
    for trace in data:
        if not isinstance(trace, dict):
            continue
        if trace.get("showlegend", True) is False:
            continue
        name = str(trace.get("name") or "").strip()
        if not _is_canonical_stat_legend_item_name(name):
            continue
        if name in seen:
            trace["showlegend"] = False
            continue
        seen.add(name)


def _is_canonical_stat_legend_item_name(name: str) -> bool:
    left, separator, value = str(name or "").partition("=")
    if not separator or not value.strip():
        return False
    label = left.strip().split(" ")[-1].casefold()
    return label in _REFERENCE_LEGEND_LABELS


def _percentile_sorted(values: list[float], fraction: float) -> float:
    if not values:
        return float("nan")
    if len(values) == 1:
        return float(values[0])
    position = (len(values) - 1) * fraction
    lower = int(math.floor(position))
    upper = int(math.ceil(position))
    if lower == upper:
        return float(values[lower])
    weight = position - lower
    return float(values[lower] * (1.0 - weight) + values[upper] * weight)


def _parse_bin_range_label(value: Any) -> tuple[float, float, str] | None:
    text = str(value or "").strip()
    match = _BIN_RANGE_PATTERN.match(text)
    if match is None:
        return None
    try:
        start = float(match.group(1))
        end = float(match.group(2))
    except ValueError:
        return None
    if not (math.isfinite(start) and math.isfinite(end) and end > start):
        return None
    return start, end, text


def _normalize_reference_trace_names_and_annotations(spec: Mapping[str, Any]) -> None:
    layout = spec.get("layout")
    if not isinstance(layout, dict):
        return
    is_histogram = _is_histogram_plotly_spec(spec)
    existing_annotations = layout.get("annotations")
    annotations_valid = isinstance(existing_annotations, list)
    annotations = existing_annotations if annotations_valid else []
    existing_text = {
        str(annotation.get("text") or "")
        for annotation in annotations
        if isinstance(annotation, Mapping)
    }
    for trace in spec.get("data") or []:
        if not isinstance(trace, dict):
            continue
        label = str(trace.get("name") or "").strip()
        label_key = label.casefold()
        if label_key not in _REFERENCE_LEGEND_LABELS:
            continue
        axis, value = _constant_line_axis_and_value(trace)
        if value is None:
            continue
        display_label = _REFERENCE_LEGEND_DISPLAY_LABELS.get(label_key, label)
        display = f"{display_label}={_format_metrology_legend_value(display_label, value)}"
        trace["name"] = display
        if is_histogram and axis == "x":
            _promote_histogram_reference_trace_to_shape(layout, trace, value)
        if display in existing_text:
            continue
        annotation = _reference_annotation(axis=axis, value=value, text=display, color=_trace_line_color(trace))
        if annotation is not None:
            if not annotations_valid:
                layout["annotations"] = annotations
                annotations_valid = True
            annotations.append(annotation)
            existing_text.add(display)


def _promote_histogram_reference_trace_to_shape(
    layout: dict[str, Any],
    trace: dict[str, Any],
    value: float,
) -> None:
    line = trace.get("line") if isinstance(trace.get("line"), Mapping) else {}
    color = str(line.get("color") or "#111827")
    width = _optional_float(line.get("width")) or 2
    dash = str(line.get("dash") or "dash")
    shapes = layout.setdefault("shapes", [])
    if not isinstance(shapes, list):
        shapes = []
        layout["shapes"] = shapes
    if not _has_histogram_reference_shape(shapes, value):
        shapes.append(
            {
                "type": "line",
                "xref": "x",
                "yref": "paper",
                "x0": value,
                "x1": value,
                "y0": 0,
                "y1": 1,
                "line": {"color": color, "width": width, "dash": dash},
            }
        )
    trace["type"] = "scatter"
    trace["mode"] = "lines"
    trace["x"] = [value, value]
    trace["y"] = [0.0, 0.0]
    trace["visible"] = "legendonly"
    trace["showlegend"] = True
    trace["hoverinfo"] = "skip"


def _has_histogram_reference_shape(shapes: list[Any], value: float) -> bool:
    for shape in shapes:
        if not isinstance(shape, Mapping):
            continue
        if str(shape.get("type") or "").strip().casefold() != "line":
            continue
        if str(shape.get("xref") or "").strip().casefold() != "x":
            continue
        if str(shape.get("yref") or "").strip().casefold() != "paper":
            continue
        x0 = _optional_float(shape.get("x0"))
        x1 = _optional_float(shape.get("x1"))
        if x0 is None or x1 is None:
            continue
        if math.isclose(x0, value, rel_tol=1e-9, abs_tol=1e-12) and math.isclose(
            x1,
            value,
            rel_tol=1e-9,
            abs_tol=1e-12,
        ):
            return True
    return False


def _constant_line_axis_and_value(trace: Mapping[str, Any]) -> tuple[str, float | None]:
    x_values = _finite_trace_values(trace.get("x"))
    y_values = _finite_trace_values(trace.get("y"))
    if len(x_values) >= 2 and all(math.isclose(value, x_values[0]) for value in x_values):
        return "x", x_values[0]
    if len(y_values) >= 2 and all(math.isclose(value, y_values[0]) for value in y_values):
        return "y", y_values[0]
    return "", None


def _finite_trace_values(values: Any) -> list[float]:
    if isinstance(values, np.ndarray):
        iterable = values.tolist()
    elif isinstance(values, (list, tuple)):
        iterable = values
    else:
        return []
    output: list[float] = []
    for value in iterable:
        try:
            number = float(value)
        except (TypeError, ValueError):
            continue
        if math.isfinite(number):
            output.append(number)
    return output


def _reference_annotation(*, axis: str, value: float, text: str, color: str) -> dict[str, Any] | None:
    annotation: dict[str, Any] = {
        "text": text,
        "showarrow": False,
        "font": {"size": 11, "color": color},
        "bgcolor": "#ffffff",
        "bordercolor": "#cbd5e1",
        "borderwidth": 1,
        "borderpad": 3,
        "opacity": 1.0,
    }
    if axis == "x":
        annotation.update({"xref": "x", "yref": "paper", "x": value, "y": 1.04, "yanchor": "bottom"})
        return annotation
    if axis == "y":
        annotation.update(
            {
                "xref": "paper",
                "yref": "y",
                "x": 1.0,
                "y": value,
                "xanchor": "right",
                "yanchor": "top",
                "yshift": -4,
            }
        )
        return annotation
    return None


def _trace_line_color(trace: Mapping[str, Any]) -> str:
    line = trace.get("line") if isinstance(trace.get("line"), Mapping) else {}
    return str(line.get("color") or "#111827")


def _format_plotly_value(value: float) -> str:
    magnitude = abs(value)
    if magnitude >= 10_000 or (0.0 < magnitude < 0.001):
        return f"{value:.4g}"
    text = f"{value:.6f}".rstrip("0").rstrip(".")
    return "0" if text in {"", "-0"} else text


def _normalize_plotly_annotation_boxes(spec: Mapping[str, Any]) -> None:
    layout = spec.get("layout")
    if not isinstance(layout, dict):
        return
    annotations = layout.get("annotations")
    if not isinstance(annotations, list):
        return
    for annotation in annotations:
        if not isinstance(annotation, dict):
            continue
        annotation["bgcolor"] = "#ffffff"
        annotation["bordercolor"] = annotation.get("bordercolor") or "#cbd5e1"
        annotation["borderwidth"] = max(int(annotation.get("borderwidth") or 0), 1)
        annotation["borderpad"] = max(int(annotation.get("borderpad") or 0), 3)
        annotation["opacity"] = 1.0


__all__ = [
    "ChartArtifactPngResult",
    "HistogramRenderResult",
    "HistogramStatsTable",
    "PLOTSTATS_EXPORT_CHARTS_ENV_VAR",
    "build_chart_artifact",
    "build_dashboard_plotly_spec",
    "build_histogram_stats_table",
    "build_plotstats_dashboard_spec",
    "metroliza_dashboard_plotstats_theme",
    "normalize_distribution_stat_legend",
    "plotstats_export_charts_enabled",
    "render_chart_artifact_png",
    "render_histogram_png",
]
