"""Offline Plotly dashboard writer for cached production analytics."""

from __future__ import annotations

import base64
from datetime import datetime, timezone
import html
from io import BytesIO
import json
from pathlib import Path
import shutil
from typing import Any

import numpy as np
import pandas as pd

from modules.export_summary_utils import resolve_histogram_bin_count
from modules.hexafe_plotstats_adapter import build_histogram_stats_table, render_histogram_png
from modules.industrial_analytics_service import (
    ProductionAggregationResult,
    ProductionAnalyticsDiagnostic,
    ProductionGroupstatsResult,
)
from modules.industrial_analytics_state import (
    ProductionAggregationState,
    ProductionChartSelection,
    ProductionMetricSelection,
    ReferenceCohortState,
)
from modules.summary_plot_palette import SUMMARY_PLOT_PALETTE


DASHBOARD_SCHEMA = "metroliza.production_analytics_dashboard.v1"
PLOTLY_ASSET_NAME = "plotly-2.27.0.min.js"
PLOTLY_ASSET_SOURCE = Path(__file__).resolve().parent / "html_dashboard_assets" / PLOTLY_ASSET_NAME
PLOTLY_MODEBAR_REMOVE = (
    "select2d",
    "lasso2d",
    "autoScale2d",
    "toggleSpikelines",
    "hoverClosestCartesian",
    "hoverCompareCartesian",
)
PLOT_COLORWAY = (
    SUMMARY_PLOT_PALETTE["distribution_foreground"],
    "#D55E00",
    "#009E73",
    SUMMARY_PLOT_PALETTE["outlier"],
    SUMMARY_PLOT_PALETTE["central_tendency"],
    SUMMARY_PLOT_PALETTE["distribution_base"],
)


def build_production_dashboard_manifest(
    *,
    frame: pd.DataFrame,
    metric_selection: tuple[ProductionMetricSelection, ...],
    aggregation_state: ProductionAggregationState | None = None,
    aggregation_result: ProductionAggregationResult | None = None,
    groupstats_result: ProductionGroupstatsResult | None = None,
    chart_selection: ProductionChartSelection | None = None,
    cohort_state: ReferenceCohortState | None = None,
    diagnostics: tuple[ProductionAnalyticsDiagnostic, ...] = (),
    dashboard_title: str = "Production Analytics",
    dashboard_subtitle: str = "Cached production data dashboard generated by Metroliza.",
) -> dict[str, Any]:
    """Build a renderer-neutral manifest for the production analytics dashboard."""

    aggregation = aggregation_state or ProductionAggregationState()
    charts = chart_selection or ProductionChartSelection()
    cohort = cohort_state or ReferenceCohortState()
    aggregate_frame = (
        aggregation_result.dataframe
        if aggregation_result is not None and not aggregation_result.dataframe.empty
        else pd.DataFrame()
    )

    chart_specs: list[dict[str, Any]] = []
    for metric in metric_selection:
        if metric.field_name not in frame.columns:
            continue
        metric_frame = frame[frame[metric.field_name].notna()].copy()
        if metric_frame.empty:
            continue
        if charts.time_series:
            group_columns = _chart_group_columns(metric_frame, aggregation)
            specs = _build_time_series_charts(
                metric,
                raw_frame=metric_frame,
                aggregate_frame=aggregate_frame,
                aggregation=aggregation,
                group_columns=group_columns,
            )
            chart_specs.extend(spec for spec in specs if spec)
        if charts.histogram:
            spec = _build_histogram_chart(
                metric,
                metric_frame,
                group_columns=_chart_group_columns(metric_frame, aggregation),
            )
            if spec:
                chart_specs.append(spec)
        if charts.violin:
            spec = _build_distribution_chart(
                metric,
                metric_frame,
                chart_type="violin",
                group_columns=_chart_group_columns(metric_frame, aggregation),
            )
            if spec:
                chart_specs.append(spec)
        if charts.box:
            spec = _build_distribution_chart(
                metric,
                metric_frame,
                chart_type="box",
                group_columns=_chart_group_columns(metric_frame, aggregation),
            )
            if spec:
                chart_specs.append(spec)

    summary = {
        "generated_at": datetime.now(timezone.utc).replace(microsecond=0).isoformat(),
        "source_rows": int(len(frame.index)),
        "aggregate_rows": (
            int(aggregation_result.output_row_count)
            if aggregation_result is not None
            else 0
        ),
        "metric_count": len(metric_selection),
        "chart_count": len(chart_specs),
        "time_bucket": aggregation.time_bucket,
        "aggregation_methods": list(aggregation.aggregation_methods),
        "group_fields": list(aggregation.group_fields),
        "reference_cohort_count": len(cohort.references),
        "reference_cohort_mode": cohort.mode,
        "dashboard_title": dashboard_title,
        "dashboard_subtitle": dashboard_subtitle,
        "groupstats_metric_count": (
            groupstats_result.analyzed_metric_count
            if groupstats_result is not None
            else 0
        ),
    }
    return {
        "schema": DASHBOARD_SCHEMA,
        "summary": summary,
        "metrics": [
            {
                "field_name": metric.field_name,
                "display_label": metric.display_label,
                "source_kind": metric.source_kind,
            }
            for metric in metric_selection
        ],
        "charts": chart_specs,
        "groupstats": _groupstats_payload(groupstats_result),
        "diagnostics": [_diagnostic_payload(diagnostic) for diagnostic in diagnostics],
    }


def write_production_dashboard(
    manifest: dict[str, Any],
    output_path: str | Path,
    *,
    assets_dir: str | Path | None = None,
) -> dict[str, Any]:
    """Write an offline production analytics dashboard and local Plotly asset."""

    destination = Path(output_path)
    if destination.suffix.lower() != ".html":
        destination = destination.with_suffix(".html")
    destination.parent.mkdir(parents=True, exist_ok=True)
    asset_directory = (
        Path(assets_dir)
        if assets_dir is not None
        else destination.with_name(f"{destination.stem}_assets")
    )
    asset_directory.mkdir(parents=True, exist_ok=True)
    plotly_target = asset_directory / PLOTLY_ASSET_NAME
    if not plotly_target.exists():
        shutil.copy2(PLOTLY_ASSET_SOURCE, plotly_target)

    html_text = _render_dashboard_html(manifest, asset_directory_name=asset_directory.name)
    destination.write_text(html_text, encoding="utf-8")
    return {
        "html_dashboard_path": str(destination),
        "html_dashboard_assets_path": str(asset_directory),
        "html_dashboard_chart_count": len(manifest.get("charts") or []),
    }


def _build_time_series_charts(
    metric: ProductionMetricSelection,
    *,
    raw_frame: pd.DataFrame,
    aggregate_frame: pd.DataFrame,
    aggregation: ProductionAggregationState,
    group_columns: list[str] | None = None,
) -> list[dict[str, Any]]:
    method = aggregation.aggregation_methods[0] if aggregation.aggregation_methods else "mean"
    aggregate_metric = f"{metric.field_name}__{method}"
    group_columns = group_columns or []
    charts: list[dict[str, Any]] = []
    if (
        aggregation.is_aggregated
        and not aggregate_frame.empty
        and "time_bucket_start" in aggregate_frame.columns
        and aggregate_metric in aggregate_frame.columns
        and all(column in aggregate_frame.columns for column in group_columns)
    ):
        traces = _time_series_traces(
            aggregate_frame,
            x_column="time_bucket_start",
            y_column=aggregate_metric,
            group_columns=group_columns,
            default_name=f"{metric.display_label} ({method})",
            time_bucket=aggregation.time_bucket,
        )
        if traces:
            charts.append(
                _chart_payload(
                    chart_id=f"time-series-{metric.field_name}-aggregated",
                    title=f"{metric.display_label} over time ({method})",
                    chart_type="time_series",
                    data=traces,
                    layout={
                        "xaxis": {"title": _bucket_axis_title(aggregation.time_bucket)},
                        "yaxis": {"title": f"{metric.display_label} ({method})"},
                        "hovermode": "x unified",
                    },
                )
            )
            overlay_traces = _time_series_traces(
                raw_frame,
                x_column="process_datetime",
                y_column=metric.field_name,
                group_columns=group_columns,
                default_name=metric.display_label,
            )
            overlay_traces.extend(
                _time_series_traces(
                    aggregate_frame,
                    x_column="time_bucket_start",
                    y_column=aggregate_metric,
                    group_columns=group_columns,
                    default_name=f"{metric.display_label} aggregate",
                    time_bucket=aggregation.time_bucket,
                    aggregate_marker=True,
                )
            )
            if overlay_traces:
                charts.append(
                    _chart_payload(
                        chart_id=f"time-series-{metric.field_name}-raw-aggregate",
                        title=f"{metric.display_label} raw values with {method} markers",
                        chart_type="time_series_raw_aggregate",
                        data=overlay_traces,
                        layout={
                            "xaxis": {"title": "Process time"},
                            "yaxis": {"title": metric.display_label},
                            "hovermode": "closest",
                        },
                    )
                )
        return charts

    traces = _time_series_traces(
        raw_frame,
        x_column="process_datetime",
        y_column=metric.field_name,
        group_columns=group_columns,
        default_name=metric.display_label,
    )
    if not traces:
        return []
    return [
        _chart_payload(
            chart_id=f"time-series-{metric.field_name}",
            title=f"{metric.display_label} over time",
            chart_type="time_series",
            data=traces,
            layout={
                "xaxis": {"title": "Process time"},
                "yaxis": {"title": metric.display_label},
                "hovermode": "x unified",
            },
        )
    ]


def _build_histogram_chart(
    metric: ProductionMetricSelection,
    frame: pd.DataFrame,
    *,
    group_columns: list[str] | None = None,
) -> dict[str, Any]:
    traces = []
    groups = _plot_groups(frame, group_columns=group_columns)
    all_values = _numeric_values(frame[metric.field_name])
    bins = _histogram_bins(all_values)
    normalize_groups = len(groups) > 1
    for index, (label, group) in enumerate(groups, start=0):
        values = _numeric_values(group[metric.field_name])
        if not values:
            continue
        trace = {
            "type": "histogram",
            "name": label,
            "x": values,
            "xbins": bins,
            "bingroup": f"hist-{metric.field_name}",
            "opacity": 0.58 if normalize_groups else 0.86,
            "marker": {
                "color": _plot_color(index, label),
                "line": {"color": "rgba(255,255,255,0.72)", "width": 0.8},
            },
            "hovertemplate": f"{html.escape(label)}<br>{metric.display_label}=%{{x}}<br>Count=%{{y}}<extra></extra>",
        }
        if normalize_groups:
            trace["histnorm"] = "probability"
            trace["hovertemplate"] = (
                f"{html.escape(label)}<br>{metric.display_label}=%{{x}}"
                "<br>Share=%{y:.1%}<extra></extra>"
            )
        traces.append(trace)
    if not traces:
        return {}
    chart = _chart_payload(
        chart_id=f"histogram-{metric.field_name}",
        title=f"{metric.display_label} distribution",
        chart_type="histogram",
        data=traces,
        layout={
            "barmode": "overlay",
            "bargap": 0.04,
            "xaxis": {"title": metric.display_label},
            "yaxis": (
                {"title": "Share of group", "tickformat": ".0%"}
                if normalize_groups
                else {"title": "Count"}
            ),
        },
    )
    stats_tables = _histogram_stats_tables(metric, groups)
    if stats_tables:
        chart["stats_tables"] = stats_tables
    image = _render_distribution_image(metric, frame, chart_type="histogram", groups=groups)
    if image:
        chart["image"] = image
    return chart


def _build_distribution_chart(
    metric: ProductionMetricSelection,
    frame: pd.DataFrame,
    *,
    chart_type: str,
    group_columns: list[str] | None = None,
) -> dict[str, Any]:
    traces = []
    groups = _plot_groups(frame, group_columns=group_columns)
    for index, (label, group) in enumerate(groups, start=0):
        values = _numeric_values(group[metric.field_name])
        if not values:
            continue
        trace_type = "box" if chart_type == "box" else "violin"
        trace = {
            "type": trace_type,
            "name": label,
            "y": values,
            "marker": {"color": _plot_color(index, label)},
            "hovertemplate": f"{html.escape(label)}<br>{metric.display_label}=%{{y}}<extra></extra>",
        }
        if trace_type == "violin":
            trace.update({"box": {"visible": True}, "meanline": {"visible": True}, "points": False})
        else:
            trace.update({"boxmean": True, "boxpoints": False})
        traces.append(trace)
    if not traces:
        return {}
    chart = _chart_payload(
        chart_id=f"{chart_type}-{metric.field_name}",
        title=f"{metric.display_label} {chart_type}",
        chart_type=chart_type,
        data=traces,
        layout={
            "xaxis": {"title": "Group"},
            "yaxis": {"title": metric.display_label},
        },
    )
    image = _render_distribution_image(metric, frame, chart_type=chart_type, groups=groups)
    if image:
        chart["image"] = image
    return chart


def _time_series_traces(
    frame: pd.DataFrame,
    *,
    x_column: str,
    y_column: str,
    group_columns: list[str],
    default_name: str,
    time_bucket: str | None = None,
    aggregate_marker: bool = False,
) -> list[dict[str, Any]]:
    if x_column not in frame.columns or y_column not in frame.columns:
        return []
    traces = []
    groups = _grouped_frames(frame, group_columns, default_name=default_name)
    for index, (label, group) in enumerate(groups, start=0):
        group = group.sort_values(x_column)
        y_series = pd.to_numeric(group[y_column], errors="coerce")
        valid_mask = group[x_column].notna() & y_series.notna()
        group = group.loc[valid_mask].copy()
        y_series = y_series.loc[valid_mask]
        x_values = _json_values(group[x_column], time_bucket=time_bucket)
        y_values = [float(value) for value in y_series.tolist()]
        if not x_values or not y_values:
            continue
        marker_symbol = "x" if aggregate_marker else ("diamond" if "selected" in label.casefold() else "circle")
        color = _plot_color(index, label)
        trace_name = label
        if aggregate_marker and not label.casefold().endswith("aggregate"):
            trace_name = f"{label} aggregate"
        traces.append(
            {
                "type": "scatter",
                "mode": "markers",
                "name": trace_name,
                "x": x_values,
                "y": y_values,
                "marker": {
                    "color": color,
                    "size": 11 if aggregate_marker else (9 if marker_symbol == "diamond" else 7),
                    "symbol": marker_symbol,
                    "line": (
                        {"color": "#111827", "width": 1.7}
                        if aggregate_marker
                        else {"color": color, "width": 0.5}
                    ),
                },
                "hovertemplate": f"{html.escape(label)}<br>Time=%{{x}}<br>Value=%{{y}}<extra></extra>",
            }
        )
    return traces


def _histogram_stats_tables(
    metric: ProductionMetricSelection,
    groups: list[tuple[str, pd.DataFrame]],
) -> list[dict[str, Any]]:
    tables: list[dict[str, Any]] = []
    for label, group in groups:
        if metric.field_name not in group.columns:
            continue
        table = build_histogram_stats_table(
            group[metric.field_name],
            title=label,
            backend="metroliza",
            lsl=metric.lsl,
            usl=metric.usl,
        )
        if table is not None:
            tables.append(table.as_dict())
    return tables


def _render_distribution_image(
    metric: ProductionMetricSelection,
    frame: pd.DataFrame,
    *,
    chart_type: str,
    groups: list[tuple[str, pd.DataFrame]] | None = None,
) -> dict[str, str] | None:
    groups = groups if groups is not None else _plot_groups(frame, group_columns=_preferred_group_columns(frame))
    if not groups:
        return None
    if chart_type == "histogram" and len(groups) == 1:
        values = _numeric_values(groups[0][1][metric.field_name])
        rendered = render_histogram_png(
            values,
            title=f"{metric.display_label} distribution",
            metric_label=metric.display_label,
            lsl=metric.lsl,
            usl=metric.usl,
        )
        if rendered is not None:
            return {
                "mime_type": "image/png",
                "base64": base64.b64encode(rendered.png_bytes).decode("ascii"),
                "alt": f"{metric.display_label} distribution",
                "backend": rendered.backend,
            }
    try:
        return _render_matplotlib_distribution_image(metric, groups, chart_type=chart_type)
    except Exception:
        return None


def _render_matplotlib_distribution_image(
    metric: ProductionMetricSelection,
    groups: list[tuple[str, pd.DataFrame]],
    *,
    chart_type: str,
) -> dict[str, str] | None:
    from modules.matplotlib_runtime import configure_headless_matplotlib

    configure_headless_matplotlib()
    import matplotlib.pyplot as plt

    value_groups: list[tuple[str, np.ndarray]] = []
    for label, group in groups:
        values = pd.to_numeric(group[metric.field_name], errors="coerce").dropna().to_numpy(dtype=float)
        values = values[np.isfinite(values)]
        if values.size:
            value_groups.append((label, values))
    if not value_groups:
        return None

    fig, ax = plt.subplots(figsize=(7.8, 4.2))
    try:
        labels = [label for label, _values in value_groups]
        arrays = [values for _label, values in value_groups]
        positions = np.arange(1, len(arrays) + 1)
        if chart_type == "histogram":
            combined = np.concatenate(arrays)
            bins = _histogram_bins([float(value) for value in combined.tolist()])
            bin_count = max(
                1,
                int(round((bins.get("end", 1.0) - bins.get("start", 0.0)) / bins.get("size", 1.0))),
            )
            for index, (label, values) in enumerate(value_groups):
                ax.hist(
                    values,
                    bins=bin_count,
                    alpha=0.52 if len(value_groups) > 1 else 0.82,
                    color=_plot_color(index, label),
                    edgecolor=SUMMARY_PLOT_PALETTE["distribution_foreground"],
                    label=label,
                    density=len(value_groups) > 1,
                )
            ax.set_ylabel("Density" if len(value_groups) > 1 else "Count")
        elif chart_type == "violin":
            parts = ax.violinplot(
                arrays,
                positions=positions,
                showmeans=False,
                showmedians=True,
                showextrema=True,
            )
            for index, body in enumerate(parts.get("bodies", [])):
                body.set_facecolor(_plot_color(index, labels[index]))
                body.set_edgecolor(SUMMARY_PLOT_PALETTE["distribution_foreground"])
                body.set_alpha(0.46)
            ax.set_xticks(positions)
            ax.set_xticklabels(labels, rotation=30 if max(len(label) for label in labels) > 12 else 0, ha="right")
            ax.set_ylabel(metric.display_label)
        else:
            box = ax.boxplot(
                arrays,
                positions=positions,
                patch_artist=True,
                showmeans=True,
                showfliers=True,
                medianprops={"color": SUMMARY_PLOT_PALETTE["central_tendency"], "linewidth": 1.15},
                meanprops={
                    "marker": "o",
                    "markerfacecolor": SUMMARY_PLOT_PALETTE["central_tendency"],
                    "markeredgecolor": SUMMARY_PLOT_PALETTE["central_tendency"],
                    "markersize": 4,
                },
                flierprops={
                    "marker": "o",
                    "markersize": 3,
                    "markerfacecolor": SUMMARY_PLOT_PALETTE["outlier"],
                    "markeredgecolor": SUMMARY_PLOT_PALETTE["outlier"],
                    "alpha": 0.85,
                },
            )
            for patch in box.get("boxes", []):
                patch.set_facecolor(SUMMARY_PLOT_PALETTE["distribution_base"])
                patch.set_edgecolor(SUMMARY_PLOT_PALETTE["distribution_foreground"])
                patch.set_alpha(0.45)
            ax.set_xticks(positions)
            ax.set_xticklabels(labels, rotation=30 if max(len(label) for label in labels) > 12 else 0, ha="right")
            ax.set_ylabel(metric.display_label)

        if chart_type == "histogram" and len(value_groups) > 1:
            ax.legend(loc="best", fontsize=8)
        for limit, color, label in (
            (metric.lsl, SUMMARY_PLOT_PALETTE["spec_limit"], "LSL"),
            (metric.usl, SUMMARY_PLOT_PALETTE["spec_limit"], "USL"),
        ):
            if limit is not None and chart_type in {"histogram", "violin", "box"}:
                axis_method = ax.axvline if chart_type == "histogram" else ax.axhline
                axis_method(float(limit), color=color, linestyle="--", linewidth=1.1, label=label)
        ax.set_title(f"{metric.display_label} {chart_type}", color=SUMMARY_PLOT_PALETTE["annotation_text"])
        if chart_type == "histogram":
            ax.set_xlabel(metric.display_label)
        ax.grid(True, axis="y", color=SUMMARY_PLOT_PALETTE["grid"], linewidth=0.5, alpha=0.45)
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        fig.tight_layout()
        image_data = BytesIO()
        fig.savefig(image_data, format="png", dpi=150)
        image_data.seek(0)
        return {
            "mime_type": "image/png",
            "base64": base64.b64encode(image_data.getvalue()).decode("ascii"),
            "alt": f"{metric.display_label} {chart_type}",
            "backend": "matplotlib",
        }
    finally:
        plt.close(fig)


def _chart_payload(
    *,
    chart_id: str,
    title: str,
    chart_type: str,
    data: list[dict[str, Any]],
    layout: dict[str, Any],
) -> dict[str, Any]:
    resolved_layout = {
        "title": {"text": title, "font": {"size": 18}, "y": 0.98, "yanchor": "top"},
        "font": {"family": 'Aptos, "Segoe UI", "Helvetica Neue", sans-serif', "color": "#1f2933"},
        "paper_bgcolor": "#ffffff",
        "plot_bgcolor": "#ffffff",
        "colorway": list(PLOT_COLORWAY),
        "dragmode": "zoom",
        "margin": {"l": 56, "r": 24, "t": 84, "b": 56},
        "hoverlabel": {"bgcolor": "#ffffff", "font": {"color": "#1f2933"}},
        "legend": {
            "orientation": "h",
            "yanchor": "bottom",
            "y": 1.0,
            "xanchor": "left",
            "x": 0.0,
            "bgcolor": "rgba(255,255,255,0.86)",
            "bordercolor": SUMMARY_PLOT_PALETTE["annotation_box_edge"],
            "borderwidth": 1,
        },
        "xaxis": {
            "gridcolor": SUMMARY_PLOT_PALETTE["grid"],
            "zerolinecolor": SUMMARY_PLOT_PALETTE["grid"],
            "linecolor": SUMMARY_PLOT_PALETTE["axis_spine"],
        },
        "yaxis": {
            "gridcolor": SUMMARY_PLOT_PALETTE["grid"],
            "zerolinecolor": SUMMARY_PLOT_PALETTE["grid"],
            "linecolor": SUMMARY_PLOT_PALETTE["axis_spine"],
        },
    }
    _merge_axis_layout(resolved_layout, layout)
    return {
        "id": chart_id,
        "title": title,
        "chart_type": chart_type,
        "plotly_spec": {
            "data": data,
            "layout": resolved_layout,
            "config": {
                "responsive": True,
                "displaylogo": False,
                "scrollZoom": False,
                "modeBarButtonsToRemove": list(PLOTLY_MODEBAR_REMOVE),
            },
        },
    }


def _plot_groups(
    frame: pd.DataFrame,
    *,
    group_columns: list[str] | None = None,
) -> list[tuple[str, pd.DataFrame]]:
    group_columns = group_columns if group_columns is not None else _preferred_group_columns(frame)
    return _grouped_frames(frame, group_columns, default_name="All production rows")


def _chart_group_columns(
    frame: pd.DataFrame,
    aggregation: ProductionAggregationState,
) -> list[str]:
    selected_columns = [
        column
        for column in aggregation.group_fields
        if column in frame.columns and frame[column].nunique(dropna=True) > 1
    ]
    if (
        "reference_cohort" in frame.columns
        and frame["reference_cohort"].nunique(dropna=True) > 1
        and "reference_cohort" not in selected_columns
    ):
        selected_columns.append("reference_cohort")
    return selected_columns or _preferred_group_columns(frame)


def _preferred_group_columns(frame: pd.DataFrame) -> list[str]:
    if "GROUP" in frame.columns and frame["GROUP"].nunique(dropna=True) > 1:
        return ["GROUP"]
    if "reference_cohort" in frame.columns and frame["reference_cohort"].nunique(dropna=True) > 1:
        return ["reference_cohort"]
    for column in ("station", "line", "process_status", "source_db_alias"):
        if column in frame.columns and frame[column].nunique(dropna=True) > 1:
            return [column]
    return []


def _grouped_frames(
    frame: pd.DataFrame,
    group_columns: list[str],
    *,
    default_name: str,
) -> list[tuple[str, pd.DataFrame]]:
    if not group_columns:
        return [(default_name, frame)]
    groups = []
    for key, group in frame.groupby(group_columns, dropna=False, sort=True):
        if not isinstance(key, tuple):
            key = (key,)
        label = " | ".join(str(item) if str(item).strip() else "(blank)" for item in key)
        groups.append((label, group))
    return groups


def _plot_color(index: int, label: str) -> str:
    if "selected" in label.casefold():
        return SUMMARY_PLOT_PALETTE["spec_limit"]
    return PLOT_COLORWAY[index % len(PLOT_COLORWAY)]


def _numeric_values(series: pd.Series) -> list[float]:
    values = pd.to_numeric(series, errors="coerce").dropna()
    return [float(value) for value in values.tolist()]


def _histogram_bins(values: list[float]) -> dict[str, float]:
    if not values:
        return {}
    minimum = min(values)
    maximum = max(values)
    if minimum == maximum:
        padding = max(abs(minimum) * 0.01, 0.5)
        minimum -= padding
        maximum += padding
    binning = resolve_histogram_bin_count(values)
    bin_count = max(1, int(binning.get("bin_count") or 1))
    bin_size = (maximum - minimum) / bin_count
    if bin_size <= 0:
        bin_size = 1.0
    return {"start": minimum, "end": maximum, "size": bin_size}


def _merge_axis_layout(base_layout: dict[str, Any], override: dict[str, Any]) -> None:
    for key, value in override.items():
        if key in {"xaxis", "yaxis"} and isinstance(value, dict):
            axis = base_layout.setdefault(key, {})
            axis.update(value)
        else:
            base_layout[key] = value


def _json_values(series: pd.Series, *, time_bucket: str | None = None) -> list[Any]:
    values: list[Any] = []
    for value in series.tolist():
        if pd.isna(value):
            values.append(None)
        elif time_bucket and time_bucket != "none":
            values.append(_format_time_bucket_value(value, time_bucket))
        elif hasattr(value, "isoformat"):
            values.append(value.isoformat())
        else:
            values.append(value)
    return values


def _format_time_bucket_value(value: Any, time_bucket: str) -> str:
    timestamp = pd.Timestamp(value)
    if timestamp.tzinfo is not None:
        timestamp = timestamp.tz_convert(None)
    if time_bucket == "year":
        return timestamp.strftime("%Y")
    if time_bucket == "month":
        return timestamp.strftime("%Y-%m")
    if time_bucket == "day":
        return timestamp.strftime("%Y-%m-%d")
    if time_bucket == "week":
        return f"Week of {timestamp.strftime('%Y-%m-%d')}"
    if time_bucket == "hour":
        return timestamp.strftime("%Y-%m-%d %H:00")
    return timestamp.isoformat()


def _bucket_axis_title(time_bucket: str) -> str:
    labels = {
        "hour": "Hour",
        "day": "Day",
        "week": "Week starting",
        "month": "Month",
        "year": "Year",
    }
    return labels.get(time_bucket, "Process time")


def _diagnostic_payload(diagnostic: ProductionAnalyticsDiagnostic) -> dict[str, Any]:
    return {
        "severity": diagnostic.severity,
        "code": diagnostic.code,
        "message": diagnostic.message,
        "context": diagnostic.context,
    }


def _groupstats_payload(groupstats_result: ProductionGroupstatsResult | None) -> dict[str, Any]:
    if groupstats_result is None:
        return {"metrics": [], "diagnostics": []}
    return {
        "metrics": list(groupstats_result.metrics),
        "diagnostics": [_diagnostic_payload(diagnostic) for diagnostic in groupstats_result.diagnostics],
    }


def _render_dashboard_html(manifest: dict[str, Any], *, asset_directory_name: str) -> str:
    summary = manifest.get("summary") if isinstance(manifest.get("summary"), dict) else {}
    charts = manifest.get("charts") if isinstance(manifest.get("charts"), list) else []
    diagnostics = manifest.get("diagnostics") if isinstance(manifest.get("diagnostics"), list) else []
    groupstats = manifest.get("groupstats") if isinstance(manifest.get("groupstats"), dict) else {}
    charts_json = json.dumps(charts, ensure_ascii=False).replace("</", "<\\/")
    cards = _render_summary_cards(summary)
    diagnostics_markup = _render_diagnostics(diagnostics)
    groupstats_markup = _render_groupstats(groupstats)
    chart_markup = "".join(_render_chart_shell(chart) for chart in charts)
    dashboard_title = str(summary.get("dashboard_title") or "Production Analytics")
    dashboard_subtitle = str(
        summary.get("dashboard_subtitle") or "Cached production data dashboard generated by Metroliza."
    )
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{html.escape(dashboard_title)}</title>
  <script src="{html.escape(asset_directory_name)}/{PLOTLY_ASSET_NAME}"></script>
  <style>
    :root {{
      color-scheme: light dark;
      --bg: #f6f7f9;
      --panel: #ffffff;
      --text: #1f2933;
      --muted: #687385;
      --line: #d8dde6;
      --accent: #1769aa;
    }}
    @media (prefers-color-scheme: dark) {{
      :root {{
        --bg: #15181d;
        --panel: #20252c;
        --text: #edf1f7;
        --muted: #aab4c2;
        --line: #384250;
        --accent: #5aa9e6;
      }}
    }}
    body {{
      margin: 0;
      background: var(--bg);
      color: var(--text);
      font-family: Inter, Segoe UI, Roboto, Arial, sans-serif;
    }}
    header, main {{
      width: min(1280px, calc(100vw - 32px));
      margin: 0 auto;
    }}
    header {{
      padding: 28px 0 14px;
    }}
    h1 {{
      margin: 0 0 6px;
      font-size: 28px;
      line-height: 1.2;
      letter-spacing: 0;
    }}
    .subtitle {{
      color: var(--muted);
      font-size: 14px;
    }}
    .cards {{
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));
      gap: 10px;
      margin: 18px 0;
    }}
    .card, .chart-card, .diagnostics {{
      background: var(--panel);
      border: 1px solid var(--line);
      border-radius: 8px;
    }}
    .card {{
      padding: 12px 14px;
    }}
    .card-label {{
      color: var(--muted);
      font-size: 12px;
      margin-bottom: 6px;
    }}
    .card-value {{
      font-size: 20px;
      font-weight: 650;
    }}
    .chart-grid {{
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(420px, 1fr));
      gap: 14px;
      padding-bottom: 24px;
    }}
    .chart-card {{
      min-height: 420px;
      padding: 12px;
    }}
    .chart-title {{
      font-size: 15px;
      font-weight: 650;
      margin: 0 0 8px;
    }}
    .plotly-chart {{
      width: 100%;
      height: 360px;
    }}
    .chart-image {{
      width: 100%;
      max-height: 460px;
      object-fit: contain;
      background: #ffffff;
      border: 1px solid var(--line);
      border-radius: 6px;
    }}
    .chart-stats {{
      margin-top: 10px;
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(190px, 1fr));
      gap: 10px;
    }}
    .chart-stats-table {{
      border: 1px solid var(--line);
      border-radius: 6px;
      overflow: hidden;
    }}
    .chart-stats-title {{
      padding: 7px 8px;
      font-size: 12px;
      font-weight: 650;
      background: #eef2f7;
    }}
    .chart-stats table {{
      font-size: 12px;
    }}
    .chart-stats td {{
      padding: 5px 7px;
    }}
    .diagnostics {{
      padding: 12px 14px;
      margin: 0 0 14px;
    }}
    .diagnostics summary {{
      cursor: pointer;
      font-size: 16px;
      font-weight: 650;
      list-style-position: inside;
    }}
    .diagnostics summary::marker {{
      color: var(--accent);
    }}
    .diagnostics ul {{
      margin: 10px 0 0;
      padding-left: 18px;
    }}
    .stats-section {{
      margin: 0 0 14px;
      display: grid;
      gap: 12px;
    }}
    .stats-card {{
      background: var(--panel);
      border: 1px solid var(--line);
      border-radius: 8px;
      padding: 14px;
      overflow-x: auto;
    }}
    .stats-card h2 {{
      margin: 0 0 10px;
      font-size: 17px;
    }}
    .stats-card h3 {{
      margin: 12px 0 8px;
      font-size: 14px;
    }}
    table {{
      border-collapse: collapse;
      width: 100%;
      font-size: 13px;
    }}
    th, td {{
      border-bottom: 1px solid var(--line);
      padding: 7px 8px;
      text-align: left;
      vertical-align: top;
    }}
    th {{
      color: var(--muted);
      font-weight: 650;
      white-space: nowrap;
    }}
    @media (max-width: 640px) {{
      header, main {{
        width: min(100vw - 20px, 1280px);
      }}
      .chart-grid {{
        grid-template-columns: 1fr;
      }}
      .chart-card {{
        min-height: 360px;
      }}
      .plotly-chart {{
        height: 310px;
      }}
    }}
  </style>
</head>
<body>
  <header>
    <h1>{html.escape(dashboard_title)}</h1>
    <div class="subtitle">{html.escape(dashboard_subtitle)}</div>
    {cards}
  </header>
  <main>
    {diagnostics_markup}
    {groupstats_markup}
    <section class="chart-grid">
      {chart_markup}
    </section>
  </main>
  <script id="production-dashboard-charts" type="application/json">{charts_json}</script>
  <script>
    const chartData = JSON.parse(document.getElementById('production-dashboard-charts').textContent);
    for (const chart of chartData) {{
      const target = document.getElementById(chart.id);
      if (!target || !chart.plotly_spec) continue;
      Plotly.newPlot(target, chart.plotly_spec.data, chart.plotly_spec.layout, chart.plotly_spec.config);
    }}
  </script>
</body>
</html>
"""


def _render_summary_cards(summary: dict[str, Any]) -> str:
    rows = (
        ("Rows", summary.get("source_rows")),
        ("Aggregate rows", summary.get("aggregate_rows")),
        ("Metrics", summary.get("metric_count")),
        ("Charts", summary.get("chart_count")),
        ("Bucket", summary.get("time_bucket")),
        ("Aggregation", ", ".join(summary.get("aggregation_methods") or [])),
        ("Reference cohort", summary.get("reference_cohort_count")),
        ("Stats metrics", summary.get("groupstats_metric_count")),
    )
    markup = []
    for label, value in rows:
        markup.append(
            '<div class="card">'
            f'<div class="card-label">{html.escape(str(label))}</div>'
            f'<div class="card-value">{html.escape(str(value if value not in (None, "") else "n/a"))}</div>'
            '</div>'
        )
    return f'<section class="cards">{"".join(markup)}</section>'


def _render_diagnostics(diagnostics: list[dict[str, Any]]) -> str:
    messages = [
        str(item.get("message") or "").strip()
        for item in diagnostics
        if isinstance(item, dict) and str(item.get("message") or "").strip()
    ]
    if not messages:
        return ""
    rows = "".join(f"<li>{html.escape(message)}</li>" for message in messages)
    label = f"Diagnostics ({len(messages)})"
    return f'<details class="diagnostics"><summary>{html.escape(label)}</summary><ul>{rows}</ul></details>'


def _render_groupstats(groupstats: dict[str, Any]) -> str:
    metrics = groupstats.get("metrics") if isinstance(groupstats.get("metrics"), list) else []
    if not metrics:
        return ""
    cards = []
    for metric in metrics:
        if not isinstance(metric, dict):
            continue
        title = str(metric.get("metric") or metric.get("field_name") or "Metric")
        if metric.get("skipped"):
            reason = str(metric.get("skip_reason") or "skipped").replace("_", " ")
            cards.append(
                '<article class="stats-card">'
                f"<h2>{html.escape(title)}</h2>"
                f"<p>Groupstats skipped: {html.escape(reason)}.</p>"
                "</article>"
            )
            continue
        descriptive = _render_table(
            metric.get("descriptive_stats"),
            columns=("group", "n", "mean", "std", "median", "iqr", "min", "max", "cp", "capability"),
        )
        distribution = _render_table(
            metric.get("distribution_rows"),
            columns=(
                "group",
                "n",
                "skewness",
                "excess_kurtosis",
                "normality_test",
                "normality_p_value",
                "normality_status",
            ),
        )
        pairwise = _render_table(
            metric.get("pairwise_rows"),
            columns=("group_a", "group_b", "p_value", "adjusted_p_value", "effect_size", "test_used"),
        )
        insight = metric.get("primary_insight") if isinstance(metric.get("primary_insight"), dict) else {}
        insight_text = str(
            insight.get("headline") or insight.get("first_action") or ""
        ).strip()
        insight_markup = (
            f"<p>{html.escape(insight_text)}</p>"
            if insight_text
            else ""
        )
        cards.append(
            '<article class="stats-card">'
            f"<h2>{html.escape(title)}</h2>"
            f"{insight_markup}"
            "<h3>Descriptive stats</h3>"
            f"{descriptive}"
            "<h3>Distribution checks</h3>"
            f"{distribution}"
            "<h3>Pairwise tests</h3>"
            f"{pairwise}"
            "</article>"
        )
    if not cards:
        return ""
    return f'<section class="stats-section">{"".join(cards)}</section>'


def _render_table(rows: Any, *, columns: tuple[str, ...]) -> str:
    if not isinstance(rows, list) or not rows:
        return "<p>No rows available.</p>"
    header = "".join(f"<th>{html.escape(_table_label(column))}</th>" for column in columns)
    body_rows = []
    for row in rows[:200]:
        if not isinstance(row, dict):
            continue
        cells = "".join(
            f"<td>{html.escape(_format_table_value(row.get(column)))}</td>"
            for column in columns
        )
        body_rows.append(f"<tr>{cells}</tr>")
    if not body_rows:
        return "<p>No rows available.</p>"
    return f"<table><thead><tr>{header}</tr></thead><tbody>{''.join(body_rows)}</tbody></table>"


def _table_label(column: str) -> str:
    return column.replace("_", " ").title()


def _format_table_value(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, float):
        return f"{value:.4g}"
    return str(value)


def _render_chart_shell(chart: dict[str, Any]) -> str:
    chart_id = str(chart.get("id") or "")
    title = str(chart.get("title") or "Chart")
    if not chart_id:
        return ""
    stats_markup = _render_chart_stats_tables(chart.get("stats_tables"))
    image = chart.get("image") if isinstance(chart.get("image"), dict) else {}
    if image.get("base64"):
        alt = str(image.get("alt") or title)
        media_markup = (
            f'<img class="chart-image" alt="{html.escape(alt)}" '
            f'src="data:{html.escape(str(image.get("mime_type") or "image/png"))};base64,{image["base64"]}">'
        )
    else:
        media_markup = f'<div class="plotly-chart" id="{html.escape(chart_id)}"></div>'
    return (
        '<article class="chart-card">'
        f'<div class="chart-title">{html.escape(title)}</div>'
        f"{media_markup}"
        f"{stats_markup}"
        '</article>'
    )


def _render_chart_stats_tables(stats_tables: Any) -> str:
    if not isinstance(stats_tables, list) or not stats_tables:
        return ""
    table_markup = []
    for table in stats_tables[:6]:
        if not isinstance(table, dict):
            continue
        title = str(table.get("title") or "Stats")
        rows = table.get("rows") if isinstance(table.get("rows"), list) else []
        body = []
        for row in rows[:12]:
            if not isinstance(row, dict):
                continue
            body.append(
                "<tr>"
                f"<td>{html.escape(str(row.get('label') or ''))}</td>"
                f"<td>{html.escape(str(row.get('value') or ''))}</td>"
                "</tr>"
            )
        if not body:
            continue
        table_markup.append(
            '<div class="chart-stats-table">'
            f'<div class="chart-stats-title">{html.escape(title)}</div>'
            "<table><thead><tr><th>Statistic</th><th>Value</th></tr></thead>"
            f"<tbody>{''.join(body)}</tbody></table>"
            "</div>"
        )
    if not table_markup:
        return ""
    return f'<div class="chart-stats">{"".join(table_markup)}</div>'


__all__ = [
    "DASHBOARD_SCHEMA",
    "build_production_dashboard_manifest",
    "write_production_dashboard",
]
