"""Offline Plotly dashboard writer for cached production analytics."""

from __future__ import annotations

import base64
from datetime import datetime, timezone
import hashlib
import html
from io import BytesIO
import json
from pathlib import Path
import shutil
from typing import Any

import numpy as np
import pandas as pd

from modules.dashboard_navigation import (
    render_back_to_dashboard_start,
    render_section_navigation_css,
    render_section_header,
    render_section_nav,
    unique_html_id,
)
from modules.export_summary_utils import resolve_histogram_bin_count
from modules.hexafe_plotstats_adapter import (
    build_dashboard_plotly_spec,
    build_histogram_stats_table,
    build_plotstats_dashboard_spec,
    metroliza_dashboard_plotstats_theme,
    plotstats_export_charts_enabled,
    render_histogram_png,
)
from modules.industrial_analytics_service import (
    ProductionAggregationResult,
    ProductionAnalyticsDiagnostic,
    ProductionGroupstatsResult,
)
from modules.industrial_analytics_state import (
    ProductionAggregationState,
    ProductionChartSelection,
    ProductionMetricSelection,
    ReferenceCohortState,
)
from modules.summary_plot_palette import SUMMARY_PLOT_PALETTE


DASHBOARD_SCHEMA = "metroliza.production_analytics_dashboard.v1"
PLOTLY_ASSET_NAME = "plotly-2.27.0.min.js"
PLOTLY_ASSET_SOURCE = Path(__file__).resolve().parent / "html_dashboard_assets" / PLOTLY_ASSET_NAME
PLOTLY_MODEBAR_REMOVE = (
    "select2d",
    "lasso2d",
    "autoScale2d",
    "toggleSpikelines",
    "hoverClosestCartesian",
    "hoverCompareCartesian",
)
PLOT_COLORWAY = (
    SUMMARY_PLOT_PALETTE["distribution_foreground"],
    "#D55E00",
    "#009E73",
    SUMMARY_PLOT_PALETTE["outlier"],
    SUMMARY_PLOT_PALETTE["central_tendency"],
    SUMMARY_PLOT_PALETTE["distribution_base"],
)
_MANUAL_GROUP_FIELD_NAMES = {"group", "group_name", "csv_group", "tabular_group"}
DASHBOARD_RAW_POINT_LIMIT = 50_000
DASHBOARD_AGGREGATE_TRACE_TARGET_POINTS = 2_500


def build_production_dashboard_manifest(
    *,
    frame: pd.DataFrame,
    metric_selection: tuple[ProductionMetricSelection, ...],
    aggregation_state: ProductionAggregationState | None = None,
    aggregation_result: ProductionAggregationResult | None = None,
    groupstats_result: ProductionGroupstatsResult | None = None,
    chart_selection: ProductionChartSelection | None = None,
    cohort_state: ReferenceCohortState | None = None,
    diagnostics: tuple[ProductionAnalyticsDiagnostic, ...] = (),
    dashboard_title: str = "Production Analytics",
    dashboard_subtitle: str = "Cached production data dashboard generated by Metroliza.",
) -> dict[str, Any]:
    """Build a renderer-neutral manifest for the production analytics dashboard."""

    aggregation = aggregation_state or ProductionAggregationState()
    charts = chart_selection or ProductionChartSelection()
    cohort = cohort_state or ReferenceCohortState()
    aggregate_frame = (
        aggregation_result.dataframe
        if aggregation_result is not None and not aggregation_result.dataframe.empty
        else pd.DataFrame()
    )

    chart_specs: list[dict[str, Any]] = []
    for metric in metric_selection:
        if metric.field_name not in frame.columns:
            continue
        metric_frame = frame[frame[metric.field_name].notna()].copy()
        if metric_frame.empty:
            continue
        if charts.time_series:
            group_columns = _chart_group_columns(metric_frame, aggregation)
            specs = _build_time_series_charts(
                metric,
                raw_frame=metric_frame,
                aggregate_frame=aggregate_frame,
                aggregation=aggregation,
                group_columns=group_columns,
            )
            chart_specs.extend(spec for spec in specs if spec)
        if charts.histogram:
            spec = _build_histogram_chart(
                metric,
                metric_frame,
                group_columns=_chart_group_columns(metric_frame, aggregation),
            )
            if spec:
                chart_specs.append(spec)
        if charts.violin:
            spec = _build_distribution_chart(
                metric,
                metric_frame,
                chart_type="violin",
                group_columns=_chart_group_columns(metric_frame, aggregation),
            )
            if spec:
                chart_specs.append(spec)
        if charts.box:
            spec = _build_distribution_chart(
                metric,
                metric_frame,
                chart_type="box",
                group_columns=_chart_group_columns(metric_frame, aggregation),
            )
            if spec:
                chart_specs.append(spec)

    summary = {
        "generated_at": datetime.now(timezone.utc).replace(microsecond=0).isoformat(),
        "source_rows": int(len(frame.index)),
        "aggregate_rows": (
            int(aggregation_result.output_row_count)
            if aggregation_result is not None
            else 0
        ),
        "metric_count": len(metric_selection),
        "chart_count": len(chart_specs),
        "time_bucket": aggregation.time_bucket,
        "aggregation_methods": list(aggregation.aggregation_methods),
        "group_fields": list(aggregation.group_fields),
        "reference_cohort_count": len(cohort.references),
        "reference_cohort_mode": cohort.mode,
        "dashboard_title": dashboard_title,
        "dashboard_subtitle": dashboard_subtitle,
        "groupstats_metric_count": (
            groupstats_result.analyzed_metric_count
            if groupstats_result is not None
            else 0
        ),
    }
    return {
        "schema": DASHBOARD_SCHEMA,
        "summary": summary,
        "metrics": [
            {
                "field_name": metric.field_name,
                "display_label": metric.display_label,
                "source_kind": metric.source_kind,
            }
            for metric in metric_selection
        ],
        "charts": chart_specs,
        "groupstats": _groupstats_payload(groupstats_result),
        "diagnostics": [_diagnostic_payload(diagnostic) for diagnostic in diagnostics],
    }


def write_production_dashboard(
    manifest: dict[str, Any],
    output_path: str | Path,
    *,
    assets_dir: str | Path | None = None,
) -> dict[str, Any]:
    """Write an offline production analytics dashboard and local Plotly asset."""

    destination = Path(output_path)
    if destination.suffix.lower() != ".html":
        destination = destination.with_suffix(".html")
    destination.parent.mkdir(parents=True, exist_ok=True)
    asset_directory = (
        Path(assets_dir)
        if assets_dir is not None
        else destination.with_name(f"{destination.stem}_assets")
    )
    requires_plotly = _manifest_requires_plotly(manifest)
    asset_directory.mkdir(parents=True, exist_ok=True)
    if requires_plotly:
        plotly_target = asset_directory / PLOTLY_ASSET_NAME
        if not plotly_target.exists():
            shutil.copy2(PLOTLY_ASSET_SOURCE, plotly_target)

    html_text = _render_dashboard_html(manifest, asset_directory_name=asset_directory.name)
    destination.write_text(html_text, encoding="utf-8")
    return {
        "html_dashboard_path": str(destination),
        "html_dashboard_assets_path": str(asset_directory),
        "html_dashboard_chart_count": len(manifest.get("charts") or []),
    }


def _manifest_requires_plotly(manifest: dict[str, Any]) -> bool:
    charts = manifest.get("charts") if isinstance(manifest.get("charts"), list) else []
    return any(isinstance(chart, dict) and isinstance(chart.get("plotly_spec"), dict) for chart in charts)


def _build_time_series_charts(
    metric: ProductionMetricSelection,
    *,
    raw_frame: pd.DataFrame,
    aggregate_frame: pd.DataFrame,
    aggregation: ProductionAggregationState,
    group_columns: list[str] | None = None,
) -> list[dict[str, Any]]:
    method = aggregation.aggregation_methods[0] if aggregation.aggregation_methods else "mean"
    aggregate_metric = f"{metric.field_name}__{method}"
    group_columns = group_columns or []
    charts: list[dict[str, Any]] = []
    raw_point_count = _time_series_point_count(
        raw_frame,
        x_column="process_datetime",
        y_column=metric.field_name,
    )
    use_hybrid_raw = raw_point_count > DASHBOARD_RAW_POINT_LIMIT
    if (
        aggregation.is_aggregated
        and not aggregate_frame.empty
        and "time_bucket_start" in aggregate_frame.columns
        and aggregate_metric in aggregate_frame.columns
        and all(column in aggregate_frame.columns for column in group_columns)
    ):
        traces = _time_series_traces(
            aggregate_frame,
            x_column="time_bucket_start",
            y_column=aggregate_metric,
            group_columns=group_columns,
            default_name=f"{metric.display_label} ({method})",
            time_bucket=aggregation.time_bucket,
        )
        if traces:
            charts.append(
                _chart_payload(
                    chart_id=f"time-series-{metric.field_name}-aggregated",
                    title=f"{metric.display_label} over time ({method})",
                    chart_type="time_series",
                    data=traces,
                    layout={
                        "xaxis": {"title": _bucket_axis_title(aggregation.time_bucket)},
                        "yaxis": {"title": f"{metric.display_label} ({method})"},
                        "hovermode": "x unified",
                    },
                )
            )
            overlay_traces = _time_series_traces(
                aggregate_frame,
                x_column="time_bucket_start",
                y_column=aggregate_metric,
                group_columns=group_columns,
                default_name=f"{metric.display_label} aggregate",
                time_bucket=aggregation.time_bucket,
                aggregate_marker=True,
            )
            if use_hybrid_raw:
                hybrid = _build_hybrid_time_series_chart(
                    metric,
                    raw_frame=raw_frame,
                    aggregate_traces=overlay_traces,
                    group_columns=group_columns,
                    chart_id=f"time-series-{metric.field_name}-raw-aggregate",
                    title=f"{metric.display_label} raw values with {method} markers",
                    chart_type="time_series_raw_aggregate",
                    x_axis_title="Process time",
                    y_axis_title=metric.display_label,
                )
                if hybrid:
                    charts.append(hybrid)
                return charts
            raw_traces = _time_series_traces(
                raw_frame,
                x_column="process_datetime",
                y_column=metric.field_name,
                group_columns=group_columns,
                default_name=metric.display_label,
            )
            raw_traces.extend(overlay_traces)
            if raw_traces:
                charts.append(
                    _chart_payload(
                        chart_id=f"time-series-{metric.field_name}-raw-aggregate",
                        title=f"{metric.display_label} raw values with {method} markers",
                        chart_type="time_series_raw_aggregate",
                        data=raw_traces,
                        layout={
                            "xaxis": {"title": "Process time"},
                            "yaxis": {"title": metric.display_label},
                            "hovermode": "closest",
                        },
                    )
                )
        return charts

    if use_hybrid_raw:
        hybrid = _build_hybrid_time_series_chart(
            metric,
            raw_frame=raw_frame,
            aggregate_traces=_display_aggregate_time_series_traces(
                raw_frame,
                x_column="process_datetime",
                y_column=metric.field_name,
                group_columns=group_columns,
                default_name=f"{metric.display_label} aggregate",
            ),
            group_columns=group_columns,
            chart_id=f"time-series-{metric.field_name}",
            title=f"{metric.display_label} over time",
            chart_type="time_series",
            x_axis_title="Process time",
            y_axis_title=metric.display_label,
        )
        return [hybrid] if hybrid else []

    traces = _time_series_traces(
        raw_frame,
        x_column="process_datetime",
        y_column=metric.field_name,
        group_columns=group_columns,
        default_name=metric.display_label,
    )
    if not traces:
        return []
    return [
        _chart_payload(
            chart_id=f"time-series-{metric.field_name}",
            title=f"{metric.display_label} over time",
            chart_type="time_series",
            data=traces,
            layout={
                "xaxis": {"title": "Process time"},
                "yaxis": {"title": metric.display_label},
                "hovermode": "x unified",
            },
        )
    ]


def _build_histogram_chart(
    metric: ProductionMetricSelection,
    frame: pd.DataFrame,
    *,
    group_columns: list[str] | None = None,
) -> dict[str, Any]:
    groups = _plot_groups(frame, group_columns=group_columns)
    image_groups, sampling_note = _sample_plot_groups_for_static_image(
        groups,
        metric.field_name,
        seed_parts=("histogram", metric.field_name),
    )
    stats_tables = _histogram_stats_tables(metric, groups)
    plotly_spec = _build_plotstats_histogram_spec(
        metric,
        groups,
        title=f"{metric.display_label} distribution",
        stats_tables=stats_tables,
    )
    image = (
        None
        if plotly_spec is not None
        else _render_distribution_image(metric, frame, chart_type="histogram", groups=image_groups)
    )
    if not stats_tables and not image and plotly_spec is None:
        return {}
    chart = _static_chart_payload(
        chart_id=f"histogram-{metric.field_name}",
        title=f"{metric.display_label} distribution",
        chart_type="histogram",
        group_labels=[label for label, _group in groups],
        image=image,
        stats_tables=stats_tables,
        notes=([sampling_note] if sampling_note else []),
    )
    if plotly_spec is not None:
        chart["plotly_spec"] = plotly_spec
    return chart


def _build_distribution_chart(
    metric: ProductionMetricSelection,
    frame: pd.DataFrame,
    *,
    chart_type: str,
    group_columns: list[str] | None = None,
) -> dict[str, Any]:
    groups = _plot_groups(frame, group_columns=group_columns)
    image_groups, sampling_note = _sample_plot_groups_for_static_image(
        groups,
        metric.field_name,
        seed_parts=(chart_type, metric.field_name),
    )
    plotly_spec = _build_plotstats_distribution_spec(
        metric,
        groups,
        chart_type=chart_type,
        title=f"{metric.display_label} {chart_type}",
    )
    image = (
        None
        if plotly_spec is not None
        else _render_distribution_image(metric, frame, chart_type=chart_type, groups=image_groups)
    )
    if not image and plotly_spec is None:
        return {}
    chart = _static_chart_payload(
        chart_id=f"{chart_type}-{metric.field_name}",
        title=f"{metric.display_label} {chart_type}",
        chart_type=chart_type,
        group_labels=[label for label, _group in groups],
        image=image,
        notes=([sampling_note] if sampling_note else []),
    )
    if plotly_spec is not None:
        chart["plotly_spec"] = plotly_spec
    return chart


def _build_plotstats_histogram_spec(
    metric: ProductionMetricSelection,
    groups: list[tuple[str, pd.DataFrame]],
    *,
    title: str,
    stats_tables: list[dict[str, Any]],
) -> dict[str, Any] | None:
    payload_groups: list[dict[str, Any]] = []
    all_values: list[float] = []
    for label, group in groups:
        if metric.field_name not in group.columns:
            continue
        values = _finite_numeric_values(group[metric.field_name])
        if not values:
            continue
        payload_groups.append({"group": str(label), "values": values})
        all_values.extend(values)
    if not all_values:
        return None
    bin_count = int(resolve_histogram_bin_count(all_values).get("bin_count") or 0)
    payload: dict[str, Any] = {
        "type": "histogram",
        "title": title,
        "limits": _plotstats_metric_limits(metric),
        "style": {"axis_label_x": metric.display_label, "axis_label_y": "Frequency (%)"},
    }
    if len(payload_groups) == 1:
        payload["values"] = payload_groups[0]["values"]
    else:
        payload["groups"] = payload_groups
    if bin_count > 0:
        payload["bin_count"] = bin_count
    if stats_tables:
        payload["summary_table_rows"] = list(stats_tables[0].get("rows") or [])
    return build_dashboard_plotly_spec(
        payload,
        title=title,
        theme=metroliza_dashboard_plotstats_theme(),
        static=False,
    )


def _build_plotstats_distribution_spec(
    metric: ProductionMetricSelection,
    groups: list[tuple[str, pd.DataFrame]],
    *,
    chart_type: str,
    title: str,
) -> dict[str, Any] | None:
    labels: list[str] = []
    series: list[list[float]] = []
    for label, group in groups:
        if metric.field_name not in group.columns:
            continue
        values = _finite_numeric_values(group[metric.field_name])
        if not values:
            continue
        labels.append(str(label))
        series.append(values)
    if not series:
        return None

    if chart_type == "violin":
        payload_type = "distribution"
        render_mode = "violin"
    elif chart_type == "box":
        payload_type = "iqr"
        render_mode = "iqr"
    else:
        return None

    payload = {
        "type": payload_type,
        "render_mode": render_mode,
        "title": title,
        "labels": labels,
        "series": series,
        "limits": _plotstats_metric_limits(metric),
    }
    return build_dashboard_plotly_spec(
        payload,
        title=title,
        theme=metroliza_dashboard_plotstats_theme(),
        static=False,
    )


def _plotstats_metric_limits(metric: ProductionMetricSelection) -> dict[str, float | None]:
    lsl = _coerce_optional_float(metric.lsl)
    usl = _coerce_optional_float(metric.usl)
    nominal = ((lsl + usl) / 2.0) if lsl is not None and usl is not None and lsl <= usl else None
    return {"lsl": lsl, "nominal": nominal, "usl": usl}


def _coerce_optional_float(value: Any) -> float | None:
    try:
        number = float(value)
    except (TypeError, ValueError):
        return None
    return number if np.isfinite(number) else None


def _finite_numeric_values(series: pd.Series) -> list[float]:
    values = pd.to_numeric(series, errors="coerce").dropna().to_numpy(dtype=float)
    values = values[np.isfinite(values)]
    return [float(value) for value in values.tolist()]


def _build_hybrid_time_series_chart(
    metric: ProductionMetricSelection,
    *,
    raw_frame: pd.DataFrame,
    aggregate_traces: list[dict[str, Any]],
    group_columns: list[str],
    chart_id: str,
    title: str,
    chart_type: str,
    x_axis_title: str,
    y_axis_title: str,
) -> dict[str, Any]:
    raw_layers, sampling_note = _time_series_raw_image_layers(
        raw_frame,
        x_column="process_datetime",
        y_column=metric.field_name,
        group_columns=group_columns,
        default_name=metric.display_label,
        seed_parts=(chart_id, metric.field_name),
    )
    if raw_layers:
        layout_images = [layer["image"] for layer in raw_layers]
        raw_legend_traces = _raw_layer_legend_traces(raw_layers)
    else:
        layout_images = []
        raw_legend_traces = []
    traces = raw_legend_traces + list(aggregate_traces)
    if not traces:
        return {}
    layout = {
        "xaxis": {"title": x_axis_title},
        "yaxis": {"title": y_axis_title},
        "hovermode": "closest",
    }
    if layout_images:
        layout["images"] = layout_images
    chart = _chart_payload(
        chart_id=chart_id,
        title=title,
        chart_type=chart_type,
        data=traces,
        layout=layout,
    )
    if sampling_note:
        chart["notes"] = [sampling_note]
    return chart


def _time_series_point_count(
    frame: pd.DataFrame,
    *,
    x_column: str,
    y_column: str,
) -> int:
    if x_column not in frame.columns or y_column not in frame.columns:
        return 0
    y_series = pd.to_numeric(frame[y_column], errors="coerce")
    return int((frame[x_column].notna() & y_series.notna()).sum())


def _display_aggregate_time_series_traces(
    frame: pd.DataFrame,
    *,
    x_column: str,
    y_column: str,
    group_columns: list[str],
    default_name: str,
) -> list[dict[str, Any]]:
    traces: list[dict[str, Any]] = []
    groups = _grouped_frames(frame, group_columns, default_name=default_name)
    for index, (label, group) in enumerate(groups, start=0):
        xy = _coerce_time_series_xy(group, x_column=x_column, y_column=y_column)
        if xy.empty:
            continue
        xy = xy.sort_values("__x_numeric")
        bucket_count = max(
            1,
            min(
                DASHBOARD_AGGREGATE_TRACE_TARGET_POINTS,
                int(np.ceil(len(xy.index) / max(1, DASHBOARD_RAW_POINT_LIMIT // 10))),
            ),
        )
        chunks = np.array_split(xy[["__x_numeric", "__y"]].to_numpy(dtype=float), bucket_count)
        x_values: list[Any] = []
        y_values: list[float] = []
        for chunk in chunks:
            if chunk.size == 0:
                continue
            x_mean = float(np.mean(chunk[:, 0]))
            y_mean = float(np.mean(chunk[:, 1]))
            x_values.append(_display_x_value(x_mean, mode=str(xy["__x_mode"].iloc[0])))
            y_values.append(y_mean)
        if not x_values:
            continue
        color = _plot_color(index, label)
        traces.append(
            {
                "type": "scatter",
                "mode": "markers",
                "name": f"{label} aggregate",
                "x": x_values,
                "y": y_values,
                "marker": _time_series_marker_style(
                    color=color,
                    symbol="x",
                    point_count=len(x_values),
                    aggregate_marker=True,
                ),
                "hovertemplate": (
                    f"{html.escape(label)} aggregate<br>Time=%{{x}}<br>"
                    "Mean=%{y}<extra></extra>"
                ),
            }
        )
    return traces


def _time_series_raw_image_layers(
    frame: pd.DataFrame,
    *,
    x_column: str,
    y_column: str,
    group_columns: list[str],
    default_name: str,
    seed_parts: tuple[str, ...],
) -> tuple[list[dict[str, Any]], str | None]:
    groups = _grouped_frames(frame, group_columns, default_name=default_name)
    prepared: list[tuple[str, pd.DataFrame]] = []
    total_points = 0
    x_modes: set[str] = set()
    for label, group in groups:
        xy = _coerce_time_series_xy(group, x_column=x_column, y_column=y_column)
        if xy.empty:
            continue
        prepared.append((label, xy))
        total_points += len(xy.index)
        x_modes.add(str(xy["__x_mode"].iloc[0]))
    if not prepared or len(x_modes) != 1:
        return [], None

    mode = next(iter(x_modes))
    x_min = min(float(xy["__x_numeric"].min()) for _label, xy in prepared)
    x_max = max(float(xy["__x_numeric"].max()) for _label, xy in prepared)
    y_min = min(float(xy["__y"].min()) for _label, xy in prepared)
    y_max = max(float(xy["__y"].max()) for _label, xy in prepared)
    if np.isclose(x_min, x_max):
        x_max = x_min + 1.0
    if np.isclose(y_min, y_max):
        y_min -= 0.5
        y_max += 0.5
    else:
        padding = max((y_max - y_min) * 0.04, 1e-9)
        y_min -= padding
        y_max += padding

    allocations = _sample_allocations(
        [len(xy.index) for _label, xy in prepared],
        DASHBOARD_RAW_POINT_LIMIT,
    )
    layers: list[dict[str, Any]] = []
    sampled_points = 0
    for index, ((label, xy), allocation) in enumerate(zip(prepared, allocations, strict=False)):
        if allocation <= 0:
            continue
        source_count = len(xy.index)
        sample_count = min(source_count, allocation)
        sampled = _sample_xy_frame(
            xy,
            sample_count,
            seed=_stable_seed(*seed_parts, label),
        )
        sampled_points += len(sampled.index)
        color = _plot_color(index, label)
        png_bytes = _render_time_series_raw_layer_png(
            sampled["__x_numeric"].to_numpy(dtype=float),
            sampled["__y"].to_numpy(dtype=float),
            x_range=(x_min, x_max),
            y_range=(y_min, y_max),
            color=color,
        )
        layers.append(
            {
                "label": label,
                "color": color,
                "source_point_count": source_count,
                "sampled_point_count": len(sampled.index),
                "image": {
                    "source": (
                        "data:image/png;base64,"
                        + base64.b64encode(png_bytes).decode("ascii")
                    ),
                    "xref": "x",
                    "yref": "y",
                    "x": _display_x_value(x_min, mode=mode),
                    "y": y_max,
                    "sizex": x_max - x_min,
                    "sizey": y_max - y_min,
                    "sizing": "stretch",
                    "layer": "below",
                    "opacity": 1.0,
                    "visible": True,
                    "metroliza_raw_layer": True,
                    "metroliza_raw_layer_label": label,
                },
            }
        )

    sampling_note = None
    if total_points > sampled_points:
        sampling_note = (
            f"Raw layer shows {sampled_points:,} randomly sampled points from "
            f"{total_points:,} rows; statistics use all rows."
        )
    return layers, sampling_note


def _coerce_time_series_xy(
    frame: pd.DataFrame,
    *,
    x_column: str,
    y_column: str,
) -> pd.DataFrame:
    if x_column not in frame.columns or y_column not in frame.columns:
        return pd.DataFrame(columns=["__x_numeric", "__y", "__x_mode"])
    y_series = pd.to_numeric(frame[y_column], errors="coerce")
    x_raw = frame[x_column]
    x_datetime = pd.to_datetime(x_raw, errors="coerce", utc=True)
    non_null_x = int(x_raw.notna().sum())
    datetime_count = int(x_datetime.notna().sum())
    if datetime_count and datetime_count >= max(1, int(non_null_x * 0.8)):
        x_numeric = x_datetime.astype("int64").astype(float) / 1_000_000.0
        mode = "date"
        valid_mask = x_datetime.notna() & y_series.notna()
    else:
        x_numeric = pd.to_numeric(x_raw, errors="coerce")
        mode = "linear"
        valid_mask = x_numeric.notna() & y_series.notna()
    result = pd.DataFrame(
        {
            "__x_numeric": x_numeric.loc[valid_mask].astype(float),
            "__y": y_series.loc[valid_mask].astype(float),
        }
    )
    result = result.replace([np.inf, -np.inf], np.nan).dropna()
    result["__x_mode"] = mode
    return result


def _display_x_value(value: float, *, mode: str) -> Any:
    if mode == "date":
        return pd.Timestamp(value, unit="ms", tz="UTC").isoformat()
    return float(value)


def _raw_layer_legend_traces(raw_layers: list[dict[str, Any]]) -> list[dict[str, Any]]:
    traces: list[dict[str, Any]] = []
    for index, layer in enumerate(raw_layers):
        label = str(layer.get("label") or f"Raw layer {index + 1}")
        traces.append(
            {
                "type": "scatter",
                "mode": "markers",
                "name": f"{label} raw layer",
                "x": [None],
                "y": [None],
                "showlegend": True,
                "hoverinfo": "skip",
                "marker": {
                    "color": str(layer.get("color") or SUMMARY_PLOT_PALETTE["distribution_foreground"]),
                    "size": 8,
                    "symbol": "circle",
                    "opacity": 0.75,
                },
                "metroliza_raw_layer_index": index,
            }
        )
    return traces


def _time_series_traces(
    frame: pd.DataFrame,
    *,
    x_column: str,
    y_column: str,
    group_columns: list[str],
    default_name: str,
    time_bucket: str | None = None,
    aggregate_marker: bool = False,
) -> list[dict[str, Any]]:
    if x_column not in frame.columns or y_column not in frame.columns:
        return []
    traces = []
    groups = _grouped_frames(frame, group_columns, default_name=default_name)
    for index, (label, group) in enumerate(groups, start=0):
        group = group.sort_values(x_column)
        y_series = pd.to_numeric(group[y_column], errors="coerce")
        valid_mask = group[x_column].notna() & y_series.notna()
        group = group.loc[valid_mask].copy()
        y_series = y_series.loc[valid_mask]
        x_values = _json_values(group[x_column], time_bucket=time_bucket)
        y_values = [float(value) for value in y_series.tolist()]
        if not x_values or not y_values:
            continue
        marker_symbol = (
            "x"
            if aggregate_marker
            else ("diamond" if "selected" in label.casefold() else "circle")
        )
        color = _plot_color(index, label)
        trace_name = label
        if aggregate_marker and not label.casefold().endswith("aggregate"):
            trace_name = f"{label} aggregate"
        marker = _time_series_marker_style(
            color=color,
            symbol=marker_symbol,
            point_count=len(x_values),
            aggregate_marker=aggregate_marker,
        )
        traces.append(
            {
                "type": "scatter",
                "mode": "markers",
                "name": trace_name,
                "x": x_values,
                "y": y_values,
                "marker": marker,
                "hovertemplate": f"{html.escape(label)}<br>Time=%{{x}}<br>Value=%{{y}}<extra></extra>",
            }
        )
    return traces


def _histogram_stats_tables(
    metric: ProductionMetricSelection,
    groups: list[tuple[str, pd.DataFrame]],
) -> list[dict[str, Any]]:
    tables: list[dict[str, Any]] = []
    for label, group in groups:
        if metric.field_name not in group.columns:
            continue
        table = build_histogram_stats_table(
            group[metric.field_name],
            title=label,
            backend="metroliza",
            lsl=metric.lsl,
            usl=metric.usl,
        )
        if table is not None:
            tables.append(table.as_dict())
    return tables


def _render_distribution_image(
    metric: ProductionMetricSelection,
    frame: pd.DataFrame,
    *,
    chart_type: str,
    groups: list[tuple[str, pd.DataFrame]] | None = None,
) -> dict[str, str] | None:
    groups = groups if groups is not None else _plot_groups(frame, group_columns=_preferred_group_columns(frame))
    if not groups:
        return None
    if chart_type == "histogram" and len(groups) == 1:
        values = _numeric_values(groups[0][1][metric.field_name])
        rendered = render_histogram_png(
            values,
            title=f"{metric.display_label} distribution",
            metric_label=metric.display_label,
            lsl=metric.lsl,
            usl=metric.usl,
        )
        if rendered is not None:
            return {
                "mime_type": "image/png",
                "base64": base64.b64encode(rendered.png_bytes).decode("ascii"),
                "alt": f"{metric.display_label} distribution",
                "backend": rendered.backend,
            }
    try:
        return _render_matplotlib_distribution_image(metric, groups, chart_type=chart_type)
    except Exception:
        return None


def _render_matplotlib_distribution_image(
    metric: ProductionMetricSelection,
    groups: list[tuple[str, pd.DataFrame]],
    *,
    chart_type: str,
) -> dict[str, str] | None:
    from modules.matplotlib_runtime import configure_headless_matplotlib

    configure_headless_matplotlib()
    import matplotlib.pyplot as plt

    value_groups: list[tuple[str, np.ndarray]] = []
    for label, group in groups:
        values = pd.to_numeric(group[metric.field_name], errors="coerce").dropna().to_numpy(dtype=float)
        values = values[np.isfinite(values)]
        if values.size:
            value_groups.append((label, values))
    if not value_groups:
        return None

    fig, ax = plt.subplots(figsize=(7.8, 4.2))
    try:
        labels = [label for label, _values in value_groups]
        arrays = [values for _label, values in value_groups]
        positions = np.arange(1, len(arrays) + 1)
        if chart_type == "histogram":
            combined = np.concatenate(arrays)
            bins = _histogram_bins([float(value) for value in combined.tolist()])
            bin_count = max(
                1,
                int(round((bins.get("end", 1.0) - bins.get("start", 0.0)) / bins.get("size", 1.0))),
            )
            for index, (label, values) in enumerate(value_groups):
                ax.hist(
                    values,
                    bins=bin_count,
                    alpha=0.52 if len(value_groups) > 1 else 0.82,
                    color=_plot_color(index, label),
                    edgecolor=SUMMARY_PLOT_PALETTE["distribution_foreground"],
                    label=label,
                    density=len(value_groups) > 1,
                )
            ax.set_ylabel("Density" if len(value_groups) > 1 else "Count")
        elif chart_type == "violin":
            parts = ax.violinplot(
                arrays,
                positions=positions,
                showmeans=False,
                showmedians=True,
                showextrema=True,
            )
            for index, body in enumerate(parts.get("bodies", [])):
                body.set_facecolor(_plot_color(index, labels[index]))
                body.set_edgecolor(SUMMARY_PLOT_PALETTE["distribution_foreground"])
                body.set_alpha(0.46)
            ax.set_xticks(positions)
            ax.set_xticklabels(labels, rotation=30 if max(len(label) for label in labels) > 12 else 0, ha="right")
            ax.set_ylabel(metric.display_label)
        else:
            box = ax.boxplot(
                arrays,
                positions=positions,
                patch_artist=True,
                showmeans=True,
                showfliers=True,
                medianprops={"color": SUMMARY_PLOT_PALETTE["central_tendency"], "linewidth": 1.15},
                meanprops={
                    "marker": "o",
                    "markerfacecolor": SUMMARY_PLOT_PALETTE["central_tendency"],
                    "markeredgecolor": SUMMARY_PLOT_PALETTE["central_tendency"],
                    "markersize": 4,
                },
                flierprops={
                    "marker": "o",
                    "markersize": 3,
                    "markerfacecolor": SUMMARY_PLOT_PALETTE["outlier"],
                    "markeredgecolor": SUMMARY_PLOT_PALETTE["outlier"],
                    "alpha": 0.85,
                },
            )
            for patch in box.get("boxes", []):
                patch.set_facecolor(SUMMARY_PLOT_PALETTE["distribution_base"])
                patch.set_edgecolor(SUMMARY_PLOT_PALETTE["distribution_foreground"])
                patch.set_alpha(0.45)
            ax.set_xticks(positions)
            ax.set_xticklabels(labels, rotation=30 if max(len(label) for label in labels) > 12 else 0, ha="right")
            ax.set_ylabel(metric.display_label)

        if chart_type in {"violin", "box"}:
            _annotate_distribution_group_stats(ax, labels, arrays, positions)
        if chart_type == "histogram" and len(value_groups) > 1:
            ax.legend(loc="best", fontsize=8)
        for limit, color, label in (
            (metric.lsl, SUMMARY_PLOT_PALETTE["spec_limit"], "LSL"),
            (metric.usl, SUMMARY_PLOT_PALETTE["spec_limit"], "USL"),
        ):
            if limit is not None and chart_type in {"histogram", "violin", "box"}:
                axis_method = ax.axvline if chart_type == "histogram" else ax.axhline
                axis_method(float(limit), color=color, linestyle="--", linewidth=1.1, label=label)
        ax.set_title(f"{metric.display_label} {chart_type}", color=SUMMARY_PLOT_PALETTE["annotation_text"])
        if chart_type == "histogram":
            ax.set_xlabel(metric.display_label)
        ax.grid(True, axis="y", color=SUMMARY_PLOT_PALETTE["grid"], linewidth=0.5, alpha=0.45)
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        fig.tight_layout()
        image_data = BytesIO()
        fig.savefig(image_data, format="png", dpi=150)
        image_data.seek(0)
        return {
            "mime_type": "image/png",
            "base64": base64.b64encode(image_data.getvalue()).decode("ascii"),
            "alt": f"{metric.display_label} {chart_type}",
            "backend": "matplotlib",
        }
    finally:
        plt.close(fig)


def _annotate_distribution_group_stats(
    ax,
    labels: list[str],
    arrays: list[np.ndarray],
    positions: np.ndarray,
) -> None:
    for label, values, position in zip(labels, arrays, positions, strict=False):
        finite = values[np.isfinite(values)]
        if finite.size == 0:
            continue
        mean_value = float(np.mean(finite))
        median_value = float(np.median(finite))
        text = f"n={finite.size:,}\nmean={mean_value:.3g}\nmedian={median_value:.3g}"
        ax.annotate(
            text,
            xy=(position, mean_value),
            xytext=(0, 12),
            textcoords="offset points",
            ha="center",
            va="bottom",
            fontsize=7,
            color=SUMMARY_PLOT_PALETTE["annotation_text"],
            bbox={
                "boxstyle": "round,pad=0.22",
                "facecolor": "white",
                "edgecolor": SUMMARY_PLOT_PALETTE["annotation_box_edge"],
                "alpha": 0.82,
            },
        )


def _chart_payload(
    *,
    chart_id: str,
    title: str,
    chart_type: str,
    data: list[dict[str, Any]],
    layout: dict[str, Any],
) -> dict[str, Any]:
    resolved_layout = {
        "title": {"text": title, "font": {"size": 18}, "y": 0.99, "yanchor": "top"},
        "font": {"family": 'Aptos, "Segoe UI", "Helvetica Neue", sans-serif', "color": "#1f2933"},
        "paper_bgcolor": "#ffffff",
        "plot_bgcolor": "#ffffff",
        "colorway": list(PLOT_COLORWAY),
        "dragmode": "zoom",
        "margin": {"l": 56, "r": 24, "t": 116, "b": 56},
        "hoverlabel": {"bgcolor": "#ffffff", "font": {"color": "#1f2933"}},
        "legend": {
            "orientation": "h",
            "yanchor": "bottom",
            "y": 1.11,
            "xanchor": "left",
            "x": 0.0,
            "bgcolor": "rgba(255,255,255,0.86)",
            "bordercolor": SUMMARY_PLOT_PALETTE["annotation_box_edge"],
            "borderwidth": 1,
        },
        "xaxis": {
            "gridcolor": SUMMARY_PLOT_PALETTE["grid"],
            "zerolinecolor": SUMMARY_PLOT_PALETTE["grid"],
            "linecolor": SUMMARY_PLOT_PALETTE["axis_spine"],
        },
        "yaxis": {
            "gridcolor": SUMMARY_PLOT_PALETTE["grid"],
            "zerolinecolor": SUMMARY_PLOT_PALETTE["grid"],
            "linecolor": SUMMARY_PLOT_PALETTE["axis_spine"],
        },
    }
    _merge_axis_layout(resolved_layout, layout)
    if plotstats_export_charts_enabled():
        spec = build_plotstats_dashboard_spec(
            {
                "type": chart_type,
                "title": title,
                "traces": data,
                "layout": resolved_layout,
            },
            title=title,
            theme="light",
            static=False,
        )
        if spec:
            return {
                "id": chart_id,
                "title": title,
                "chart_type": chart_type,
                "plotly_spec": spec,
            }
    return {
        "id": chart_id,
        "title": title,
        "chart_type": chart_type,
        "plotly_spec": {
            "data": data,
            "layout": resolved_layout,
            "config": {
                "responsive": True,
                "displaylogo": False,
                "scrollZoom": False,
                "modeBarButtonsToRemove": list(PLOTLY_MODEBAR_REMOVE),
            },
        },
    }


def _static_chart_payload(
    *,
    chart_id: str,
    title: str,
    chart_type: str,
    group_labels: list[str],
    image: dict[str, str] | None = None,
    stats_tables: list[dict[str, Any]] | None = None,
    notes: list[str] | None = None,
) -> dict[str, Any]:
    chart: dict[str, Any] = {
        "id": chart_id,
        "title": title,
        "chart_type": chart_type,
        "group_labels": [str(label) for label in group_labels],
    }
    if image:
        chart["image"] = image
    if stats_tables:
        chart["stats_tables"] = stats_tables
    if notes:
        chart["notes"] = [str(note) for note in notes if str(note).strip()]
    return chart


def _plot_groups(
    frame: pd.DataFrame,
    *,
    group_columns: list[str] | None = None,
) -> list[tuple[str, pd.DataFrame]]:
    group_columns = group_columns if group_columns is not None else _preferred_group_columns(frame)
    return _grouped_frames(frame, group_columns, default_name="All production rows")


def _chart_group_columns(
    frame: pd.DataFrame,
    aggregation: ProductionAggregationState,
) -> list[str]:
    selected_columns = [
        column
        for column in aggregation.group_fields
        if column in frame.columns and frame[column].nunique(dropna=True) > 1
    ]
    if (
        "reference_cohort" in frame.columns
        and frame["reference_cohort"].nunique(dropna=True) > 1
        and "reference_cohort" not in selected_columns
    ):
        selected_columns.append("reference_cohort")
    return selected_columns or _preferred_group_columns(frame)


def _preferred_group_columns(frame: pd.DataFrame) -> list[str]:
    if "GROUP" in frame.columns and frame["GROUP"].nunique(dropna=True) > 1:
        return ["GROUP"]
    if "reference_cohort" in frame.columns and frame["reference_cohort"].nunique(dropna=True) > 1:
        return ["reference_cohort"]
    for column in ("station", "line", "process_status", "source_db_alias"):
        if column in frame.columns and frame[column].nunique(dropna=True) > 1:
            return [column]
    return []


def _grouped_frames(
    frame: pd.DataFrame,
    group_columns: list[str],
    *,
    default_name: str,
) -> list[tuple[str, pd.DataFrame]]:
    if not group_columns:
        return [(default_name, frame)]
    groups = []
    for key, group in frame.groupby(group_columns, dropna=False, sort=True):
        if not isinstance(key, tuple):
            key = (key,)
        label = " | ".join(str(item) if str(item).strip() else "(blank)" for item in key)
        groups.append((label, group))
    return groups


def _plot_color(index: int, label: str) -> str:
    if "selected" in label.casefold():
        return SUMMARY_PLOT_PALETTE["spec_limit"]
    return PLOT_COLORWAY[index % len(PLOT_COLORWAY)]


def _raw_marker_size(point_count: int, *, selected: bool = False) -> float:
    if point_count >= 10_000:
        base = 3.0
    elif point_count >= 3_000:
        base = 4.0
    elif point_count >= 1_000:
        base = 5.0
    elif point_count >= 300:
        base = 6.0
    else:
        base = 7.0
    return min(base + (0.75 if selected else 0.0), 8.0)


def _raw_marker_opacity(point_count: int, *, selected: bool = False) -> float:
    if point_count >= 10_000:
        base = 0.42
    elif point_count >= 3_000:
        base = 0.52
    elif point_count >= 1_000:
        base = 0.62
    elif point_count >= 300:
        base = 0.72
    else:
        base = 0.82
    return min(base + (0.1 if selected else 0.0), 0.9)


def _raw_marker_line_width(point_count: int, *, selected: bool = False) -> float:
    if point_count >= 1_000:
        return 0.25 if selected else 0.0
    return 0.45 if selected else 0.35


def _time_series_marker_style(
    *,
    color: str,
    symbol: str,
    point_count: int,
    aggregate_marker: bool,
) -> dict[str, Any]:
    if aggregate_marker:
        return {
            "color": color,
            "size": 8,
            "symbol": symbol,
            "opacity": 0.94,
            "line": {"color": "#111827", "width": 1.4},
        }

    selected = symbol == "diamond"
    return {
        "color": color,
        "size": _raw_marker_size(point_count, selected=selected),
        "symbol": symbol,
        "opacity": _raw_marker_opacity(point_count, selected=selected),
        "line": {
            "color": color,
            "width": _raw_marker_line_width(point_count, selected=selected),
        },
    }


def _numeric_values(series: pd.Series) -> list[float]:
    values = pd.to_numeric(series, errors="coerce").dropna()
    return [float(value) for value in values.tolist()]


def _sample_plot_groups_for_static_image(
    groups: list[tuple[str, pd.DataFrame]],
    metric_field_name: str,
    *,
    seed_parts: tuple[str, ...],
) -> tuple[list[tuple[str, pd.DataFrame]], str | None]:
    counts = [
        int(pd.to_numeric(group[metric_field_name], errors="coerce").notna().sum())
        if metric_field_name in group.columns
        else 0
        for _label, group in groups
    ]
    total = sum(counts)
    if total <= DASHBOARD_RAW_POINT_LIMIT:
        return groups, None
    allocations = _sample_allocations(counts, DASHBOARD_RAW_POINT_LIMIT)
    sampled_groups: list[tuple[str, pd.DataFrame]] = []
    sampled_total = 0
    for (label, group), allocation, count in zip(groups, allocations, counts, strict=False):
        if count <= 0 or allocation <= 0 or metric_field_name not in group.columns:
            sampled_groups.append((label, group.iloc[0:0].copy()))
            continue
        valid_index = pd.to_numeric(group[metric_field_name], errors="coerce").dropna().index
        valid_group = group.loc[valid_index]
        sample_size = min(len(valid_group.index), allocation)
        sampled = valid_group.sample(
            n=sample_size,
            random_state=_stable_seed(*seed_parts, label),
        ) if sample_size < len(valid_group.index) else valid_group
        sampled_groups.append((label, sampled))
        sampled_total += len(sampled.index)
    note = (
        f"Plot image shows {sampled_total:,} randomly sampled points from "
        f"{total:,} rows; statistics use all rows."
    )
    return sampled_groups, note


def _sample_allocations(counts: list[int], limit: int) -> list[int]:
    total = sum(max(0, int(count)) for count in counts)
    if total <= 0 or limit <= 0:
        return [0 for _count in counts]
    if total <= limit:
        return [max(0, int(count)) for count in counts]
    raw_allocations = [max(0.0, (max(0, int(count)) / total) * limit) for count in counts]
    allocations = [
        min(max(0, int(count)), max(1, int(np.floor(raw))))
        if int(count) > 0
        else 0
        for count, raw in zip(counts, raw_allocations, strict=False)
    ]
    while sum(allocations) > limit:
        candidates = [
            (allocation, index)
            for index, allocation in enumerate(allocations)
            if allocation > 1
        ]
        if not candidates:
            break
        _allocation, index = max(candidates)
        allocations[index] -= 1
    while sum(allocations) < limit:
        candidates = [
            (
                raw_allocations[index] - allocations[index],
                max(0, int(counts[index])) - allocations[index],
                index,
            )
            for index in range(len(allocations))
            if allocations[index] < max(0, int(counts[index]))
        ]
        if not candidates:
            break
        _fraction, _remaining, index = max(candidates)
        allocations[index] += 1
    return allocations


def _sample_xy_frame(frame: pd.DataFrame, sample_size: int, *, seed: int) -> pd.DataFrame:
    if sample_size >= len(frame.index):
        return frame.sort_values("__x_numeric")
    return frame.sample(n=sample_size, random_state=seed).sort_values("__x_numeric")


def _stable_seed(*parts: str) -> int:
    digest = hashlib.sha256("|".join(str(part) for part in parts).encode("utf-8")).hexdigest()
    return int(digest[:8], 16)


def _render_time_series_raw_layer_png(
    x_values: np.ndarray,
    y_values: np.ndarray,
    *,
    x_range: tuple[float, float],
    y_range: tuple[float, float],
    color: str,
) -> bytes:
    from modules.matplotlib_runtime import configure_headless_matplotlib

    configure_headless_matplotlib()
    import matplotlib.pyplot as plt

    fig, ax = plt.subplots(figsize=(9.6, 3.8), dpi=120)
    try:
        fig.patch.set_alpha(0.0)
        ax.set_facecolor((1.0, 1.0, 1.0, 0.0))
        ax.scatter(
            x_values,
            y_values,
            s=0.16,
            alpha=0.18,
            c=color,
            marker=".",
            linewidths=0,
            rasterized=True,
        )
        ax.set_xlim(*x_range)
        ax.set_ylim(*y_range)
        ax.axis("off")
        fig.subplots_adjust(0, 0, 1, 1)
        image_data = BytesIO()
        fig.savefig(image_data, format="png", transparent=True, dpi=120)
        image_data.seek(0)
        return image_data.getvalue()
    finally:
        plt.close(fig)


def _histogram_bins(values: list[float]) -> dict[str, float]:
    if not values:
        return {}
    minimum = min(values)
    maximum = max(values)
    if minimum == maximum:
        padding = max(abs(minimum) * 0.01, 0.5)
        minimum -= padding
        maximum += padding
    binning = resolve_histogram_bin_count(values)
    bin_count = max(1, int(binning.get("bin_count") or 1))
    bin_size = (maximum - minimum) / bin_count
    if bin_size <= 0:
        bin_size = 1.0
    return {"start": minimum, "end": maximum, "size": bin_size}


def _merge_axis_layout(base_layout: dict[str, Any], override: dict[str, Any]) -> None:
    for key, value in override.items():
        if key in {"xaxis", "yaxis"} and isinstance(value, dict):
            axis = base_layout.setdefault(key, {})
            axis.update(value)
        elif key in {"shapes", "annotations"} and isinstance(value, list):
            base_layout.setdefault(key, [])
            base_layout[key].extend(value)
        else:
            base_layout[key] = value


def _metric_reference_markings(
    metric: ProductionMetricSelection,
    values: list[float],
    *,
    axis: str,
) -> dict[str, list[dict[str, Any]]]:
    finite_values = np.asarray(values, dtype=float)
    finite_values = finite_values[np.isfinite(finite_values)]
    markings: list[tuple[str, float, str, str]] = []
    if metric.lsl is not None:
        markings.append(("LSL", float(metric.lsl), SUMMARY_PLOT_PALETTE["spec_limit"], "dash"))
    if metric.usl is not None:
        markings.append(("USL", float(metric.usl), SUMMARY_PLOT_PALETTE["spec_limit"], "dash"))
    if finite_values.size:
        markings.append(("Mean", float(np.mean(finite_values)), SUMMARY_PLOT_PALETTE["central_tendency"], "solid"))
        markings.append(("Median", float(np.median(finite_values)), SUMMARY_PLOT_PALETTE["annotation_text"], "dot"))
    if not markings:
        return {}

    shapes = []
    annotations = []
    for label, value, color, dash in markings:
        if axis == "y":
            shapes.append(
                {
                    "type": "line",
                    "xref": "paper",
                    "yref": "y",
                    "x0": 0,
                    "x1": 1,
                    "y0": value,
                    "y1": value,
                    "line": {"color": color, "width": 1.1, "dash": dash},
                }
            )
            annotations.append(
                {
                    "xref": "paper",
                    "yref": "y",
                    "x": 1.01,
                    "y": value,
                    "text": label,
                    "showarrow": False,
                    "xanchor": "left",
                    "font": {"size": 11, "color": color},
                }
            )
        else:
            shapes.append(
                {
                    "type": "line",
                    "xref": "x",
                    "yref": "paper",
                    "x0": value,
                    "x1": value,
                    "y0": 0,
                    "y1": 1,
                    "line": {"color": color, "width": 1.1, "dash": dash},
                }
            )
            annotations.append(
                {
                    "xref": "x",
                    "yref": "paper",
                    "x": value,
                    "y": 1.04,
                    "text": label,
                    "showarrow": False,
                    "yanchor": "bottom",
                    "font": {"size": 11, "color": color},
                }
            )
    return {"shapes": shapes, "annotations": annotations}


def _json_values(series: pd.Series, *, time_bucket: str | None = None) -> list[Any]:
    values: list[Any] = []
    for value in series.tolist():
        if pd.isna(value):
            values.append(None)
        elif time_bucket and time_bucket != "none":
            values.append(_format_time_bucket_value(value, time_bucket))
        elif hasattr(value, "isoformat"):
            values.append(value.isoformat())
        else:
            values.append(value)
    return values


def _format_time_bucket_value(value: Any, time_bucket: str) -> str:
    timestamp = pd.Timestamp(value)
    if timestamp.tzinfo is not None:
        timestamp = timestamp.tz_convert(None)
    if time_bucket == "year":
        return timestamp.strftime("%Y")
    if time_bucket == "month":
        return timestamp.strftime("%Y-%m")
    if time_bucket == "day":
        return timestamp.strftime("%Y-%m-%d")
    if time_bucket == "week":
        return f"Week of {timestamp.strftime('%Y-%m-%d')}"
    if time_bucket == "hour":
        return timestamp.strftime("%Y-%m-%d %H:00")
    return timestamp.isoformat()


def _bucket_axis_title(time_bucket: str) -> str:
    labels = {
        "hour": "Hour",
        "day": "Day",
        "week": "Week starting",
        "month": "Month",
        "year": "Year",
    }
    return labels.get(time_bucket, "Process time")


def _diagnostic_payload(diagnostic: ProductionAnalyticsDiagnostic) -> dict[str, Any]:
    return {
        "severity": diagnostic.severity,
        "code": diagnostic.code,
        "message": diagnostic.message,
        "context": diagnostic.context,
    }


def _groupstats_payload(groupstats_result: ProductionGroupstatsResult | None) -> dict[str, Any]:
    if groupstats_result is None:
        return {"metrics": [], "diagnostics": []}
    return {
        "metrics": list(groupstats_result.metrics),
        "diagnostics": [_diagnostic_payload(diagnostic) for diagnostic in groupstats_result.diagnostics],
    }


def _render_dashboard_html(manifest: dict[str, Any], *, asset_directory_name: str) -> str:
    summary = manifest.get("summary") if isinstance(manifest.get("summary"), dict) else {}
    charts = manifest.get("charts") if isinstance(manifest.get("charts"), list) else []
    diagnostics = manifest.get("diagnostics") if isinstance(manifest.get("diagnostics"), list) else []
    groupstats = manifest.get("groupstats") if isinstance(manifest.get("groupstats"), dict) else {}
    plotly_charts = _plotly_chart_payloads(charts)
    charts_json = json.dumps(plotly_charts, ensure_ascii=False).replace("</", "<\\/")
    plotly_script = (
        f'  <script src="{html.escape(asset_directory_name)}/{PLOTLY_ASSET_NAME}"></script>'
        if plotly_charts
        else ""
    )
    plotly_runtime = _render_plotly_runtime(charts_json) if plotly_charts else ""
    cards = _render_summary_cards(summary)
    diagnostics_markup = _render_diagnostics(diagnostics)
    groupstats_markup = _render_groupstats(groupstats)
    dashboard_title = str(summary.get("dashboard_title") or "Production Analytics")
    dashboard_subtitle = str(
        summary.get("dashboard_subtitle") or "Cached production data dashboard generated by Metroliza."
    )
    used_section_ids = {"dashboard-start", "diagnostics", "groupstats"}
    nav_items: list[dict[str, str]] = []
    if diagnostics_markup:
        nav_items.append({"id": "diagnostics", "label": "Diagnostics"})
        diagnostics_markup = _render_dashboard_section(
            section_id="diagnostics",
            title="Diagnostics",
            body=diagnostics_markup,
        )
    if groupstats_markup:
        nav_items.append({"id": "groupstats", "label": "Groupstats"})
        groupstats_markup = _render_dashboard_section(
            section_id="groupstats",
            title="Groupstats",
            body=groupstats_markup,
        )
    chart_sections = []
    for chart in charts:
        if not isinstance(chart, dict):
            continue
        chart_title = str(chart.get("title") or chart.get("id") or "Chart")
        section_id = unique_html_id(
            f"chart-{chart.get('id') or chart_title}",
            used_section_ids,
            fallback="chart",
        )
        nav_items.append({"id": section_id, "label": chart_title})
        chart_sections.append(_render_chart_section(chart, section_id=section_id))
    chart_markup = "".join(chart_sections)
    nav_markup = render_section_nav(nav_items)
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{html.escape(dashboard_title)}</title>
{plotly_script}
  <style>
    :root {{
      color-scheme: light dark;
      --bg: #f6f7f9;
      --panel: #ffffff;
      --text: #1f2933;
      --muted: #687385;
      --line: #d8dde6;
      --accent: #1769aa;
    }}
    @media (prefers-color-scheme: dark) {{
      :root {{
        --bg: #15181d;
        --panel: #20252c;
        --text: #edf1f7;
        --muted: #aab4c2;
        --line: #384250;
        --accent: #5aa9e6;
      }}
    }}
    html {{
      scroll-behavior: smooth;
    }}
    body {{
      margin: 0;
      background: var(--bg);
      color: var(--text);
      font-family: Inter, Segoe UI, Roboto, Arial, sans-serif;
    }}
    header, main {{
      width: min(1280px, calc(100vw - 32px));
      margin: 0 auto;
    }}
    header {{
      padding: 28px 0 14px;
    }}
    h1 {{
      margin: 0 0 6px;
      font-size: 28px;
      line-height: 1.2;
      letter-spacing: 0;
    }}
    .subtitle {{
      color: var(--muted);
      font-size: 14px;
    }}
    .cards {{
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));
      gap: 10px;
      margin: 18px 0;
    }}
{render_section_navigation_css("compact")}
    .dashboard-section {{
      margin-bottom: 14px;
      scroll-margin-top: 18px;
    }}
    .section-top {{
      display: flex;
      justify-content: space-between;
      gap: 12px;
      align-items: flex-start;
      margin: 0 0 10px;
    }}
    .section-top h2 {{
      margin: 0;
      font-size: 18px;
      line-height: 1.25;
    }}
    .section-meta {{
      color: var(--muted);
      font-size: 13px;
      margin-top: 3px;
    }}
    .section-actions {{
      display: flex;
      justify-content: flex-end;
    }}
    .card, .chart-card, .diagnostics {{
      background: var(--panel);
      border: 1px solid var(--line);
      border-radius: 8px;
    }}
    .card {{
      padding: 12px 14px;
    }}
    .card-label {{
      color: var(--muted);
      font-size: 12px;
      margin-bottom: 6px;
    }}
    .card-value {{
      font-size: 20px;
      font-weight: 650;
    }}
    .chart-grid {{
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(min(100%, 420px), 1fr));
      gap: 14px;
      padding-bottom: 24px;
    }}
    .chart-card {{
      min-height: 420px;
      padding: 12px;
    }}
    .chart-title {{
      font-size: 15px;
      font-weight: 650;
      margin: 0 0 8px;
    }}
    .plotly-chart {{
      width: 100%;
      height: 360px;
    }}
    .chart-image {{
      width: 100%;
      max-height: 360px;
      object-fit: contain;
      background: #ffffff;
      border: 1px solid var(--line);
      border-radius: 6px;
    }}
    .chart-snapshot {{
      margin-top: 10px;
    }}
    .chart-snapshot summary {{
      cursor: pointer;
      color: var(--muted);
      font-size: 12px;
      margin-bottom: 6px;
    }}
    .chart-notes {{
      margin: 10px 0 0;
      padding-left: 18px;
      color: var(--muted);
      font-size: 12px;
      line-height: 1.35;
    }}
    .chart-stats {{
      margin-top: 10px;
    }}
    .chart-stats summary {{
      cursor: pointer;
      color: var(--muted);
      font-size: 12px;
      font-weight: 650;
      margin-bottom: 8px;
    }}
    .chart-stats-grid {{
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(190px, 1fr));
      gap: 10px;
    }}
    .chart-stats-table {{
      border: 1px solid var(--line);
      border-radius: 6px;
      overflow: hidden;
    }}
    .chart-stats-title {{
      padding: 7px 8px;
      font-size: 12px;
      font-weight: 650;
      background: #eef2f7;
    }}
    .chart-stats table {{
      font-size: 12px;
    }}
    .chart-stats th {{
      padding: 6px 7px;
      background: #1f2937;
      color: #ffffff;
      border-bottom: 1px solid #111827;
      text-align: left;
    }}
    .chart-stats td {{
      padding: 5px 7px;
    }}
    .diagnostics {{
      padding: 12px 14px;
      margin: 0 0 14px;
    }}
    .diagnostics summary {{
      cursor: pointer;
      font-size: 16px;
      font-weight: 650;
      list-style-position: inside;
    }}
    .diagnostics summary::marker {{
      color: var(--accent);
    }}
    .diagnostics ul {{
      margin: 10px 0 0;
      padding-left: 18px;
    }}
    .stats-section {{
      margin: 0 0 14px;
      background: var(--panel);
      border: 1px solid var(--line);
      border-radius: 8px;
      padding: 12px 14px;
    }}
    .stats-section > summary {{
      cursor: pointer;
      font-size: 17px;
      font-weight: 650;
      list-style-position: inside;
    }}
    .stats-section-grid {{
      display: grid;
      gap: 12px;
      margin-top: 12px;
    }}
    .stats-card {{
      background: var(--panel);
      border: 1px solid var(--line);
      border-radius: 8px;
      padding: 14px;
      overflow-x: auto;
    }}
    .stats-card h2 {{
      margin: 0 0 10px;
      font-size: 17px;
    }}
    .stats-card > summary {{
      cursor: pointer;
      font-size: 15px;
      font-weight: 650;
      list-style-position: inside;
    }}
    .stats-card-body {{
      margin-top: 10px;
    }}
    .stats-subsection {{
      border-top: 1px solid var(--line);
      margin-top: 10px;
      padding-top: 10px;
    }}
    .stats-subsection summary {{
      cursor: pointer;
      font-size: 14px;
      font-weight: 650;
      margin-bottom: 8px;
    }}
    table {{
      border-collapse: collapse;
      width: 100%;
      font-size: 13px;
    }}
    th, td {{
      border-bottom: 1px solid var(--line);
      padding: 7px 8px;
      text-align: left;
      vertical-align: top;
    }}
    th {{
      color: var(--muted);
      font-weight: 650;
      white-space: nowrap;
    }}
    @media (max-width: 640px) {{
      header, main {{
        width: min(100vw - 20px, 1280px);
      }}
      .chart-grid {{
        grid-template-columns: 1fr;
      }}
      .chart-card {{
        min-height: 360px;
      }}
      .plotly-chart {{
        height: 310px;
      }}
    }}
  </style>
</head>
<body>
  <header id="dashboard-start">
    <h1>{html.escape(dashboard_title)}</h1>
    <div class="subtitle">{html.escape(dashboard_subtitle)}</div>
    {cards}
    {nav_markup}
  </header>
  <main>
    {diagnostics_markup}
    {groupstats_markup}
    {chart_markup}
  </main>
{plotly_runtime}
</body>
</html>
"""


def _plotly_chart_payloads(charts: list[Any]) -> list[dict[str, Any]]:
    payloads: list[dict[str, Any]] = []
    for chart in charts:
        if not isinstance(chart, dict) or not isinstance(chart.get("plotly_spec"), dict):
            continue
        payloads.append(
            {
                "id": chart.get("id"),
                "plotly_spec": chart.get("plotly_spec"),
            }
        )
    return payloads


def _render_dashboard_section(*, section_id: str, title: str, body: str, subtitle: str = "") -> str:
    if not str(body or "").strip():
        return ""
    header = render_section_header(
        title,
        subtitle,
        actions=render_back_to_dashboard_start(),
    )
    return (
        f'<section id="{html.escape(section_id)}" class="dashboard-section">'
        f"{header}{body}"
        "</section>"
    )


def _render_chart_section(chart: dict[str, Any], *, section_id: str) -> str:
    title = str(chart.get("title") or chart.get("id") or "Chart")
    subtitle_parts = [
        str(chart.get("chart_type") or "").replace("_", " ").title(),
        str(chart.get("field_name") or "").strip(),
    ]
    subtitle = " | ".join(part for part in subtitle_parts if part)
    header = render_section_header(
        title,
        subtitle,
        actions=render_back_to_dashboard_start(),
    )
    return (
        f'<section id="{html.escape(section_id)}" class="dashboard-section">'
        f"{header}"
        f'<div class="chart-grid">{_render_chart_shell(chart)}</div>'
        "</section>"
    )


def _render_plotly_runtime(charts_json: str) -> str:
    return f"""
  <script id="production-dashboard-charts" type="application/json">{charts_json}</script>
  <script>
    const chartData = JSON.parse(document.getElementById('production-dashboard-charts').textContent);
    for (const chart of chartData) {{
      const target = document.getElementById(chart.id);
      if (!target || !chart.plotly_spec) continue;
      Plotly.newPlot(target, chart.plotly_spec.data, chart.plotly_spec.layout, chart.plotly_spec.config);
      if (typeof target.on === 'function') {{
        target.on('plotly_legendclick', function(eventData) {{
          const curveNumber = eventData && typeof eventData.curveNumber === 'number' ? eventData.curveNumber : -1;
          const trace = (chart.plotly_spec.data || [])[curveNumber];
          if (!trace || typeof trace.metroliza_raw_layer_index !== 'number') return true;
          const imageIndex = trace.metroliza_raw_layer_index;
          const images = (target.layout && target.layout.images) || [];
          const image = images[imageIndex] || {{}};
          const nextVisible = image.visible === false;
          const update = {{}};
          update[`images[${{imageIndex}}].visible`] = nextVisible;
          Plotly.relayout(target, update);
          Plotly.restyle(target, {{ visible: nextVisible ? true : 'legendonly' }}, [curveNumber]);
          return false;
        }});
      }}
    }}
  </script>
"""


def _render_summary_cards(summary: dict[str, Any]) -> str:
    markup = []
    for label, value in _summary_card_rows(summary):
        markup.append(
            '<div class="card">'
            f'<div class="card-label">{html.escape(str(label))}</div>'
            f'<div class="card-value">{html.escape(str(value if value not in (None, "") else "n/a"))}</div>'
            '</div>'
        )
    return f'<section class="cards">{"".join(markup)}</section>'


def _summary_int(value: Any) -> int | None:
    try:
        if value in (None, ""):
            return None
        return int(value)
    except (TypeError, ValueError):
        return None


def _friendly_time_bucket(value: Any) -> str:
    bucket = str(value or "").strip()
    if not bucket or bucket.casefold() in {"none", "raw", "raw rows"}:
        return ""
    labels = {
        "minute": "By minute",
        "hour": "Hourly",
        "day": "Daily",
        "week": "Weekly",
        "month": "Monthly",
    }
    return labels.get(bucket.casefold(), bucket.replace("_", " ").title())


def _friendly_aggregation_methods(value: Any) -> str:
    if isinstance(value, str):
        methods = [value]
    elif isinstance(value, (list, tuple, set)):
        methods = [str(item) for item in value]
    else:
        methods = []
    labels = [method.strip().replace("_", " ").title() for method in methods if method.strip()]
    return ", ".join(labels)


def _friendly_group_field_name(value: Any) -> str:
    raw = str(value or "").strip()
    folded = raw.casefold()
    if not raw:
        return ""
    if raw == "GROUP" or folded in _MANUAL_GROUP_FIELD_NAMES:
        return "Manual groups"
    if folded == "reference_cohort":
        return "Pasted reference cohorts"
    return raw.replace("_", " ").title()


def _friendly_group_fields(value: Any) -> str:
    if isinstance(value, str):
        fields = [value]
    elif isinstance(value, (list, tuple, set)):
        fields = list(value)
    else:
        fields = []
    labels: list[str] = []
    seen: set[str] = set()
    for field in fields:
        label = _friendly_group_field_name(field)
        if not label:
            continue
        key = label.casefold()
        if key in seen:
            continue
        seen.add(key)
        labels.append(label)
    return ", ".join(labels)


def _plural_summary_count(count: int, singular: str, plural: str | None = None) -> str:
    return f"{count} {singular if count == 1 else (plural or singular + 's')}"


def _summary_card_rows(summary: dict[str, Any]) -> tuple[tuple[str, Any], ...]:
    rows: list[tuple[str, Any]] = [
        ("Rows", summary.get("source_rows")),
    ]
    aggregate_rows = _summary_int(summary.get("aggregate_rows"))
    if aggregate_rows and aggregate_rows > 0:
        rows.append(("Rows after aggregation", aggregate_rows))
    rows.extend(
        [
            ("Metrics", summary.get("metric_count")),
            ("Charts", summary.get("chart_count")),
        ]
    )

    time_bucket = _friendly_time_bucket(summary.get("time_bucket"))
    if time_bucket:
        rows.append(("Time bucket", time_bucket))

    aggregation = _friendly_aggregation_methods(summary.get("aggregation_methods"))
    if aggregation:
        rows.append(("Aggregation", aggregation))

    group_fields = _friendly_group_fields(summary.get("group_fields"))
    if group_fields:
        rows.append(("Groups", group_fields))

    reference_count = _summary_int(summary.get("reference_cohort_count"))
    if reference_count and reference_count > 0:
        rows.append(("Pasted references", reference_count))

    groupstats_metric_count = _summary_int(summary.get("groupstats_metric_count"))
    if groupstats_metric_count and groupstats_metric_count > 0:
        rows.append(
            (
                "Groupstats",
                _plural_summary_count(groupstats_metric_count, "metric"),
            )
        )

    return tuple(rows)


def _render_diagnostics(diagnostics: list[dict[str, Any]]) -> str:
    messages = [
        str(item.get("message") or "").strip()
        for item in diagnostics
        if isinstance(item, dict) and str(item.get("message") or "").strip()
    ]
    if not messages:
        return ""
    rows = "".join(f"<li>{html.escape(message)}</li>" for message in messages)
    label = f"Diagnostics ({len(messages)})"
    return f'<details class="diagnostics"><summary>{html.escape(label)}</summary><ul>{rows}</ul></details>'


def _render_groupstats(groupstats: dict[str, Any]) -> str:
    metrics = groupstats.get("metrics") if isinstance(groupstats.get("metrics"), list) else []
    if not metrics:
        return ""
    cards = []
    for metric in metrics:
        if not isinstance(metric, dict):
            continue
        title = str(metric.get("metric") or metric.get("field_name") or "Metric")
        if metric.get("skipped"):
            reason = str(metric.get("skip_reason") or "skipped").replace("_", " ")
            cards.append(
                '<details class="stats-card">'
                f"<summary>{html.escape(title)}</summary>"
                '<div class="stats-card-body">'
                f"<p>Groupstats skipped: {html.escape(reason)}.</p>"
                "</div>"
                "</details>"
            )
            continue
        descriptive_rows = metric.get("descriptive_stats")
        distribution_rows = metric.get("distribution_rows")
        omnibus_rows = _groupstats_omnibus_rows(metric.get("omnibus"))
        pairwise_rows = metric.get("pairwise_rows")
        posthoc_rows = metric.get("posthoc_rows")
        descriptive = _render_collapsible_table_section(
            "Descriptive stats",
            descriptive_rows,
            columns=("group", "n", "mean", "std", "median", "iqr", "min", "max", "cp", "capability"),
        )
        distribution = _render_collapsible_table_section(
            "Distribution checks",
            distribution_rows,
            columns=(
                "group",
                "n",
                "skewness",
                "excess_kurtosis",
                "normality_test",
                "normality_p_value",
                "normality_status",
            ),
        )
        omnibus = _render_collapsible_table_section(
            "Overall group test",
            omnibus_rows,
            columns=("test_name", "p_value", "effect_size", "effect_type", "significant"),
        )
        pairwise = _render_collapsible_table_section(
            "Pairwise tests",
            pairwise_rows,
            columns=(
                "group_a",
                "group_b",
                "delta_mean",
                "p_value",
                "adjusted_p_value",
                "effect_size",
                "effect_type",
                "significant",
                "test_used",
            ),
        )
        posthoc = _render_collapsible_table_section(
            "Post-hoc tests",
            posthoc_rows,
            columns=(
                "group_a",
                "group_b",
                "method_name",
                "family",
                "adjusted_p_value",
                "effect_size",
                "effect_type",
                "significant",
            ),
        )
        insight = metric.get("primary_insight") if isinstance(metric.get("primary_insight"), dict) else {}
        insight_parts = [
            str(insight.get("headline") or "").strip(),
            str(insight.get("why") or "").strip(),
            str(insight.get("first_action") or "").strip(),
        ]
        insight_text = " ".join(part for part in insight_parts if part).strip()
        insight_markup = (
            f"<p>{html.escape(insight_text)}</p>"
            if insight_text
            else ""
        )
        cards.append(
            '<details class="stats-card">'
            f"<summary>{html.escape(title)}</summary>"
            '<div class="stats-card-body">'
            f"{insight_markup}"
            f"{descriptive}"
            f"{distribution}"
            f"{omnibus}"
            f"{pairwise}"
            f"{posthoc}"
            "</div>"
            "</details>"
        )
    if not cards:
        return ""
    label = _plural_summary_count(len(cards), "metric")
    return (
        '<details class="stats-section">'
        f"<summary>Groupstats ({html.escape(label)})</summary>"
        f'<div class="stats-section-grid">{"".join(cards)}</div>'
        "</details>"
    )


def _groupstats_omnibus_rows(value: Any) -> list[dict[str, Any]]:
    if not isinstance(value, dict) or not value:
        return []
    return [value]


def _render_table(rows: Any, *, columns: tuple[str, ...]) -> str:
    if not isinstance(rows, list) or not rows:
        return "<p>No rows available.</p>"
    header = "".join(f"<th>{html.escape(_table_label(column))}</th>" for column in columns)
    body_rows = []
    for row in rows[:200]:
        if not isinstance(row, dict):
            continue
        cells = "".join(
            f"<td>{html.escape(_format_table_value(row.get(column)))}</td>"
            for column in columns
        )
        body_rows.append(f"<tr>{cells}</tr>")
    if not body_rows:
        return "<p>No rows available.</p>"
    return f"<table><thead><tr>{header}</tr></thead><tbody>{''.join(body_rows)}</tbody></table>"


def _row_count(rows: Any) -> int:
    return len(rows) if isinstance(rows, list) else 0


def _render_collapsible_table_section(
    title: str,
    rows: Any,
    *,
    columns: tuple[str, ...],
) -> str:
    row_count = _row_count(rows)
    label = f"{title} ({_plural_summary_count(row_count, 'row')})"
    return (
        '<details class="stats-subsection">'
        f"<summary>{html.escape(label)}</summary>"
        f"{_render_table(rows, columns=columns)}"
        "</details>"
    )


def _table_label(column: str) -> str:
    return column.replace("_", " ").title()


def _format_table_value(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, float):
        return f"{value:.4g}"
    return str(value)


def _render_chart_shell(chart: dict[str, Any]) -> str:
    chart_id = str(chart.get("id") or "")
    title = str(chart.get("title") or "Chart")
    if not chart_id:
        return ""
    stats_markup = _render_chart_stats_tables(chart.get("stats_tables"))
    notes_markup = _render_chart_notes(chart.get("notes"))
    image = chart.get("image") if isinstance(chart.get("image"), dict) else {}
    has_plotly = isinstance(chart.get("plotly_spec"), dict)
    snapshot_markup = ""
    if image.get("base64"):
        alt = str(image.get("alt") or title)
        image_markup = (
            f'<img class="chart-image" alt="{html.escape(alt)}" '
            f'src="data:{html.escape(str(image.get("mime_type") or "image/png"))};base64,{image["base64"]}">'
        )
        if has_plotly:
            snapshot_markup = (
                '<details class="chart-snapshot">'
                '<summary>Static snapshot</summary>'
                f"{image_markup}"
                "</details>"
            )
            media_markup = f'<div class="plotly-chart" id="{html.escape(chart_id)}"></div>'
        else:
            media_markup = image_markup
    else:
        media_markup = (
            f'<div class="plotly-chart" id="{html.escape(chart_id)}"></div>'
            if has_plotly
            else ""
        )
    return (
        '<article class="chart-card">'
        f'<div class="chart-title">{html.escape(title)}</div>'
        f"{media_markup}"
        f"{snapshot_markup}"
        f"{notes_markup}"
        f"{stats_markup}"
        '</article>'
    )


def _render_chart_notes(notes: Any) -> str:
    if not isinstance(notes, list) or not notes:
        return ""
    rows = "".join(
        f"<li>{html.escape(str(note))}</li>"
        for note in notes
        if str(note).strip()
    )
    if not rows:
        return ""
    return f'<ul class="chart-notes">{rows}</ul>'


def _render_chart_stats_tables(stats_tables: Any) -> str:
    if not isinstance(stats_tables, list) or not stats_tables:
        return ""
    table_markup = []
    for table in stats_tables[:6]:
        if not isinstance(table, dict):
            continue
        title = str(table.get("title") or "Stats")
        rows = table.get("rows") if isinstance(table.get("rows"), list) else []
        body = []
        for row in rows[:12]:
            if not isinstance(row, dict):
                continue
            body.append(
                "<tr>"
                f"<td>{html.escape(str(row.get('label') or ''))}</td>"
                f"<td>{html.escape(str(row.get('value') or ''))}</td>"
                "</tr>"
            )
        if not body:
            continue
        table_markup.append(
            '<div class="chart-stats-table">'
            f'<div class="chart-stats-title">{html.escape(title)}</div>'
            "<table><thead><tr><th>Statistic</th><th>Value</th></tr></thead>"
            f"<tbody>{''.join(body)}</tbody></table>"
            "</div>"
        )
    if not table_markup:
        return ""
    label = f"Chart statistics ({_plural_summary_count(len(table_markup), 'table')})"
    return (
        '<details class="chart-stats">'
        f"<summary>{html.escape(label)}</summary>"
        f'<div class="chart-stats-grid">{"".join(table_markup)}</div>'
        "</details>"
    )


__all__ = [
    "DASHBOARD_SCHEMA",
    "build_production_dashboard_manifest",
    "write_production_dashboard",
]
