from __future__ import annotations

import zipfile
from pathlib import Path

import pandas as pd
import pytest

from modules.industrial_analytics_state import (
    ProductionAggregationState,
    ProductionChartSelection,
    ProductionMetricSelection,
    ReferenceCohortState,
)
from modules.industrial_analytics_workflow import (
    AnalyticsCancelled,
    run_production_cache_analytics,
    run_tabular_file_analytics,
)
from tests.industrial_analytics_fixtures import seed_production_analytics_cache


def test_run_production_cache_analytics_writes_dashboard_and_workbook(tmp_path) -> None:
    db_path = str(tmp_path / "production_only.db")
    seed_production_analytics_cache(db_path)
    dashboard_file = tmp_path / "production_analytics.html"
    workbook_file = tmp_path / "production_analytics.xlsx"
    progress_messages: list[str] = []

    result = run_production_cache_analytics(
        db_file=db_path,
        output_dashboard_file=str(dashboard_file),
        output_workbook_file=str(workbook_file),
        metric_selection=(ProductionMetricSelection("cycle_time_s"),),
        aggregation_state=ProductionAggregationState(
            time_bucket="day",
            aggregation_methods=("mean",),
            group_fields=("line",),
        ),
        cohort_state=ReferenceCohortState.from_text("REF-100", mode="compare_rest"),
        chart_selection=ProductionChartSelection(
            time_series=True,
            histogram=True,
            violin=True,
            box=True,
            groupstats=True,
        ),
        separate_parameter_sheets=True,
        progress_callback=progress_messages.append,
    )

    assert Path(result.html_dashboard_path).exists()
    assert Path(result.workbook_path).exists()
    assert result.row_count == 16
    assert result.metric_count == 1
    assert result.groupstats_metric_count == 1
    assert result.parameter_sheet_count == 1
    assert {"Production Data", "Aggregates", "Metrics", "Groupstats", "Diagnostics"}.issubset(
        result.workbook_sheet_names
    )
    assert "Charts" in result.workbook_sheet_names
    with zipfile.ZipFile(workbook_file) as workbook_zip:
        names = set(workbook_zip.namelist())
    assert any(name.startswith("xl/charts/chart") for name in names)
    assert any(name.startswith("xl/media/image") for name in names)
    production_columns = pd.read_excel(workbook_file, sheet_name="Production Data").columns
    assert "raw_record_json" not in production_columns
    assert progress_messages
    assert progress_messages[0].startswith("Loading production data...")
    assert any(message.startswith("Writing dashboard...") for message in progress_messages)
    assert progress_messages[-1].startswith("Analytics complete")
    assert all("ETA" in message for message in progress_messages)


def test_run_tabular_file_analytics_reuses_shared_dashboard_and_parameter_workbook(tmp_path) -> None:
    input_file = tmp_path / "table.csv"
    dashboard_file = tmp_path / "table_analytics.html"
    workbook_file = tmp_path / "table_analytics.xlsx"
    pd.DataFrame(
        {
            "Time Stamp": pd.date_range("2026-05-10 08:00", periods=6, freq="12h"),
            "Reference ID": ["R1", "R1", "R2", "R2", "R3", "R3"],
            "Line": ["L1", "L1", "L2", "L2", "L1", "L2"],
            "Length mm": [10.0, 10.1, 10.2, 10.4, 10.3, 10.5],
            "Width mm": [5.0, 5.1, 5.2, 5.4, 5.3, 5.5],
        }
    ).to_csv(input_file, index=False)
    progress_messages: list[str] = []

    result = run_tabular_file_analytics(
        input_file=str(input_file),
        output_dashboard_file=str(dashboard_file),
        output_workbook_file=str(workbook_file),
        metric_selection=(ProductionMetricSelection("length_mm", display_label="Length mm"),),
        aggregation_state=ProductionAggregationState(
            time_bucket="day",
            aggregation_methods=("mean",),
            group_fields=("line",),
        ),
        chart_selection=ProductionChartSelection(groupstats=True),
        separate_parameter_sheets=True,
        progress_callback=progress_messages.append,
    )

    assert Path(result.html_dashboard_path).exists()
    assert Path(result.workbook_path).exists()
    html_text = dashboard_file.read_text(encoding="utf-8")
    assert "CSV / Excel Analytics" in html_text
    assert "CSV/Excel data dashboard generated by Metroliza." in html_text
    assert "Cached production data dashboard" not in html_text
    assert result.source_kind == "tabular_file"
    assert result.metric_count == 1
    assert result.parameter_sheet_count == 1
    assert "Length Mm" in result.workbook_sheet_names
    assert "Charts" in result.workbook_sheet_names
    with zipfile.ZipFile(workbook_file) as workbook_zip:
        names = set(workbook_zip.namelist())
    assert any(name.startswith("xl/charts/chart") for name in names)
    assert progress_messages
    assert progress_messages[0].startswith("Loading CSV/Excel data...")
    assert any(message.startswith("Writing dashboard...") for message in progress_messages)
    assert progress_messages[-1].startswith("Analytics complete")
    assert all("ETA" in message for message in progress_messages)


def test_run_tabular_file_analytics_uses_manual_population_grouping(tmp_path) -> None:
    input_file = tmp_path / "table.csv"
    dashboard_file = tmp_path / "grouped_table_analytics.html"
    workbook_file = tmp_path / "grouped_table_analytics.xlsx"
    pd.DataFrame(
        {
            "Time Stamp": pd.date_range("2026-05-10 08:00", periods=6, freq="12h"),
            "Reference ID": ["R1", "R1", "R2", "R2", "R3", "R3"],
            "Length mm": [10.0, 10.1, 10.2, 10.4, 10.3, 10.5],
        }
    ).to_csv(input_file, index=False)
    grouping_df = pd.DataFrame(
        {
            "REPORT_ID": [1, 2, 3, 4, 5, 6],
            "GROUP": ["Selected", "Selected", "POPULATION", "POPULATION", "POPULATION", ""],
        }
    )

    result = run_tabular_file_analytics(
        input_file=str(input_file),
        output_dashboard_file=str(dashboard_file),
        output_workbook_file=str(workbook_file),
        metric_selection=(ProductionMetricSelection("length_mm", display_label="Length mm"),),
        grouping_df=grouping_df,
        aggregation_state=ProductionAggregationState(
            time_bucket="none",
            aggregation_methods=("mean",),
        ),
        chart_selection=ProductionChartSelection(groupstats=True),
        separate_parameter_sheets=False,
    )

    assert result.metric_count == 1
    assert result.groupstats_metric_count == 1
    table_data = pd.read_excel(workbook_file, sheet_name="Table Data")
    assert set(table_data["GROUP"]) == {"POPULATION", "Selected"}
    aggregates = pd.read_excel(workbook_file, sheet_name="Aggregates")
    assert set(aggregates["GROUP"]) == {"POPULATION", "Selected"}
    assert "tabular_grouping_applied" in {diagnostic.code for diagnostic in result.diagnostics}


def test_run_tabular_file_analytics_applies_visual_row_filter_before_outputs(tmp_path) -> None:
    input_file = tmp_path / "filtered_table.csv"
    dashboard_file = tmp_path / "filtered_table_analytics.html"
    workbook_file = tmp_path / "filtered_table_analytics.xlsx"
    pd.DataFrame(
        {
            "Time Stamp": pd.date_range("2026-05-10 08:00", periods=4, freq="h"),
            "TraceCode": ["TC-001", "TC-002", "TC-003", "TC-004"],
            "Line": ["L1", "L2", "L1", "L2"],
            "Length mm": [10.0, 10.2, 10.4, 10.6],
        }
    ).to_csv(input_file, index=False)

    result = run_tabular_file_analytics(
        input_file=str(input_file),
        output_dashboard_file=str(dashboard_file),
        output_workbook_file=str(workbook_file),
        metric_selection=(ProductionMetricSelection("length_mm", display_label="Length mm"),),
        tabular_filter_columns=("tracecode",),
        tabular_filter_keys=(("TC-001",), ("TC-003",)),
        aggregation_state=ProductionAggregationState(
            time_bucket="none",
            aggregation_methods=("mean",),
            group_fields=("line",),
        ),
        chart_selection=ProductionChartSelection(groupstats=False),
        separate_parameter_sheets=False,
    )

    table_data = pd.read_excel(workbook_file, sheet_name="Table Data")
    assert result.row_count == 2
    assert table_data["tracecode"].tolist() == ["TC-001", "TC-003"]
    assert "tabular_filters_applied" in {diagnostic.code for diagnostic in result.diagnostics}


def test_run_production_cache_analytics_cancel_removes_temp_outputs(tmp_path) -> None:
    db_path = str(tmp_path / "production_only.db")
    seed_production_analytics_cache(db_path)
    dashboard_file = tmp_path / "production_analytics.html"
    workbook_file = tmp_path / "production_analytics.xlsx"
    calls = {"count": 0}

    def cancel_after_dashboard_write() -> bool:
        calls["count"] += 1
        return calls["count"] >= 7

    with pytest.raises(AnalyticsCancelled):
        run_production_cache_analytics(
            db_file=db_path,
            output_dashboard_file=str(dashboard_file),
            output_workbook_file=str(workbook_file),
            metric_selection=(ProductionMetricSelection("cycle_time_s"),),
            chart_selection=ProductionChartSelection(time_series=True, histogram=False),
            cancel_check=cancel_after_dashboard_write,
        )

    assert not dashboard_file.exists()
    assert not workbook_file.exists()
    assert not list(tmp_path.glob(".production_analytics.*.tmp.html"))
    assert not list(tmp_path.glob(".production_analytics.*.tmp.xlsx"))
